import type { CreatureStatBlock } from './creatures';

export const CREATURES_B: CreatureStatBlock[] = [
  {
    slug: 'lakava',
    name: 'Lakava',
    pageTitle: 'Lakava',
    cv: 1,
    hp: 15,
    av: 1,
    avNote: 'natural',
    speed: '30 ft.',
    class: 'Monster',
    type: 'Navirite (Fey)',
    horror: '1/1d4 (First Encounter), 0/1d2 (Maniacal Laugh)',
    treasure: 'Standard',
    characteristics: { STR: 8, CON: 10, SIZ: 5, INT: 10, ACU: 9, DEX: 16, SOC: 8 },
    attacks: ['2 Claws 65% 1d6+1+1d4 wither and Bite 55% 1d6+1+1d4 wither'],
    skills: 'Dodge 50%, Grapple 45%, Hide 55%, Listen 50%, Spot 55%, Stealth 55%, Acrobatics 55%',
    special: ['Maniacal Laugh', 'Withering Attacks'],
    weaknesses: 'Cold Iron',
    habitat: 'Any',
    encounter: 'Solitary',
  },
  {
    slug: 'lich',
    name: 'Lich (Abravian Devolos, the Lich of the Wastes)',
    pageTitle: 'Lich',
    cv: 5,
    hp: 90,
    av: 15,
    avNote: 'natural 7 + magical protections',
    speed: '60 ft.',
    dmgMod: '+1d4',
    class: 'Monster',
    type: 'Undead',
    horror: '2/2d6+1 (First Encounter), 1/1d6 (Fear Aura)',
    treasure: 'Double (includes Legacy Items, see below)',
    characteristics: { STR: 12, SIZ: 15, INT: 20, ACU: 16, DEX: 14, SOC: 16 },
    attacks: ['(2) Ritual Dagger 75% 1d4+1+1d4+ Paralyzing Touch', '(2) Touch 75% 1d8+5 negative energy (also heals undead)'],
    skills: 'Dodge 50%, Grapple 50%, Hide 50%, Listen 60%, Spot 65%, Stealth 55%, Acrobatics 55%, Athletics 55%, Knowledge 80%, Persuasion 65%, Spellcraft 90%',
    special: ['Energy Burst', 'Energy Blast', 'Energy Wall', 'Call of the Elements', 'Paralyzing Touch', 'Fear Aura', 'Ravaging', 'Spellcasting (Luminar 8)', 'Spell Sight', 'Undead Traits', 'Darkvision 90 ft.', 'Immortal (Arcanima bound)'],
    weaknesses: 'Legacy & Magic weapons bypass DR, Arcanima (must be destroyed or lich reforms in 1d10 days)',
    habitat: 'Wastes, ancient fortresses',
    encounter: 'Solitary',
  },
  {
    slug: 'merfolk',
    name: 'Merfolk',
    pageTitle: 'Merfolk',
    cv: 2,
    hp: 24,
    av: 2,
    speed: '5 ft., Swim 50 ft.',
    dmgMod: '+1d4',
    class: 'Monster',
    type: 'Navirite (Aquatic)',
    horror: '1/1d6 (Song of the Deep)',
    treasure: 'Standard',
    characteristics: { STR: 12, CON: 14, SIZ: 14, INT: 10, ACU: 11, DEX: 12, SOC: 8 },
    attacks: ['Trident 65% 1d8+2+1d4', 'Bite 65% 1d8+2+1d4'],
    skills: 'Dodge 50%, Grapple 55%, Hide 50%, Listen 50%, Spot 55%, Stealth 50%, Acrobatics 50%, Athletics 55%, Survival 55%',
    special: ['Amphibious', 'Disguise', 'Fascinating Bulb', 'Song of the Deep', 'Low-Light Vision', 'Spell-like Ability (Polymorph 3/day)'],
    weaknesses: 'None',
    habitat: 'Temperate Aquatic',
    encounter: 'Sliver (2–4)',
  },
  {
    slug: 'miglin',
    name: 'Miglin',
    pageTitle: 'Miglin',
    cv: 0.5,
    hp: 3,
    av: 0,
    speed: '20\'',
    dmgMod: '-2',
    class: 'Monster',
    type: 'Navirite',
    horror: '1/1d3',
    treasure: 'Wandering: None; Lair: 1d3 gems (worth 1 gp)',
    characteristics: { STR: 6, CON: 3, SIZ: 3, INT: 8, ACU: 8, DEX: 8, SOC: 1 },
    attacks: ['(2) Arm Spikes 45% 1d6-2'],
    skills: 'Spot 25%, Stealth 40%, Hide 40%, Dodge 40%, Other Skills 15%',
    special: ['Dark vision 60\'', 'Weak 1/2 HP'],
    weaknesses: 'Bright Light, Cold Iron (x2 damage)',
  },
  {
    slug: 'minotaur',
    name: 'Minotaur',
    pageTitle: 'Minotaur',
    cv: 3,
    hp: 39,
    av: 5,
    avNote: 'natural hide+leather armor',
    speed: '30 ft.',
    dmgMod: '+2d6',
    class: 'Being',
    type: 'Humanoid (Giant)',
    horror: 'None (Being)',
    treasure: 'Standard',
    characteristics: { STR: 18, CON: 14, SIZ: 25, INT: 8, ACU: 12, DEX: 10, SOC: 9 },
    attacks: ['Greataxe 75% 2d8+3+2d6 and Gore 65% 1d8+2+2d6', 'Ranged Longbow 65% 1d8+3+2d6'],
    skills: 'Dodge 65%, Grapple 60%, Hide 60%, Listen 60%, Spot 60%, Stealth 60%, Track 65%',
    special: ['Powerful Charge', 'Natural Cunning', 'Scent', 'Track', 'Darkvision 60 ft.', 'Special Attack: Powerful Charge (see below)'],
    weaknesses: 'None',
    habitat: 'Underground',
    encounter: 'Solitary, Pair, or Gang (3–4)',
  },
  {
    slug: 'mummy',
    name: 'Mummy',
    pageTitle: 'Mummy',
    cv: 3,
    hp: 32,
    av: 10,
    avNote: 'natural',
    speed: '20 ft.',
    dmgMod: '+2d6',
    class: 'Monster',
    type: 'Undead',
    horror: '1/1d6 (First Encounter)',
    treasure: 'Standard',
    characteristics: { STR: 20, SIZ: 16, INT: 8, ACU: 12, DEX: 10, SOC: 14 },
    attacks: ['Slam 70% 1d8+3+2d6 + Mummy Rot'],
    skills: 'Dodge 50%, Grapple 65%, Hide 45%, Listen 55%, Spot 55%, Stealth 45%',
    special: ['Despair', 'Mummy Rot', 'Darkvision 60 ft.', 'Damage Resistance 5/-'],
    weaknesses: 'Fire; Silver',
    habitat: 'Any',
    encounter: 'Solitary, Warden Squad (2–4), or Guardian Detail (6–10)',
  },
  {
    slug: 'mummy',
    name: 'Mummy, Greater',
    pageTitle: 'Mummy',
    cv: 5,
    hp: 72,
    av: 12,
    avNote: 'natural',
    speed: '25 ft.',
    dmgMod: '+3d6',
    class: 'Monster',
    type: 'Undead',
    horror: '2/1d10+1 (First Encounter)',
    treasure: 'Standard (often entombed relics)',
    characteristics: { STR: 24, SIZ: 18, INT: 10, ACU: 13, DEX: 10, SOC: 16 },
    attacks: ['Slam 80% 1d8+5+3d6 + Greater Mummy Rot'],
    skills: 'Dodge 50%, Grapple 75%, Hide 45%, Listen 60%, Spot 60%, Stealth 45%',
    special: ['Despairing Aura', 'Greater Mummy Rot', 'Darkvision 60 ft.', 'Damage Resistance 8/-'],
    weaknesses: 'Fire',
    habitat: 'Tombs, Deserts, Ruins',
    encounter: 'Solitary, Tomb Guard (2–4), or Royal Entourage (6–10 lesser mummies)',
  },
  {
    slug: 'mummy',
    name: 'Mummy Lord',
    pageTitle: 'Mummy',
    cv: 6,
    hp: 90,
    av: 14,
    avNote: 'natural + ceremonial armor',
    speed: '30 ft.',
    dmgMod: '+4d6',
    class: 'Monster',
    type: 'Undead',
    horror: '2/1d12+1 (First Encounter, aura of dread)',
    treasure: 'Double (ancient relics, cursed treasures)',
    characteristics: { STR: 26, SIZ: 20, INT: 14, ACU: 14, DEX: 10, SOC: 18 },
    attacks: ['Slam 95% 1d8+6+4d6 + Rotting Curse'],
    skills: 'Dodge 50%, Grapple 75%, Hide 40%, Listen 65%, Spot 65%, Stealth 40%, Knowledge (Ancient Lore) 75%, Spellcraft 80%',
    special: ['Despairing Aura', 'Rotting Curse', 'Priest of the Dead', 'Darkvision 90 ft.', 'DR 10/-'],
    weaknesses: 'Fire, Dispel/Consecrate effects',
    habitat: 'Tombs, Forgotten Temples',
    encounter: 'Solitary or with 2–6 greater mummies',
  },
  {
    slug: 'ogre',
    name: 'Ogre',
    pageTitle: 'Ogre',
    cv: 2,
    hp: 42,
    av: 2,
    avNote: 'thick hide',
    speed: '30’',
    dmgMod: '+2d6',
    class: 'Being',
    type: 'Giant',
    characteristics: { STR: 21, CON: 18, SIZ: 24, INT: 7, ACU: 8, DEX: 11, SOC: 8 },
    attacks: ['Giant Club 65% 2d6+2+dm', 'Giant Javelin 60% 2d6+2+dm'],
    skills: 'Dodge 40%, Grapple 50%, Hide 40%, Listen 50%, Spot 50%, Stealth 40%',
    special: [],
    habitat: 'Any',
    encounter: 'Solitary or Pair',
  },
  {
    slug: 'orlock',
    name: 'Orlock Drone',
    pageTitle: 'Orlock',
    cv: 2,
    hp: 21,
    av: 2,
    speed: '25',
    dmgMod: '1d4',
    class: 'Monster',
    type: 'Aberration',
    horror: '1/1d6',
    treasure: 'Poor (resin-covered tools, dried fungi rations)',
    characteristics: { STR: 12, CON: 11, SIZ: 10, INT: 7, ACU: 10, DEX: 10, SOC: 5 },
    attacks: ['(2) Chitin Blade 60% 1d6+1+1d4'],
    skills: 'Awareness 50%, Climb 45%, Stealth 40%, Survival 50%',
    special: ['Hive Instinct (+10% to rolls when near another Orlock)'],
    weaknesses: 'Fire',
  },
  {
    slug: 'orlock',
    name: 'Orlock Scavenger',
    pageTitle: 'Orlock',
    cv: 0.5,
    hp: 6,
    av: 2,
    avNote: 'chitin armor',
    speed: '30',
    dmgMod: '0',
    class: 'Monster',
    type: 'Fey (Athelesian)',
    horror: '1/1d4',
    treasure: 'Average',
    characteristics: { STR: 8, CON: 8, SIZ: 8, INT: 6, ACU: 8, DEX: 10, SOC: 6 },
    attacks: ['Shortsword 45% 1d6+0'],
    skills: 'Stealth 55%, Thievery 55%, Awareness 25%, Trapmaking 45%, Other Skills 15%',
    special: ['Sneak Attack (bonus damage if target is Distracted, Flanked, or Flat-footed)', 'Trapmaking (CR1 traps; sample: Camouflaged Pit, Spear Trap)', 'Hivemind (shared awareness within 500 ft.)', 'Darkvision 60 ft.', 'Low-Light Vision'],
    weaknesses: 'Cold iron',
  },
  {
    slug: 'orlock',
    name: 'Orlock Predator',
    pageTitle: 'Orlock',
    cv: 1,
    hp: 15,
    av: 4,
    avNote: 'chitin armor',
    speed: '30',
    dmgMod: '+1',
    class: 'Monster',
    type: 'Fey (Athelesian)',
    horror: '1/1d4',
    treasure: 'Average',
    characteristics: { STR: 10, CON: 10, SIZ: 10, INT: 6, ACU: 8, DEX: 8, SOC: 6 },
    attacks: ['Longsword 50% 1d8+1+1'],
    skills: 'Combat 50%, Athletics 35%, Endurance 35%, Awareness 25%, Other Skills 15%',
    special: ['Rage: +2 to hit and damage, DR+1 for 30 min', 'DR 1 (Take a Hit Talent)', 'Hivemind', 'Darkvision 60 ft.', 'Low-Light Vision'],
    weaknesses: 'Cold iron',
  },
  {
    slug: 'orlock',
    name: 'Orlock Seer',
    pageTitle: 'Orlock',
    cv: 2,
    hp: 8,
    av: 2,
    avNote: 'cloth and chitin armor',
    speed: '30',
    dmgMod: '0',
    class: 'Monster',
    type: 'Fey (Athelesian)',
    horror: '1/1d6',
    treasure: 'Average',
    characteristics: { STR: 8, CON: 8, SIZ: 8, INT: 6, ACU: 12, DEX: 10, SOC: 6 },
    attacks: ['Longknife 45% 1d4+0', 'Wild Magic (ranged touch) 50% 1d4+2'],
    skills: 'Spellcraft 60%, Awareness 50%, Thievery 50%, Survival 50%, Other Skills 25%',
    special: ['Mana: 3', 'Wild Magic ranged attack (1d4+2 force, 60 ft.)', 'Spells: Mana 0: *Daze*; Mana 1: *Jump*, *Spider Climb*; Mana 3: *Web*', 'Hivemind', 'Darkvision 60 ft.', 'Low-Light Vision'],
    weaknesses: 'Cold iron',
  },
  {
    slug: 'orlock',
    name: 'Orlock Resinweaver',
    pageTitle: 'Orlock',
    cv: 3,
    hp: 27,
    av: 3,
    speed: '20',
    dmgMod: '0',
    class: 'Monster',
    type: 'Aberration',
    horror: '1/1d8',
    treasure: '1d2 hardened resin clusters (used in crafting or alchemy)',
    characteristics: { STR: 11, CON: 13, SIZ: 14, INT: 8, ACU: 10, DEX: 8, SOC: 4 },
    attacks: ['Resin Spit 65% 1d4 + Entangle (Heroic Action Effort vs 65 or –20% for 1d4 rounds)'],
    skills: 'Resincraft 70%, Hive Engineering 60%, Stealth 30%, Awareness 50%',
    special: ['Resin Flow: Create 5’x5’ wall (AV 2, HP 10), hardens in 1 minute.', 'Resin Burst (on death): 10\' radius, Dodge vs 50 or immobilized for 1 round.'],
    weaknesses: 'Cold',
  },
  {
    slug: 'orlock',
    name: 'Orlock Hive Concubine',
    pageTitle: 'Orlock',
    cv: 4,
    hp: 30,
    av: 4,
    speed: '30',
    dmgMod: '1d6',
    class: 'Monster',
    type: 'Aberration',
    horror: '2/1d8+1',
    treasure: 'Average (Queen-blessed trinkets, ceremonial chitin shard, rare resin gear)',
    characteristics: { STR: 16, CON: 15, SIZ: 15, INT: 10, ACU: 12, DEX: 13, SOC: 6 },
    attacks: ['(2) Chitin Blade 75% 1d8+2+1d6', 'Claw + Bite Combo (65% each) Claw 1d6+1d6, Bite 1d8+1'],
    skills: 'Combat 75%, Intimidate 65%, Awareness 60%, Dodge 60%, Hive Tactics 55%',
    special: ['Dominating Pheromones: Once per day, all lower CV Orlocks within 30’ gain +10% to combat for 3 rounds.', 'Shielding Rush: May use full move to engage an enemy and provide cover to a queen or drone (–20% to be hit behind them).', 'Regenerating Chitin: Regain 1 HP at start of each round for 3 rounds, once per combat.'],
    weaknesses: 'Sonic damage disrupts pheromone link (stuns 1 round if failed Effort roll).',
  },
  {
    slug: 'orlock',
    name: 'Orlock Queen',
    pageTitle: 'Orlock',
    cv: 6,
    hp: 220,
    av: 11,
    avNote: 'chitin plates',
    speed: '30',
    dmgMod: '+2d6',
    class: 'Monster',
    type: 'Fey (Navirite)',
    horror: '2/1d10+1',
    treasure: 'Rich (Embedded hive treasures, pheromone glands, spell component glands)',
    characteristics: { STR: 19, CON: 18, SIZ: 38, INT: 16, ACU: 15, DEX: 13, SOC: 10 },
    attacks: ['Claw (2) 85% 2d10+2+2d6 (Slashing) and Kick 75% 2d12+2+2d6 (Crushing, Knockback DC 18)'],
    skills: 'Combat 85%, Intimidate 65%, Endurance 65%, Awareness 55%, Command 75%, Spot 70%, Stealth 25%, Other Skills 45%',
    special: ['Darkvision 90’', 'Hivemind (with all orlocks in 1 mile)', 'Queen’s Pheromones', 'Pheromone Cloud', 'Hive Control'],
    weaknesses: 'Cold Iron (+1 damage), Fire (bypasses AV)',
  },
  {
    slug: 'orrilot',
    name: 'Orrilot',
    pageTitle: 'Orrilot',
    cv: 3,
    hp: 60,
    av: 4,
    avNote: 'thick hide',
    speed: '40’',
    dmgMod: '+3d6',
    class: 'Animal',
    type: 'Beast',
    characteristics: { STR: 28, CON: 20, SIZ: 40, INT: 5, ACU: 8, DEX: 10 },
    attacks: ['Slam 75% 1d8+3+3d6'],
    skills: 'Dodge 50%, Grapple 60%, Hide 45%, Listen 60%, Spot 60%, Stealth 45%',
    special: ['Scent'],
    habitat: 'Any plains',
    encounter: 'Solitary',
  },
  {
    slug: 'ozgoth-void-demon',
    name: 'Oz’goth Grunt',
    pageTitle: 'Oz’goth (Void Demon)',
    cv: 2,
    hp: 24,
    av: 2,
    avNote: 'Thick Hide',
    speed: '25’',
    dmgMod: '0',
    class: 'Monster',
    type: 'Navirite',
    horror: '2/2d3',
    treasure: 'Harvestables',
    characteristics: { STR: 10, CON: 12, SIZ: 12, INT: 6, ACU: 10, DEX: 14, SOC: 3 },
    attacks: ['(2) Claw 65% 1d6+2+db+1d4 Wither', 'Bite (only to grappled opponents) 85% 1d6+2+db+1d4 Wither'],
    skills: 'Dodge 50%, Grapple 50%, Hide 50%, Listen 50%, Spot 50%, Stealth 50%',
    special: ['Darkvision 60’', 'Immunity to Blindness', 'Poison', 'Prickly Skin'],
    weaknesses: 'Cold Iron (+1d4 damage), Light',
    habitat: 'Any dark area.',
    encounter: 'Single, pair, or horde (3 - 20)',
  },
  {
    slug: 'ozgoth-void-demon',
    name: 'Oz’goth Mystic',
    pageTitle: 'Oz’goth (Void Demon)',
    cv: 3,
    hp: 24,
    av: 2,
    avNote: 'Thick hide',
    speed: '25’',
    dmgMod: '0',
    class: 'Monster',
    type: 'Navirite',
    horror: '2/2d3',
    treasure: 'Harvestables',
    characteristics: { STR: 10, CON: 10, SIZ: 14, INT: 13, ACU: 15, DEX: 12, SOC: 8 },
    attacks: ['(2) Claw 65% 1d6+2+db+1d4 Wither', 'Bite (only to grappled opponents) 85% 1d6+2+db+1d4 Wither'],
    skills: 'Dodge 65%, Grapple 60%, Hide 60%, Listen 60%, Spellcraft 65%, Spot 60%, Stealth 60%',
    special: ['Darkvision 60’', 'Immunity to Blindness', 'Poison', 'Prickly Skin'],
    weaknesses: 'Cold Iron (+1d4 damage), Light',
    habitat: 'Any dark area.',
    encounter: 'Single, pair',
  },
  {
    slug: 'pyrg',
    name: 'Pyrg',
    pageTitle: 'Pyrg',
    cv: 0.5,
    hp: 6,
    av: 0,
    speed: '10\', Fly 40\'',
    dmgMod: '-1',
    class: 'Monster',
    type: 'Magical Beast',
    horror: 'None',
    treasure: 'None',
    characteristics: { STR: 4, CON: 4, SIZ: 2, INT: 2, ACU: 8, DEX: 18, SOC: 1 },
    attacks: ['Proboscis 55% (Attach)'],
    skills: 'Dodge 70%, Grapple 30%, Hide 50%, Listen 35%, Spot 40%, Stealth 60%',
    special: ['Attach', 'Blood Drain', 'Weapon Dexterity', 'Darkvision 60\''],
    weaknesses: 'Fragile',
    habitat: 'Swamps, marshes, riverbanks, damp forests',
    encounter: 'Single, Pair, or Swarm (3-12)',
  },
  {
    slug: 'ravenous-corpse',
    name: 'Ravenous Corpse (Daevar)',
    pageTitle: 'Ravenous Corpse (Daevar)',
    cv: 2,
    hp: 28,
    av: null,
    speed: '30',
    dmgMod: '+1d4',
    characteristics: { STR: 15, SIZ: 14, DEX: 16 },
    attacks: ['(2) Claw 60% 1d6+2+db', 'plus Bite 60% 1d6+2+db+paralyze', 'Tongue Lash 65% 1d6+2+db+10’ reach'],
    skills: 'Dodge 50%, Grapple 50%, Hide 50%, Listen 50%, Spot 50%, Stealth 50%',
    special: ['Artful Dodger', 'Blind Fight', 'Darkness', 'Disease', 'Paralysis'],
    weaknesses: 'Silver',
    habitat: 'Any dark place',
    encounter: 'Any',
  },
  {
    slug: 'reaver',
    name: 'Reaver',
    pageTitle: 'Reaver',
    cv: 4,
    hp: 52,
    av: 5,
    speed: '30\', Fly 50\'',
    dmgMod: '1d4',
    class: 'Monster',
    type: 'Fey (Athelesian)',
    horror: 'First Encounter (1/1d8), Fear Aura (2/1d6)',
    treasure: 'Ashiron sigil, fey bone trinkets, corrupted spell scroll',
    characteristics: { STR: 12, CON: 16, SIZ: 12, INT: 16, ACU: 12, DEX: 16, SOC: 8 },
    attacks: ['(2) Claws 80% 1d8+4+dm'],
    skills: 'Dodge 75%, Grapple 75%, Hide 65%, Listen 75%, Spot 75%, Stealth 65%, Spellcraft 80%, Athletics 75%, Intimidate 75%',
    special: ['Regeneration 5', 'Spell-Like Abilities', 'Spellcasting', 'Fly', 'Fear Aura', 'Darkvision 60\''],
    weaknesses: 'Cold Iron',
    habitat: 'Corrupted forests, Ashiron strongholds, the Navirim',
    encounter: 'Solitary, Hunting Pair, or Ashiron Warband (1-4 plus lesser fey)',
  },
  {
    slug: 'reaver',
    name: 'Reaver (Alternate Stat Block)',
    pageTitle: 'Reaver',
    cv: 4,
    hp: 52,
    av: 5,
    avNote: 'natural',
    speed: '30 ft. (Fly 50 ft.)',
    dmgMod: '1d4',
    class: 'Monster',
    type: 'Fey (Athelesian)',
    horror: 'First Encounter (1/1d8), Fear Aura (2/1d6)',
    treasure: 'Ashiron sigil, fey bone trinkets, corrupted scroll (spell)',
    characteristics: { STR: 12, CON: 16, SIZ: 12, INT: 16, ACU: 12, DEX: 16, SOC: 8 },
    attacks: ['2 Claws – 1d8+2+DM (Avg 11)'],
    skills: 'Combat and Main Skills 75%, Other Skills 45%',
    special: ['Regeneration 5 (negated by Cold Iron)', 'Spell-Like Abilities (*Mage Fire*, *Fear*)', 'Standard Spellcasting (MP: 30)', 'Fly', 'Darkvision (60 ft)', 'Low-Light Vision', 'Talents: Advantage, Cleave, Enlarge Spell, Stunning Strike'],
    weaknesses: 'Cold Iron bypasses regen, deals +2 dmg',
  },
  {
    slug: 'red-howler',
    name: 'Red Howler',
    pageTitle: 'Red Howler',
    cv: 3,
    hp: 45,
    av: 5,
    speed: '60',
    dmgMod: '+1d6',
    class: 'Monster',
    type: 'Navirite',
    horror: '1/1d6',
    treasure: 'None',
    characteristics: { STR: 17, CON: 14, SIZ: 16, INT: 6, ACU: 12, DEX: 16, SOC: 9 },
    attacks: ['Bite 65% 2d8+5 + Quills (1d4), Crit on 19–20'],
    skills: 'Acrobatics +40%, Athletics +50%, Awareness +50%, Endurance +20%, Survival +20%, Thievery +30%',
    special: ['Quills', 'Howl', 'Trip', 'Darkvision 60’'],
    weaknesses: 'Cold Iron',
  },
  {
    slug: 'redcap',
    name: 'Redcap',
    pageTitle: 'Redcap',
    cv: 2,
    hp: 18,
    av: 1,
    avNote: 'Thick Skin',
    speed: '20’',
    dmgMod: '-1',
    class: 'Monster',
    type: 'Navirite (Fey)',
    horror: '1/1d6',
    treasure: '50 gp',
    characteristics: { STR: 10, CON: 12, SIZ: 6, INT: 10, ACU: 12, DEX: 16, SOC: 12 },
    attacks: ['Melee: Short Sword 65% (1d6 + Poison): Ranged: Tiny Spear 65% (1d6 + Poison)'],
    skills: 'Dodge 60%, Grapple 50%, Hide 60%, Listen 50%, Spot 50%, Stealth 60%',
    special: ['Darkvision 60’', 'Poison'],
    weaknesses: 'Cold Iron does +1d4 damage',
    habitat: 'Forests, Underground',
    encounter: 'Single, Pair, Band (3–6), Clan (8–16)',
  },
  {
    slug: 'skeleton',
    name: 'Rotting Skeleton',
    pageTitle: 'Skeleton',
    cv: 0.5,
    hp: 12,
    av: 0,
    speed: '25',
    dmgMod: '0',
    class: 'Monster',
    type: 'Undead',
    horror: '1/1d4',
    treasure: '1 gp',
    characteristics: { STR: 6, SIZ: 12, DEX: 6 },
    attacks: ['Claw 45% 1d6+db'],
    skills: 'Dodge 45%, Grapple 25%, Hide 25%, Listen 25%, Spot 25%, Stealth 25%, Other Skills 15%',
    special: ['Piercing attacks are *Difficult*.'],
    weaknesses: 'Bludgeoning does an extra 1d4 damage. Silver (+1d4)',
    habitat: 'Any',
    encounter: 'Any',
  },
  {
    slug: 'skeleton',
    name: 'Skeleton',
    pageTitle: 'Skeleton',
    cv: 1,
    hp: 28,
    av: 0,
    speed: '25’',
    dmgMod: '0',
    class: 'Monster',
    type: 'Undead',
    horror: '1/1d4',
    treasure: '2 gp',
    characteristics: { STR: 8, SIZ: 14, DEX: 8 },
    attacks: ['Claw 50% 1d6+db+1 withering'],
    skills: 'Dodge 50%, Grapple 40%, Hide 40%, Listen 40%, Spot 40%, Stealth 35%',
    special: ['Piercing attacks are *Difficult*.'],
    weaknesses: 'Bludgeoning does an extra 1d4 damage. Silver (+1d4)',
    habitat: 'Any',
    encounter: 'Any',
  },
  {
    slug: 'skeleton',
    name: 'Shattered Skeleton',
    pageTitle: 'Skeleton',
    cv: 1,
    hp: 8,
    av: 0,
    speed: '25',
    dmgMod: '0',
    class: 'Monster',
    type: 'Undead',
    horror: '1/1d4',
    treasure: 'Standard',
    characteristics: { STR: 8, SIZ: 15, DEX: 8 },
    attacks: ['Claw 50% 1d6+db+1 withering'],
    skills: 'Dodge 50%, Grapple 40%, Hide 40%, Listen 40%, Spot 40%, Stealth 35%, Other Skills 15%',
    special: ['Piercing attacks are *Difficult*.', 'Bone shards 1d4+1 Bleed'],
    weaknesses: 'Bludgeoning does an extra 1d4 damage. Silver (+1d4)',
  },
  {
    slug: 'skeleton',
    name: 'Greater Skeleton',
    pageTitle: 'Skeleton',
    cv: 2,
    hp: 16,
    av: 2,
    speed: '25',
    dmgMod: '1d4',
    class: 'Monster',
    type: 'Undead',
    horror: '1/1d6',
    treasure: 'Standard',
    characteristics: { STR: 12, SIZ: 16, DEX: 12 },
    attacks: ['(2) Claws 65% 1d6+db+2 withering'],
    skills: 'Dodge 65%, Grapple 50%, Hide 50%, Listen 50%, Spot 50%, Stealth 50%, Other Skills 25%',
    special: ['Piercing attacks are *Difficult*.', 'Resistant.'],
    weaknesses: 'Bludgeoning does an extra 1d4 damage. Silver (+1d4)',
  },
  {
    slug: 'skeleton',
    name: 'Skeletal Boss',
    pageTitle: 'Skeleton',
    cv: 4,
    hp: 34,
    av: 4,
    speed: '25’',
    dmgMod: '1d6',
    class: 'Monster',
    type: 'Undead',
    horror: '2/1d8+1',
    treasure: '150 gp',
    characteristics: { STR: 18, SIZ: 17, DEX: 15 },
    attacks: ['(2) Claws 80% 1d6+dm+4 withering'],
    skills: 'Dodge 75%, Grapple 65%, Hide 65%, Listen 65%, Spot 65%, Stealth 65%',
    special: ['Piercing attacks are *Difficult*.', 'Resistant'],
    weaknesses: 'Bludgeoning does an extra 1d4 damage. Silver (+1d4)',
    habitat: 'Any',
    encounter: 'Solitary',
  },
  {
    slug: 'spiders',
    name: 'Spider, Dire (Small)',
    pageTitle: 'Spiders',
    cv: 1,
    hp: 9,
    av: 0,
    speed: '25’',
    dmgMod: '-1',
    class: 'Animal',
    type: 'Vermin',
    treasure: '2 gp (harvestables)',
    characteristics: { STR: 8, CON: 10, SIZ: 8, INT: 2, ACU: 7, DEX: 12 },
    attacks: ['Bite 50% 1d6+1+dm+Poison, Web 55% Entangled'],
    skills: 'Climb 90%, Dodge 50%, Grapple 40%, Hide 40%, Listen 40%, Spot 40%, Stealth 35%',
    special: ['Darkvision', 'Poison', 'Web'],
    weaknesses: 'Low HP (1/2)',
    habitat: 'Any',
    encounter: 'Solitary or cluster (2-5)',
  },
  {
    slug: 'spiders',
    name: 'Spider, Dire (Medium)',
    pageTitle: 'Spiders',
    cv: 2,
    hp: 26,
    av: 0,
    speed: '25’',
    dmgMod: '0',
    class: 'Animal',
    type: 'Vermin',
    treasure: '25 gp',
    characteristics: { STR: 10, CON: 12, SIZ: 14, INT: 2, ACU: 8, DEX: 13 },
    attacks: ['Bite 65% 1d6+2+dm+poison, Web 65% Entangled'],
    skills: 'Climb 90%, Dodge 50%, Grapple 50%, Hide 50%, Listen 50%, Spot 50%, Stealth 50%',
    special: ['Darkvision', 'Poison', 'Web'],
    habitat: 'Any',
    encounter: 'Solitary or cluster (2-5)',
  },
  {
    slug: 'spiders',
    name: 'Spider, Dire (Large)',
    pageTitle: 'Spiders',
    cv: 3,
    hp: 26,
    av: 2,
    avNote: 'thick hide',
    speed: '30’',
    dmgMod: '1d4',
    class: 'Animal',
    type: 'Vermin',
    treasure: '40 gp',
    characteristics: { STR: 14, CON: 16, SIZ: 20, INT: 3, ACU: 10, DEX: 15 },
    attacks: ['(2) 75% 1d6+3+dm+poison, Web 75% Entangled'],
    skills: 'Climb 90%, Dodge 65%, Grapple 60%, Hide 60%, Listen 60%, Spot 60%, Stealth 60%',
    special: ['Darkvision', 'Poison', 'Web'],
    habitat: 'Any',
    encounter: 'Solitary or cluster (2-5)',
  },
  {
    slug: 'spiders',
    name: 'Dire Spider (Huge)',
    pageTitle: 'Spiders',
    cv: 4,
    hp: 52,
    av: 4,
    speed: '25’',
    dmgMod: '2d6',
    class: 'Animal',
    type: 'Vermin',
    treasure: '150 gp',
    characteristics: { STR: 18, CON: 20, SIZ: 32, INT: 3, ACU: 13, DEX: 15 },
    attacks: ['Bite (2) 80% 1d6+4+dm+poison, Web 55% Entangled'],
    skills: 'Climb 90%, Dodge 75%, Grapple 65%, Hide 65%, Listen 65%, Spot 65%, Stealth 65%',
    special: ['Darkvision', 'Poison', 'Web'],
    habitat: 'Any',
    encounter: 'Solitary or cluster (2-5)',
  },
  {
    slug: 'spiders',
    name: 'Death\'s Eye Spider',
    pageTitle: 'Spiders',
    cv: 3,
    hp: 16,
    av: 1,
    speed: '30\', Climb 30\'',
    dmgMod: '0',
    class: 'Monster',
    type: 'Vermin',
    horror: 'None',
    treasure: 'None',
    characteristics: { STR: 8, CON: 8, SIZ: 14, INT: 1, ACU: 8, DEX: 13 },
    attacks: ['Bite 75% 1d6+3+dm+poison'],
    skills: 'Dodge 80%, Grapple 40%, Hide 75%, Listen 40%, Spot 45%, Stealth 75%, Climb 80%',
    special: ['Poison', 'Darkvision 60\'', 'Spider Climb'],
    habitat: 'Forests, caves, underground',
    encounter: 'Solitary, Pair, or Colony (3-8)',
  },
  {
    slug: 'tentacle-crawler',
    name: 'Tentacle Crawler',
    pageTitle: 'Tentacle Crawler',
    cv: 4,
    hp: 35,
    av: 4,
    avNote: 'thick carapace',
    speed: '30’',
    dmgMod: '1d6',
    class: 'Monster',
    type: 'Vermin',
    horror: '1/1d8',
    treasure: 'Harvestables',
    characteristics: { STR: 16, CON: 15, SIZ: 20, INT: 2, ACU: 8, DEX: 10 },
    attacks: ['(5) Tentacles 65% 1d6+1+dm (Attempt Grab on hit) and Tail Sting 65% 1d6+1+dm+Poison'],
    skills: 'Dodge 75%, Grapple 65%, Hide 65%, Listen 65%, Spot 65%, Stealth 65%',
    special: ['Darkvision 60’', 'Grab', 'Reach'],
    weaknesses: 'None',
    habitat: 'Marshes, sewers, underground',
    encounter: 'Solitary',
  },
  {
    slug: 'tevlan',
    name: 'Tevlan',
    pageTitle: 'Tevlan',
    cv: 2,
    hp: 22,
    av: 2,
    speed: '25',
    dmgMod: '1d4',
    class: 'Monster',
    type: 'Navirite',
    horror: '1',
    treasure: 'Standard',
    characteristics: { STR: 17, CON: 14, SIZ: 8, INT: 12, ACU: 12, DEX: 14, SOC: 7 },
    attacks: ['(2) Claw 60% 1d6+1+1d4'],
    skills: 'Dodge 60%, Hide/Stealth/Spot 50%, Other Skills 25%',
    special: ['Shadowstep'],
    weaknesses: 'Cold Iron',
  },
  {
    slug: 'troll',
    name: 'Troll',
    pageTitle: 'Troll',
    cv: 3,
    hp: 25,
    av: 4,
    speed: '30’',
    dmgMod: '1d6',
    class: 'Monster',
    type: 'Giant',
    horror: '3/2d6',
    characteristics: { STR: 12, CON: 12, SIZ: 23, INT: 12, ACU: 12, DEX: 12 },
    attacks: ['(2) Claw 60% 1d6+1+1d6'],
    skills: 'Main Skills 60%, Other Skills 35%',
    special: ['Rend', 'Darksight 60’'],
    weaknesses: 'Fire, Acid, Sunlight',
  },
  {
    slug: 'vorzhem',
    name: 'Vorzhem',
    pageTitle: 'Vorzhem',
    cv: 5,
    hp: 58,
    av: 6,
    avNote: 'Thick Hide',
    speed: '35’',
    dmgMod: '+2d6',
    class: 'Monster',
    type: 'Navirite',
    horror: '2/1d10+1',
    treasure: 'Harvestables and Equipment',
    characteristics: { STR: 26, CON: 28, SIZ: 30, INT: 14, ACU: 12, DEX: 10, SOC: 15 },
    attacks: ['Bite 85% 1d6+5+dm and (2) Claws 85% 1d6+5+dm+Grab'],
    skills: 'Dodge 80%, Grapple 85%, Hide 75%, Listen 75%, Spot 75%, Stealth 75%',
    special: ['Deathly Howl', 'Grab', 'Nausea', 'Great Cleave', 'Power Attack', 'Darkvision 60 ft.', 'Amphibious', 'Space 10 ft.', 'Reach 10 ft.'],
    weaknesses: 'Cold Iron',
    habitat: 'Any',
    encounter: 'Solitary',
  },
  {
    slug: 'wyvere',
    name: 'Wyvere',
    pageTitle: 'Wyvere',
    cv: 8,
    hp: 92,
    av: 8,
    speed: '60’ (Fly 200’)',
    dmgMod: '+2d6',
    class: 'Monster',
    type: 'Draconian',
    horror: 'None',
    treasure: 'Harvestable',
    characteristics: { STR: 21, CON: 18, SIZ: 28, INT: 12, ACU: 13, DEX: 14, SOC: 12 },
    attacks: ['Bite 75% 2d6+2d6+2d6 acid over 1d4 rounds and Tail Slap 75% 1d8+2d6+Venom', 'ranged Acid Spit 80% (range 30 ft) 6d6 acid'],
    skills: 'Dodge 55%, Climb 50%, Spot 65%, Listen 65%, Hide 40%, Stealth 50%',
    special: ['Acid Spit', 'Acid Bite', 'Tail Venom', 'Immune to Poison and Acid'],
    habitat: 'Desert, Warm Mountains',
    encounter: 'Solitary or Pair',
  },
  {
    slug: 'zombie',
    name: 'Shambling Zombie',
    pageTitle: 'Zombie',
    cv: 1,
    hp: 7,
    av: 0,
    speed: '20’',
    dmgMod: '0',
    class: 'Monster',
    type: 'Undead',
    horror: '1/1d4',
    characteristics: { STR: 10, SIZ: 13, DEX: 10 },
    attacks: ['Bite 50% 1d6+1+dm'],
    skills: 'Grapple 40%, Listen 40%, Spot 40%',
    special: ['Zombie Bite'],
    weaknesses: 'Headshots kill instantly, Slow, Low HP',
    habitat: 'Any',
    encounter: 'Solitary, Group (2-8), Herd (9+)',
  },
  {
    slug: 'zombie',
    name: 'Zombie',
    pageTitle: 'Zombie',
    cv: 2,
    hp: 15,
    av: 1,
    speed: '25',
    dmgMod: '+1d4',
    horror: '1/1d4',
    treasure: 'Standard',
    characteristics: { STR: 13, SIZ: 12, DEX: 10 },
    attacks: ['(2) Slam 50% 1d6+1+dm (Avg 5)'],
    skills: 'Combat 55%, Main Skills 50%, Other Skills 25%',
    special: ['Zombie Bite'],
    weaknesses: 'Headshots bypass AV',
  },
];
