import type { CreatureStatBlock } from './creatures';

export const CREATURES_A: CreatureStatBlock[] = [
  {
    slug: 'angroll',
    name: 'Angroll',
    pageTitle: 'Angroll',
    cv: 2,
    hp: 26,
    av: 2,
    avNote: 'Thick Hide',
    speed: '25’',
    dmgMod: '1d4',
    class: 'Being',
    type: 'Terianeth',
    treasure: '25 gp',
    characteristics: { STR: 14, CON: 10, SIZ: 16, INT: 10, ACU: 10, DEX: 12, SOC: 8 },
    attacks: ['Weapon (Spear or Sword) 65% 1d8+2+1d4'],
    skills: 'Dodge 50%, Grapple 50%, Hide 50%, Listen 50%, Spot 50%, Stealth 50%',
    special: ['Hold Breath', 'Immune Disease', 'Create Sandstorm', 'Shrill Scream', 'Curled Defense'],
    weaknesses: 'None',
    habitat: 'Warm Plains',
    encounter: 'Single, Pair, Troop (3-12), or Tribe (15-50)',
  },
  {
    slug: 'ank',
    name: 'Ank',
    pageTitle: 'Ank',
    cv: 2,
    hp: 22,
    av: 2,
    avNote: 'Thick Hide',
    speed: '25’',
    dmgMod: '1d4',
    class: 'Animal',
    type: 'Terian',
    treasure: 'Harvestables',
    characteristics: { STR: 14, CON: 14, SIZ: 18, INT: 3, ACU: 4, DEX: 8 },
    attacks: ['Bite 60% 1d6+2+dm'],
    skills: 'Dodge 50%, Grapple 50%, Hide 35%, Listen 50%, Spot 50%, Stealth 40%',
    special: ['Honey Globule Growth', 'Scent'],
    habitat: 'Plains',
    encounter: 'Herd 2-30',
  },
  {
    slug: 'ankheg',
    name: 'Ankheg',
    pageTitle: 'Ankheg',
    cv: 3,
    hp: 42,
    av: 4,
    avNote: 'Chitin',
    speed: '35’',
    dmgMod: '2d6',
    class: 'Monster',
    type: 'Aberration',
    horror: '1/1d8',
    treasure: 'Harvestables',
    characteristics: { STR: 16, CON: 16, SIZ: 26, INT: 3, ACU: 3, DEX: 8 },
    attacks: ['Bite 75% 1d6+3+dm plus grab', 'Acid Spit 65% 1d10+1 or 1 AV for 10 rounds'],
    skills: 'Dodge 55%, Grapple 60%, Hide 50%, Listen 60%, Spot 60%, Stealth 50%',
    special: ['Burrow', 'Grab', 'Spit Acid'],
    habitat: 'Loose soil, deserts, underground',
    encounter: 'Single, Pair',
  },
  {
    slug: 'apparition',
    name: 'Apparition',
    pageTitle: 'Apparition',
    cv: 4,
    hp: 30,
    av: 3,
    speed: '60’ (fly)',
    dmgMod: '0',
    class: 'Monster',
    type: 'Undead',
    horror: '2/2d4',
    characteristics: { SIZ: 15, INT: 14, ACU: 14, DEX: 17, SOC: 15 },
    attacks: ['(2) Touch 75% 1d6 (withering) and Spirit Drain', '*In-Between*: (2) Claws 75% 1d8+1d4 Spirit Point Drain'],
    skills: 'Dodge 75%, Grapple 65%, Hide 65%, Listen 65%, Spot 65%, Stealth 65%',
    special: ['Spirit Drain', 'Sense the Living'],
    weaknesses: 'Silver (allows hits)',
    habitat: 'Any dark.',
    encounter: 'Single or Pair',
  },
  {
    slug: 'bagoth',
    name: 'Ba\'goth',
    pageTitle: 'Ba\'goth',
    cv: 4,
    hp: 35,
    av: 6,
    avNote: 'Thick Skin',
    speed: '25',
    dmgMod: '1d6',
    class: 'Monster',
    type: 'Navirite',
    horror: '2/1d8+1',
    treasure: '120 gp (Harvestables)',
    characteristics: { STR: 20, CON: 20, SIZ: 15, INT: 5, ACU: 6, DEX: 12, SOC: 4 },
    attacks: ['(2) claws 80% 1d6+4+dm'],
    skills: 'Dodge 75%, Grapple 65%, Hide 65%, Listen 65%, Spot 65%, Stealth 65%',
    special: ['Darkvision 60’', 'dark', 'immune (acid, cold, and fire)', 'protective slime', 'see invisible', 'sneak attack'],
    weaknesses: 'Cold Iron',
    habitat: 'Any dark area.',
    encounter: 'Single, Pair, or Troop (4-20)',
  },
  {
    slug: 'basilisk',
    name: 'Basilisk',
    pageTitle: 'Basilisk',
    cv: 5,
    hp: 37,
    av: 5,
    speed: '30’',
    dmgMod: '1d6',
    class: 'Monster',
    type: 'Magical Beast',
    horror: '2/2d4 (If Turning to Stone)',
    treasure: 'Harvestables',
    characteristics: { STR: 18, CON: 15, SIZ: 22, INT: 4, ACU: 6, DEX: 15 },
    attacks: ['Bite* 80% 1d6+5+dm and (2) Claws 70% 1d6+5+dm'],
    skills: 'Dodge 70%, Grapple 75%, Hide 65%, Listen 75%, Spot 75%, Stealth 65%',
    special: ['Stone Breath'],
    weaknesses: 'Mirrors',
    habitat: 'Forests, Mountains, or Caves',
    encounter: 'single or a Pair',
  },
  {
    slug: 'beelzebuf',
    name: 'Beelzebuf',
    pageTitle: 'Beelzebuf',
    cv: 3,
    hp: 44,
    av: 4,
    speed: '35’',
    dmgMod: '2d6',
    class: 'Animal',
    type: 'Amphibian',
    treasure: 'Harvestables',
    characteristics: { STR: 12, CON: 14, SIZ: 30, INT: 3, ACU: 6, DEX: 14 },
    attacks: ['Bite 75% 1d6+3+2d6', 'Tongue 75% grab', 'Venom Spit 75% (Blindness)'],
    skills: 'Dodge 65%, Grapple 60%, Hide 60%, Listen 60%, Spot 60%, Stealth 60%',
    special: ['Blinding Venom', 'Tongue', 'Grab', 'Swallow Whole'],
    habitat: 'Swamp, Underground',
    encounter: 'Single or Pair',
  },
  {
    slug: 'boggart',
    name: 'Boggart',
    pageTitle: 'Boggart',
    cv: 0.5,
    hp: 9,
    av: 0,
    speed: '20',
    dmgMod: '-2',
    class: 'Being',
    type: 'Navirite (Fey)',
    treasure: '2 gp',
    characteristics: { STR: 8, CON: 6, SIZ: 3, INT: 6, ACU: 6, DEX: 12, SOC: 4 },
    attacks: ['Short Sword 45% 1d6-1'],
    skills: 'Dodge 65%, Grapple 40%, Hide 55%, Listen 40%, Spot 40%, Stealth 450%',
    special: ['Dark Vision 60’'],
    weaknesses: 'Light Sensitivity',
    habitat: 'Any dark area.',
    encounter: 'Single, Pair, or Gang (3-20)',
  },
  {
    slug: 'centipede-giant',
    name: 'Giant Centipede',
    pageTitle: 'Giant Centipede',
    cv: 1,
    hp: 21,
    av: 0,
    speed: '25’',
    dmgMod: '0',
    class: 'Animal',
    type: 'Vermin',
    treasure: 'Harvestables',
    characteristics: { STR: 8, CON: 9, SIZ: 12, INT: 1, ACU: 4, DEX: 13 },
    attacks: ['Bite 50% 1d6+1+dm'],
    skills: 'Dodge 50%, Grapple 40%, Hide 40%, Listen 40%, Spot 40%, Stealth 35%',
    special: ['Centipede Poison'],
    habitat: 'Underground, Dense Forests',
    encounter: 'Solitary',
  },
  {
    slug: 'cockatrice',
    name: 'Cockatrice',
    pageTitle: 'Cockatrice',
    cv: 2,
    hp: 16,
    av: 0,
    speed: '20’/ fly 15’',
    dmgMod: '-1',
    class: 'Monster',
    type: 'Magical Beast',
    horror: '1/1d6',
    treasure: 'Harvestables',
    characteristics: { STR: 8, CON: 10, SIZ: 6, INT: 3, ACU: 10, DEX: 16, SOC: 3 },
    attacks: ['Bite 65% 1d6+2+dm+ Petrification'],
    skills: 'Dodge 60%, Grapple 50%, Hide 60%, Listen 50%, Spot 50%, Stealth 60%',
    special: ['Petrification', 'Fear of chickens', 'Fly (poor)'],
    weaknesses: 'Chickens',
    habitat: 'Plains, Forests, Temperate',
    encounter: 'Single, Pair, or Roost (3-12)',
  },
  {
    slug: 'devouring-ooze',
    name: 'Devouring Ooze',
    pageTitle: 'Devouring Ooze',
    cv: 3,
    hp: 45,
    av: 0,
    speed: '25’ / 15’ Climb',
    dmgMod: '+1d6',
    class: 'Monster',
    type: 'Magical Beast',
    horror: '1/1d6',
    treasure: 'None',
    characteristics: { STR: 18, CON: 26, SIZ: 19, ACU: 5, DEX: 8 },
    attacks: ['Slam 65% 1d8+3+dm+ Engulf'],
    skills: 'Dodge 65%, Grapple 60%, Hide 60%, Listen 60%, Spot 60%, Stealth 60%',
    special: ['Camouflage', 'Engulf'],
    habitat: 'Sewers, Marshes, Wet Caves',
    encounter: 'Solitary or Pair',
  },
  {
    slug: 'dire-rat',
    name: 'Dire Rat',
    pageTitle: 'Dire Rat',
    cv: 1,
    hp: 5,
    av: 0,
    speed: '20’',
    dmgMod: '-1',
    class: 'Animal',
    type: 'Magical Beast',
    treasure: '2 gp',
    characteristics: { STR: 8, CON: 5, SIZ: 4, INT: 3, ACU: 6, DEX: 12 },
    attacks: ['bite 50% 1d6+1+dm'],
    skills: 'Dodge 65%, Grapple 40%, Hide 55%, Listen 40%, Spot 40%, Stealth 50%',
    special: ['Dark Vision 40’', 'Scent'],
    weaknesses: 'Low HP (1/2)',
    habitat: 'Any',
    encounter: 'Solitary, Pair, or Pack (7-12)',
  },
  {
    slug: 'drake',
    name: 'Drake',
    pageTitle: 'Drake',
    cv: 5,
    hp: 36,
    av: 6,
    speed: '40',
    dmgMod: '1d6',
    class: 'Monster',
    type: 'Draconian',
    treasure: 'Harvestables',
    characteristics: { STR: 18, CON: 16, SIZ: 20, INT: 6, ACU: 11, DEX: 12, SOC: 11 },
    attacks: ['Bite 65% 1d6+5+dm and Claw (x2) 70% 1d6+5+dm'],
    skills: 'Dodge 70%, Grapple 75%, Hide 65%, Listen 75%, Spot 75%, Stealth 65%',
    special: ['Breath Weapon', 'Scent', 'Immune to Fire', 'Darkvision 60’'],
    weaknesses: 'Tritium (negates AV)',
    habitat: 'Mountains',
    encounter: 'Solitary, Pair, or Family (1–2 adults and 2–5 young)',
  },
  {
    slug: 'drekava',
    name: 'Drekava',
    pageTitle: 'Drekava',
    cv: 2,
    hp: 14,
    av: 2,
    avNote: 'tough hide',
    speed: '30’',
    dmgMod: '-2',
    class: 'Monster',
    type: 'Navirite',
    horror: '1/1d6',
    treasure: 'Harvestables',
    characteristics: { STR: 11, CON: 11, SIZ: 3, INT: 13, ACU: 13, DEX: 12, SOC: 7 },
    attacks: ['Bite 60% 1d6+dm and (2) Claws 60% 55% 1d6+dm'],
    skills: 'Dodge 65%, Grapple 50%, Hide 65%, Listen 50%, Spot 50%, Stealth 65%',
    special: ['Revolting Smile', 'Maniacal Laugh', 'Multi-attack', 'Dark Vision 60’'],
    weaknesses: 'Cold Iron',
    habitat: 'Any',
    encounter: 'Solitary, or group 2-6',
  },
  {
    slug: 'dretch',
    name: 'Dretch',
    pageTitle: 'Dretch',
    cv: 2,
    hp: 22,
    av: 2,
    avNote: 'thick hide',
    speed: '25’',
    dmgMod: '0',
    class: 'Monster',
    type: 'Navirite',
    horror: '1/1d6',
    treasure: 'Harvestables',
    characteristics: { STR: 11, CON: 14, SIZ: 8, INT: 4, ACU: 10, DEX: 10, SOC: 3 },
    attacks: ['(2) Claws 65% 1d6+db+2'],
    skills: 'Dodge 50%, Grapple 50%, Hide 50%, Listen 50%, Spot 50%, Stealth 50%',
    special: ['Belching Acid', 'Darkvision 60’', 'Immune: Acid', 'Electricity', 'and Poison'],
    weaknesses: 'Cold Iron',
    habitat: 'Any',
    encounter: 'Single, Pair, or Herd (3–12)',
  },
  {
    slug: 'drogga',
    name: 'Drogga',
    pageTitle: 'Drogga',
    cv: 0.5,
    hp: 10,
    av: 0,
    speed: '15’',
    dmgMod: '-2',
    class: 'Being',
    type: 'Goblinoid',
    treasure: '1 gp',
    characteristics: { STR: 6, CON: 8, SIZ: 2, INT: 7, ACU: 9, DEX: 11, SOC: 5 },
    attacks: ['Dagger 45% 1d4+dm,', 'sling 40% 1d4+dm'],
    skills: 'Dodge 60%, Grapple 25%, Hide 60%, Listen 25%, Spot 25%, Stealth 60%',
    special: ['Darkvision 80’', 'Light Sensitivity', 'Trap Maker'],
    habitat: 'Underground, Forest',
    encounter: 'Single Scout, Hunting Party (2–6), Tribe (6–18)',
  },
  {
    slug: 'drueglem',
    name: 'Drueglem',
    pageTitle: 'Drueglem',
    cv: 2,
    hp: 20,
    av: 4,
    speed: '25’',
    dmgMod: '0',
    class: 'Monster',
    type: 'Construct',
    characteristics: { STR: 12, SIZ: 10, INT: 2, ACU: 8, DEX: 12 },
    attacks: ['Slam 65% 1d8+2+dm'],
    skills: 'Dodge 50%, Grapple 50%, Hide 50%, Listen 50%, Spot 50%, Stealth 50%',
    special: ['Immune to Fire', 'Poison', 'Disease', 'and Bleed', 'Armored', 'Construct Traits'],
    habitat: 'Any',
    encounter: 'Single, Pair, or Troop (3-9)',
  },
  {
    slug: 'drueglem',
    name: 'Battle Block: Drueglem (CV 2)',
    pageTitle: 'Drueglem',
    cv: null,
    hp: 20,
    av: 4,
    speed: '20',
    horror: 'None',
    treasure: 'None',
    characteristics: { STR: 12, SIZ: 10, INT: 1, ACU: 8, DEX: 12 },
    attacks: ['Pummel 75% 1d8+2+1d4'],
    skills: 'Dodge 50%, Grapple 50%, Hide 50%, Listen 50%, Spot 50%, Stealth 50%, Other Skills 25%',
    special: ['Immune to Fire'],
    weaknesses: 'None',
  },
  {
    slug: 'dryad',
    name: 'Dryad',
    pageTitle: 'Dryad',
    cv: 3,
    hp: 23,
    av: 2,
    avNote: 'natural',
    speed: '25\'',
    dmgMod: '0',
    class: 'Being',
    type: 'Fey',
    treasure: '100 gp',
    characteristics: { STR: 10, CON: 10, SIZ: 13, INT: 16, ACU: 16, DEX: 18, SOC: 18 },
    attacks: ['(2) Claw 75% 1d6+dm'],
    skills: 'Dodge 65%, Grapple 60%, Hide 60%, Listen 60%, Persuasion 75%, Spellcraft 75%, Spot 60%, Stealth 60%',
    special: ['Speak With Plants', 'Tree Stride', 'Tree Shape', 'Tree-Dependent', 'Magic Abilities'],
    weaknesses: 'Cold Iron',
    habitat: 'Any Forest',
    encounter: 'single',
  },
  {
    slug: 'dworven-drone',
    name: 'Dworven Drone',
    pageTitle: 'Dworven Drone',
    cv: 3,
    hp: 32,
    av: 6,
    avNote: 'natural, includes DR2',
    speed: '30 ft.',
    dmgMod: '+1d4',
    class: 'Monster',
    type: 'Construct',
    horror: 'None',
    treasure: 'None',
    characteristics: { STR: 18, SIZ: 20, INT: 3, ACU: 8, DEX: 11, SOC: 2 },
    attacks: ['Leg Piercing 65% – 1d6+1d4+1 (Avg 7)', 'Claw 65% – 1d6+1d4 (Grapple on hit)', 'Flame-throw – 15 ft. cone, 1d6+1 fire (Dodge vs 60)'],
    skills: 'Acrobatics 30%, Athletics 50%, Awareness 35%, Thievery 25%',
    special: ['DR2', 'Flame-throw', 'Grease Spray', 'Self-Destruct', 'Command Override'],
    weaknesses: 'Commands',
    habitat: 'Any',
    encounter: 'Solitary',
  },
  {
    slug: 'elemental-wraith',
    name: 'Elemental Wraith',
    pageTitle: 'Elemental Wraith',
    cv: 3,
    hp: 24,
    av: 4,
    speed: '10',
    dmgMod: '0',
    class: 'Monster',
    type: 'Elemental',
    horror: 'None',
    treasure: 'Incidental',
    characteristics: { STR: 12, CON: 12, SIZ: 12, INT: 12, ACU: 12, DEX: 12 },
    attacks: ['(2) Slam 75% 1d8+3+db+element'],
    skills: 'Dodge 65%, Grapple 60%, Hide 60%, Listen 60%, Spot 60%, Stealth 60%, Other Skills 35%',
    special: ['Varies'],
    weaknesses: 'Opposite Elements, Powerless',
  },
  {
    slug: 'elf',
    name: 'Elven Commoner',
    pageTitle: 'Elves',
    cv: 2,
    hp: 28,
    av: 0,
    speed: '25',
    dmgMod: '1d4',
    class: 'Being',
    type: 'Elf',
    treasure: 'Standard',
    characteristics: { STR: 10, CON: 10, SIZ: 18, INT: 10, ACU: 10, DEX: 10, SOC: 10 },
    attacks: ['65% 1d6+2+1d4'],
    skills: 'Dodge 50%, Main Skills 50%, Other Skills 25%',
    special: ['Dark Vision'],
    weaknesses: 'Allergic to Steel and Iron',
  },
  {
    slug: 'elf',
    name: 'Elven Archer',
    pageTitle: 'Elves',
    cv: 3,
    hp: 32,
    av: 4,
    avNote: 'Studded Leather and Buckler',
    speed: '25',
    dmgMod: '1d4',
    class: 'Being',
    type: 'Elf',
    treasure: 'Standard',
    characteristics: { STR: 13, CON: 14, SIZ: 18, INT: 12, ACU: 14, DEX: 14, SOC: 13 },
    attacks: ['Longbow 80% 1d8+1+1d4+2d6 (Wild Magic), Quick Shot 70% 1d8+1d4+2d6 (Wild Magic), Longsword 65% 1d8+1d4+1d6 (Wild Magic)'],
    skills: 'Dodge 65%, Grapple 60%, Hide 60%, Listen 60%, Spot 60%, Stealth 65%, Other Skills 25%',
    special: ['Dark Vision', 'Spell Memory', 'Wild Magic', 'Quick Shot'],
    weaknesses: 'Allergic to Steel and Iron',
  },
  {
    slug: 'elf',
    name: 'Elven Soldier',
    pageTitle: 'Elves',
    cv: 3,
    hp: 35,
    av: 4,
    avNote: 'Studded Leather and Buckler',
    speed: '25',
    dmgMod: '1d6',
    class: 'Being',
    type: 'Elf',
    treasure: 'Standard',
    characteristics: { STR: 16, CON: 17, SIZ: 18, INT: 11, ACU: 11, DEX: 14, SOC: 10 },
    attacks: ['Longsword 80% 1d8+1+1d6'],
    skills: 'Dodge 65%, Grapple 60%, Hide 60%, Listen 60%, Spot 60%, Stealth 65%, Other Skills 25%',
    special: ['Dark Vision', 'Gain Health', 'Powerful Attack'],
    weaknesses: 'Allergic to Steel and Iron',
  },
  {
    slug: 'elf',
    name: 'Elven Spellweaver',
    pageTitle: 'Elves',
    cv: 3,
    hp: 29,
    av: 1,
    avNote: '5 with Warding Armor',
    speed: '25',
    dmgMod: '1d4',
    class: 'Being',
    type: 'Elf',
    treasure: 'Standard',
    characteristics: { STR: 12, CON: 11, SIZ: 18, INT: 16, ACU: 14, DEX: 11, SOC: 12 },
    attacks: ['Energy Burst'],
    skills: 'Dodge 65%, Grapple 60%, Hide 60%, Listen 60%, Spellcraft 85%, Spot 60%, Stealth 65%, Other Skills 25%',
    special: ['Dark Vision', 'Spellbook', 'Energy Burst', 'Elemental Focus', 'Energy Blast'],
    weaknesses: 'Allergic to Steel and Iron',
  },
  {
    slug: 'elf',
    name: 'Elven Swordmaster',
    pageTitle: 'Elves',
    cv: 5,
    hp: 49,
    av: 6,
    speed: '25',
    dmgMod: '1d6',
    class: 'Being',
    type: 'Elf',
    treasure: 'Standard',
    characteristics: { STR: 16, CON: 15, SIZ: 19, INT: 12, ACU: 14, DEX: 15, SOC: 9 },
    attacks: ['Broadsword 90% 1d8+1+1d6', '(2) Broadsword Dual 80% 1d8+1+1d6', 'Shortbow 65% 1d8+1d6'],
    skills: 'Dodge 75%, Grapple 65%, Hide 60%, Listen 60%, Spot 60%, Stealth 60%, Other Skills 25%',
    special: ['Dark Vision', 'Dual Wield', 'Gain Health', 'Heroic Surge', 'Riposte', 'Weapon Specialty'],
    weaknesses: 'Allergic to Steel and Iron',
  },
  {
    slug: 'ettercap',
    name: 'Ettercap',
    pageTitle: 'Ettercap',
    cv: 3,
    hp: 31,
    av: 0,
    speed: '25\'',
    dmgMod: '+1d4',
    class: 'Monster',
    type: 'Navirite',
    horror: '1/1d8',
    treasure: '40 gp (harvestables)',
    characteristics: { STR: 14, CON: 13, SIZ: 18, INT: 9, ACU: 12, DEX: 16, SOC: 9 },
    attacks: ['Bite 65% 1d6+dm+poison and (2) Claws 55% 1d6+dm'],
    skills: 'Climb 80%, Dodge 65%, Grapple 60%, Hide 60%, Listen 60%, Spot 60%, Stealth 60%',
    special: ['Poison', 'Web', 'Dark Vision', 'Multiattack'],
    weaknesses: 'Cold Iron',
    habitat: 'Forests, Underground',
    encounter: 'Single, Pair, or Cluster (3-5)',
  },
  {
    slug: 'ettin',
    name: 'Ettin',
    pageTitle: 'Ettin',
    cv: 4,
    hp: 36,
    av: 7,
    speed: '40 ft.',
    dmgMod: '+2d6',
    class: 'Being',
    type: 'Giant',
    horror: '2/1d8+1',
    treasure: 'Standard',
    characteristics: { STR: 21, CON: 14, SIZ: 22, INT: 8, ACU: 12, DEX: 9, SOC: 10 },
    attacks: ['2× Large Morningstar 75% 2d6+2d6', '2× Javelin 65% 1d8+2d6'],
    skills: 'Athletics 75%, Dodge 50%, Grapple 65%, Hide 25%, Listen 55%, Spot 60%, Stealth 15%',
    special: ['Low-Light Vision', 'Superior Two-Weapon Fighting', 'Power Attack'],
    weaknesses: 'None',
    habitat: 'Cold hills',
    encounter: 'Solitary, gang (2–4), troupe (1–2)',
  },
  {
    slug: 'fey-fox',
    name: 'Fey Fox',
    pageTitle: 'Fey Fox',
    cv: 2,
    hp: 26,
    av: 0,
    speed: '35 ft.',
    dmgMod: '+1d4',
    class: 'Animal',
    type: 'Fey',
    treasure: 'None',
    characteristics: { STR: 14, CON: 14, SIZ: 12, INT: 7, ACU: 15, DEX: 18, SOC: 10 },
    attacks: ['Bite 65% 1d6+1+1d4'],
    skills: 'Acrobatics 50%, Athletics 45%, Dodge 50%, Spot 65%, Survival 45%, Stealth 50%',
    special: ['Darkvision 60 ft.', 'See Invisibility', 'See Navirite'],
    weaknesses: 'Cold Iron',
    habitat: 'Plains, desert',
    encounter: 'Solitary, pair',
  },
  {
    slug: 'frost-worm',
    name: 'Frost Worm',
    pageTitle: 'Frost Worm',
    cv: 6,
    hp: 81,
    av: 14,
    speed: '50\', Burrow 20\', Swim 50\'',
    dmgMod: '+4d6',
    class: 'Monster',
    type: 'Magical Beast (Cold)',
    horror: 'First Encounter (2/1d12+1)',
    treasure: 'Harvestables',
    characteristics: { STR: 26, CON: 20, SIZ: 55, INT: 6, ACU: 12, DEX: 10, SOC: 10 },
    attacks: ['Bite 85% 2d8+6+4d6+1d8 (Cold)', 'Slam 85% 2d8+6+4d6+1d8 (Cold)'],
    skills: 'Dodge 85%, Grapple 90%, Hide 75%, Listen 80%, Spot 80%, Stealth 70%, Athletics 90%, Survival 85%',
    special: ['Cold', 'Trill', 'Breath Weapon', 'Death Throes', 'Darkvision 60\'', 'Immunity to Cold', 'Vulnerability to Fire', 'Reach 25\''],
    weaknesses: 'Fire',
    habitat: 'Arctic glaciers, frozen tundra, ice caves',
    encounter: 'Solitary',
  },
  {
    slug: 'ghast',
    name: 'Ghast',
    pageTitle: 'Ghast',
    cv: 2,
    hp: 28,
    av: 2,
    speed: '25\'',
    dmgMod: '0',
    class: 'Monster',
    type: 'Undead',
    horror: '1/1d6',
    treasure: 'Harvestables',
    characteristics: { STR: 10, SIZ: 14, INT: 2, DEX: 18 },
    attacks: ['60% Claw 1d6+2+dm and bite 60% 1d6+2+dm+paralyze+ghast fever'],
    skills: 'Dodge 50%, Grapple 50%, Hide 50%, Listen 50%, Spot 50%, Stealth 50%',
    special: ['Dark Vision 60\'', 'Ghast Fever', 'Paralyze'],
    weaknesses: 'Silver',
    habitat: 'Any dark',
    encounter: 'Solitary, Pair, or Corpse (3-12)',
  },
  {
    slug: 'ghul',
    name: 'Ghul Grunt',
    pageTitle: 'Ghul',
    cv: 1,
    hp: 24,
    av: 1,
    speed: '25\'',
    dmgMod: '0',
    class: 'Monster',
    type: 'Terian',
    treasure: 'Equipment',
    characteristics: { STR: 12, CON: 10, SIZ: 14, INT: 6, ACU: 7, DEX: 12, SOC: 3 },
    attacks: ['Broadsword 50% 1d8+1+dm'],
    skills: 'Dodge 50%, Grapple 40%, Hide 40%, Listen 40%, Spot 40%, Stealth 35%',
    special: [],
    weaknesses: 'Aradan Steel',
    habitat: 'Any',
    encounter: 'Solitary, Pair, Hunting Party (3-8), Tribe (30+)',
  },
  {
    slug: 'giant-fire',
    name: 'Fire Giant',
    pageTitle: 'Fire Giant (Antavar)',
    cv: 5,
    hp: 55,
    av: 13,
    avNote: 'natural + steel breastplate',
    speed: '40 ft.',
    dmgMod: '+3d6',
    class: 'Being',
    type: 'Humanoid (Giant)',
    horror: '2/1d10+1',
    treasure: 'Standard',
    characteristics: { STR: 30, CON: 20, SIZ: 35, INT: 15, ACU: 14, DEX: 9, SOC: 10 },
    attacks: ['Greatsword 85% 3d6+3+3d6', 'Slam 85% 1d4+3+3d6', 'Boulder 65% 2d6+3+3d6'],
    skills: 'Acrobatics 45%, Athletics 85%, Dodge 50%, Knowledge 65%, Spot 60%, Survival 50%',
    special: ['Heat Metal', 'Immune to Fire', '+15% to all Heroic Actions', 'Reach 10 ft.'],
    weaknesses: 'Cold (double damage)',
    habitat: 'Warm mountains',
    encounter: 'Solitary',
  },
  {
    slug: 'giant-frost',
    name: 'Frost Giant',
    pageTitle: 'Frost Giant (Hallavar)',
    cv: 5,
    hp: 70,
    av: 11,
    avNote: 'natural + hide armor',
    speed: '40 ft., Swim 30 ft.',
    dmgMod: '+4d6',
    class: 'Being',
    type: 'Giant',
    treasure: 'Standard',
    characteristics: { STR: 28, CON: 20, SIZ: 50, INT: 10, ACU: 15, DEX: 9, SOC: 9 },
    attacks: ['Great Axe 80% 3d6+3+4d6', 'Slam 80% 2d6+3+4d6', 'Boulder 65% 2d6+3+3d6'],
    skills: 'Acrobatics 45%, Athletics 80%, Dodge 50%, Knowledge 65%, Persuasion 45%, Spot 55%, Spellcraft 75%, Survival 55%',
    special: ['Immune to Cold', 'Hold Breath 80 minutes', 'Spellcasting (CL 4)', 'Reach 15 ft.'],
    weaknesses: 'Fire (double damage)',
    habitat: 'Cold regions',
    encounter: 'Solitary, pair, or tribe (4–16)',
  },
  {
    slug: 'giant-hill',
    name: 'Hill Giant',
    pageTitle: 'Hill Giant (Makvar)',
    cv: 4,
    hp: 50,
    av: 2,
    speed: '35\'',
    dmgMod: '+2d6',
    class: 'Being',
    type: 'Giant',
    treasure: '150 gp',
    characteristics: { STR: 22, CON: 18, SIZ: 32, INT: 8, ACU: 10, DEX: 9, SOC: 7 },
    attacks: ['Great Club 80% 2d8+4+dm and Slam 80% 1d6+4+dm', 'Boulder 70% 2d6+4+dm'],
    skills: 'Dodge 60%, Grapple 65%, Hide 50%, Listen 65%, Spot 65%, Stealth 50%',
    special: ['Rage', 'Reach 10\''],
    habitat: 'Hills, Mountains',
    encounter: 'Solitary, Pair, or Tribe (4–16)',
  },
  {
    slug: 'giant-mountain',
    name: 'Mountain Giant',
    pageTitle: 'Mountain Giant (Ceninvar)',
    cv: 12,
    hp: 78,
    av: 8,
    speed: '50 (Climb 30)',
    dmgMod: '+4d6',
    class: 'Being',
    type: 'Giant',
    horror: 'None',
    treasure: 'Standard',
    characteristics: { STR: 26, CON: 18, SIZ: 60, INT: 12, ACU: 11, DEX: 12, SOC: 10 },
    attacks: ['Great Club 75% 2d8+8+4d6,', 'Slam 65% 1d6+8+4d6, Boulder 55% 2d8+8+4d6'],
    skills: 'Acrobatics +30%, Athletics +60%, Awareness +60%, Survival +60%',
    special: ['Reach 15 ft', 'Disperse Magic', 'Over-Extended Attack', 'Powerful', 'Stunning Strike'],
  },
  {
    slug: 'glimmer-worm',
    name: 'Glimmer Worm',
    pageTitle: 'Glimmer Worm',
    cv: 3,
    hp: 30,
    av: 2,
    speed: '25',
    dmgMod: '0',
    class: 'Monster',
    type: 'Vermin',
    horror: '0/1d3',
    treasure: 'Harvest (Silk Gland)',
    characteristics: { STR: 17, CON: 12, SIZ: 18, INT: 1, ACU: 10, DEX: 12 },
    attacks: ['Bite 1d8+2+dm'],
    skills: 'Combat and Main Skills 60%, Other Skills 35%',
    special: ['Filament', 'Pull', 'Hold'],
    weaknesses: 'Fire burns its filaments.',
  },
  {
    slug: 'gnoll',
    name: 'Gnoll',
    pageTitle: 'Gnoll',
    cv: 1,
    hp: 28,
    av: 1,
    speed: '30\'',
    dmgMod: '+1d4',
    class: 'Being',
    type: 'Terianeth',
    treasure: 'Equipment',
    characteristics: { STR: 13, CON: 12, SIZ: 16, INT: 10, ACU: 12, DEX: 10, SOC: 9 },
    attacks: ['50% Broadsword 1d8+dm', 'bite 50% 1d6+1+dm'],
    skills: 'Dodge 50%, Grapple 40%, Hide 40%, Listen 40%, Spot 40%, Stealth 35%',
    special: ['Fast', 'Dark Vision 40\''],
    habitat: 'Any',
    encounter: 'Solitary, pair, hunting party (3-6), band (12-20), or tribe (40+)',
  },
  {
    slug: 'gnoll',
    name: 'Gnoll Shaman',
    pageTitle: 'Gnoll',
    cv: 3,
    hp: 25,
    av: 1,
    speed: '30\'',
    dmgMod: '1d4',
    class: 'Being',
    type: 'Terianeth',
    treasure: '40 gp (treasure)',
    characteristics: { STR: 11, CON: 11, SIZ: 14, INT: 16, ACU: 14, DEX: 13, SOC: 11 },
    attacks: ['Ranged: Wild Magic 62% 1d4+1', 'Melee: Quarterstaff 22% 1d6+dm+Wild Magic'],
    skills: 'Dodge 58%, First Aid 73%, Grapple 22%, Hide 17%, Insight 42%, Knowledge (General) 40%, Knowledge (Arcane) 60%, Listen 67%, Medicine 33%, Persuade 57%, Research 47%, Sense 37%, Spellcraft 75%, Spot 62%, Stealth 22%, Survival 33%',
    special: ['Spell Memory', 'Wild Magic', 'Elemental Foci: Fire', 'Fast', 'Dark Vision 40\''],
  },
  {
    slug: 'goblin',
    name: 'Goblin Commoner',
    pageTitle: 'Goblin',
    cv: 0.5,
    hp: 8,
    av: 1,
    speed: '20\'',
    dmgMod: '-2',
    class: 'Being',
    type: 'Goblinoid',
    treasure: 'Equipment',
    characteristics: { STR: 6, CON: 4, SIZ: 4, INT: 9, ACU: 8, DEX: 8, SOC: 4 },
    attacks: ['Dagger 45% 1d4+dm'],
    skills: 'Dodge 45%, Grapple 25%, Hide 25%, Listen 25%, Spot 25%, Stealth 25%',
    special: ['Darkvision 40\''],
    habitat: 'Any',
    encounter: 'Single, Pair, or Tribe 3-40',
  },
  {
    slug: 'goblin',
    name: 'Goblin Fighter',
    pageTitle: 'Goblin',
    cv: 1,
    hp: 13,
    av: 1,
    speed: '20\'',
    dmgMod: '-1',
    class: 'Being',
    type: 'Goblinoid',
    treasure: 'Equipment',
    characteristics: { STR: 9, CON: 8, SIZ: 5, INT: 6, ACU: 8, DEX: 9, SOC: 8 },
    attacks: ['Spear or Short Sword 50% 1d6+dm'],
    skills: 'Dodge 50%, Grapple 40%, Hide 40%, Listen 40%, Spot 40%, Stealth 35%',
    special: ['Darkvision 40\''],
    habitat: 'Any',
    encounter: 'Single, Pair, or Tribe 3-40',
  },
  {
    slug: 'goblin',
    name: 'Goblin Grabber',
    pageTitle: 'Goblin',
    cv: 2,
    hp: 15,
    av: 2,
    speed: '20\'',
    dmgMod: '0',
    class: 'Being',
    type: 'Goblinoid',
    treasure: 'Equipment',
    characteristics: { STR: 11, CON: 9, SIZ: 6, INT: 6, ACU: 8, DEX: 8, SOC: 8 },
    attacks: ['Hook Blade 65% 1d6+dm+trip', '(Thrown) Short Spear 55% 1d6+dm (40\')'],
    skills: 'Dodge 60%, Grapple 80%, Hide 60%, Listen 50%, Spot 50%, Stealth 60%',
    special: ['Darkvision 40\''],
    habitat: 'Any',
    encounter: 'Pair',
  },
  {
    slug: 'goblin',
    name: 'Goblin Brute',
    pageTitle: 'Goblin',
    cv: 2,
    hp: 19,
    av: 2,
    speed: '25\'',
    dmgMod: '1d4',
    class: 'Being',
    type: 'Goblinoid',
    treasure: 'Equipment',
    characteristics: { STR: 16, CON: 10, SIZ: 9, INT: 6, ACU: 8, DEX: 13, SOC: 7 },
    attacks: ['Great Sword or Hammer 65% 2d8+dm+1', '(Thrown) Short Spear 55% 1d6+dm (40\')'],
    skills: 'Dodge 50%, Grapple 50%, Hide 50%, Listen 50%, Spot 50%, Stealth 50%',
    special: ['Weapon Expertise'],
    habitat: 'any',
    encounter: 'Single, Pair, or Squad',
  },
  {
    slug: 'goblin',
    name: 'Goblin Mystic',
    pageTitle: 'Goblin',
    cv: 2,
    hp: 14,
    av: 2,
    speed: '20\'',
    dmgMod: '-1',
    class: 'Being',
    type: 'Goblinoid',
    treasure: 'Equipment',
    characteristics: { STR: 8, CON: 8, SIZ: 6, INT: 12, ACU: 11, DEX: 8, SOC: 11 },
    attacks: ['Dagger 55% 1d4+dm', '75% Wild Magic 1d4+1'],
    skills: 'Dodge 60%, Grapple 80%, Hide 60%, Listen 50%, Spellcraft 75%, Spot 50%, Stealth 60%',
    special: ['Darkvision 40\'', 'Spell Memory', 'Wild Magic'],
    habitat: 'Any',
    encounter: 'Pair',
  },
  {
    slug: 'goblin',
    name: 'Goblin, Arnach',
    pageTitle: 'Goblin',
    cv: 2,
    hp: 15,
    av: 2,
    speed: '20\'',
    dmgMod: '-1',
    class: 'Being',
    type: 'Goblinoid',
    treasure: 'Equipment',
    characteristics: { STR: 11, CON: 9, SIZ: 5, INT: 6, ACU: 8, DEX: 8, SOC: 8 },
    attacks: ['Short Spear 65% 1d6+dm', '(Thrown) Shortbow 65% 1d6+dm+spider sac'],
    skills: 'Dodge 60%, Grapple 80%, Hide 60%, Listen 50%, Spot 50%, Stealth 60%',
    special: ['Darkvision 40\''],
    habitat: 'Any',
    encounter: 'Pair',
  },
  {
    slug: 'golem-clay',
    name: 'Golem, Clay',
    pageTitle: 'Golem, Clay',
    cv: 5,
    hp: 100,
    av: 10,
    speed: '20 ft.',
    dmgMod: '+2d6',
    class: 'Monster',
    type: 'Construct',
    horror: '2/1d10+1',
    treasure: 'None',
    characteristics: { STR: 24, SIZ: 20, ACU: 10, DEX: 9 },
    attacks: ['Slam (2) 75% 2d8+1+2d6 + Cursed Wound'],
    skills: 'Grapple 60%, Spot 60%',
    special: ['Berserk', 'Cursed Wound', 'Construct Traits', 'Haste', 'Immunity to Magic', 'Damage Resistance 10/tritium and bludgeoning', 'Darkvision 60 ft.', 'Low-Light Vision', 'Reach 10 ft.'],
    weaknesses: 'Bend Sound',
    habitat: 'Any',
    encounter: 'Solitary or gang (2–4)',
  },
  {
    slug: 'golem-flesh',
    name: 'Golem, Flesh',
    pageTitle: 'Golem, Flesh',
    cv: 4,
    hp: 72,
    av: 10,
    speed: '30 ft.',
    dmgMod: '+1d6',
    class: 'Monster',
    type: 'Construct',
    horror: '1/1d8 (First Encounter)',
    treasure: 'Harvestables',
    characteristics: { STR: 20, SIZ: 18, ACU: 10, DEX: 9 },
    attacks: ['Slam (2) 75% 1d8+4+1d6'],
    skills: 'Dodge 65%, Grapple 75%, Hide 45%, Listen 55%, Spot 65%, Stealth 25%, Other Skills 25%',
    special: ['Berserk', 'Bellow', 'Construct Traits', 'Immunity to Electricity', 'Immunity to Magic', 'Darkvision 60 ft.'],
    weaknesses: 'Cold, Fire',
    habitat: 'Any',
    encounter: 'Solitary',
  },
  {
    slug: 'golem-iron',
    name: 'Golem, Iron',
    pageTitle: 'Golem, Iron',
    cv: 25,
    hp: 200,
    av: 15,
    speed: '25 ft.',
    dmgMod: '+3d6',
    class: 'Monster',
    type: 'Construct',
    horror: 'None',
    treasure: 'None',
    characteristics: { STR: 25, SIZ: 40, ACU: 8, DEX: 8 },
    attacks: ['Slam (2) 85% 2d6+3+3d6', 'Bolt of Lightning 4d6 in a 30\' straight line'],
    skills: 'Athletics 75%, Intimidate 45%, Listen 65%',
    special: ['Breath Weapon', 'Construct Traits', 'Magical Immunity', 'Whirlwind'],
    weaknesses: 'Tritium (negates 1/2 AV)',
    habitat: 'Any',
    encounter: 'Solitary',
  },
  {
    slug: 'golem-root',
    name: 'Root Golem',
    pageTitle: 'Root Golem',
    cv: 2,
    hp: 36,
    av: 4,
    avNote: 'natural',
    speed: '30 ft.',
    dmgMod: '+1d6',
    class: 'Monster',
    type: 'Construct',
    horror: 'None',
    treasure: 'None',
    characteristics: { STR: 16, SIZ: 18, ACU: 10, DEX: 13, SOC: 5 },
    attacks: ['Slam (2) 65% 1d6+1+1d6 + Grab'],
    skills: 'Grapple 65%, Spot 50%',
    special: ['Grab', 'Strangle', 'Water Source', 'Construct Traits'],
    weaknesses: 'Fire, requires a water source to survive',
    habitat: 'Forest or underground',
    encounter: 'Any',
  },
  {
    slug: 'golem-stone',
    name: 'Stone Golem',
    pageTitle: 'Stone Golem',
    cv: 25,
    hp: 100,
    av: 12,
    speed: '20 ft.',
    dmgMod: '+2d6',
    class: 'Monster',
    type: 'Construct',
    horror: 'None',
    treasure: 'Harvestable',
    characteristics: { STR: 24, SIZ: 20, ACU: 10, DEX: 9 },
    attacks: ['Slam (x2) 85% 1d8+5+2d6 (19 average)'],
    skills: 'Grapple 60%, Spot +60%',
    special: ['Slow (every 2 rounds)', 'Tritium and Blackrock ignore AV', 'Construct Traits'],
    weaknesses: 'Tritium, Blackrock',
  },
  {
    slug: 'gorgalug',
    name: 'Gorgalug, Adolescent',
    pageTitle: 'Gorgalug',
    cv: 3,
    hp: 38,
    av: 4,
    speed: '30\'',
    dmgMod: '+2d6',
    class: 'Animal',
    type: 'Beast',
    treasure: 'Harvestables',
    characteristics: { STR: 20, CON: 14, SIZ: 24, INT: 5, ACU: 12, DEX: 12 },
    attacks: ['Slam 60% 1d8+3+dm', 'and Acid Spit'],
    skills: 'Dodge 55%, Grapple 60%, Hide 50%, Listen 60%, Spot 60%, Stealth 50%',
    special: ['Acid Immunity', 'Acid Spit', 'Pungent Scent', 'Dissolve Stone', 'Armor Shell'],
    weaknesses: 'Salt does 2d8 damage per lb',
    habitat: 'Underground',
    encounter: 'Solitary',
  },
  {
    slug: 'gorgalug',
    name: 'Gorgalug',
    pageTitle: 'Gorgalug',
    cv: 5,
    hp: 60,
    av: 6,
    speed: '40\'',
    dmgMod: '+3d6',
    class: 'Animal',
    type: 'Beast',
    treasure: 'Harvestables',
    characteristics: { STR: 25, CON: 25, SIZ: 35, INT: 5, ACU: 10, DEX: 11 },
    attacks: ['Slam (2) 80% 1d6+5+3d6', 'and Acid Spit'],
    skills: 'Dodge 80%, Grapple 75%, Hide 75%, Listen 75%, Spot 75%, Stealth 75%',
    special: ['Acid Immunity', 'Acid Spit', 'Pungent Scent', 'Dissolve Stone', 'Armor Shell'],
    weaknesses: 'Salt does 2d8 damage per lb',
    habitat: 'Underground',
    encounter: 'Solitary',
  },
  {
    slug: 'green-hag',
    name: 'Green Hag',
    pageTitle: 'Green Hag',
    cv: 3,
    hp: 28,
    av: 11,
    avNote: 'natural',
    speed: '30 ft., Swim 30 ft.',
    dmgMod: '+1d6',
    class: 'Monster',
    type: 'Navirite (Fey)',
    horror: '1/1d6',
    treasure: 'Standard',
    characteristics: { STR: 18, CON: 12, SIZ: 16, INT: 12, ACU: 12, DEX: 12, SOC: 15 },
    attacks: ['2 Claws 75% 1d6+1+1d6'],
    skills: 'Acrobatics 55%, Athletics 65%, Dodge 50%, Knowledge 55%, Persuasion 60%, Spellcraft 75%, Spot 60%, Survival 55%',
    special: ['Weakening Touch', 'Mimicry', 'Spell-Like Abilities', 'Darkvision 90 ft.', 'Resistant', 'Water Breathing'],
    weaknesses: 'Cold Iron',
    habitat: 'Temperate or Warm Marshes',
    encounter: 'Solitary or Covey (3 hags + 1–8 ogres + 1–4 evil giants)',
  },
  {
    slug: 'grelm',
    name: 'Grelm',
    pageTitle: 'Grelm',
    cv: 4,
    hp: 48,
    av: 4,
    speed: '30',
    dmgMod: '2d6',
    class: 'Monster',
    type: 'Navirite',
    horror: 'First Encounter 1/1d8, if grappled by the grelm 1/1d8',
    treasure: 'Standard (gems and coins)',
    characteristics: { STR: 16, CON: 16, SIZ: 32, INT: 3, ACU: 6, DEX: 14, SOC: 0 },
    attacks: ['(2) Claw 1d4+1+2d6 and Bite (if grappled) and 1d6+1+poison', 'ranged: Boulder 2d6 (30\')'],
    skills: 'Combat and Main Skills 65%, Other Skills 35%',
    special: ['Reach 10\'', 'Grab', 'Poison', 'Fearless'],
    weaknesses: 'Cold Iron (double damage)',
  },
  {
    slug: 'griffon',
    name: 'Griffon',
    pageTitle: 'Griffon',
    cv: 3,
    hp: 44,
    av: 6,
    speed: '30\', Fly 80\'',
    dmgMod: '1d6',
    class: 'Monster',
    type: 'Magical Beast',
    horror: 'None',
    treasure: 'None',
    characteristics: { STR: 18, CON: 16, SIZ: 28, INT: 4, ACU: 12, DEX: 14, SOC: 9 },
    attacks: ['Bite 75% 2d6+3+1d6, 2 Claws 65% 1d4+3+1d6'],
    skills: 'Dodge 65%, Grapple 75%, Hide 50%, Listen 70%, Spot 75%, Stealth 50%, Athletics 80%, Survival 65%',
    special: ['Pounce', 'Rake', 'Scent', 'Darkvision 60\'', 'Reach 10\''],
    weaknesses: 'None',
    habitat: 'Temperate hills and mountains',
    encounter: 'Solitary, Pair, or Pride (6-10)',
  },
  {
    slug: 'hag-night',
    name: 'Night Hag',
    pageTitle: 'Night Hag',
    cv: 5,
    hp: 54,
    av: 15,
    speed: '30 ft.',
    dmgMod: '+1d6',
    class: 'Monster',
    type: 'Navirite (Fey)',
    horror: '3/1d10+1',
    treasure: 'Double (includes Heartstone)',
    characteristics: { STR: 20, CON: 22, SIZ: 16, INT: 18, ACU: 16, DEX: 18, SOC: 16 },
    attacks: ['2 Claws 75% 2d6+1+1d6', 'Bite 75% 2d6+1+1d6+1d8 (Disease)'],
    skills: 'Acrobatics 60%, Athletics 65%, Dodge 65%, Knowledge 90%, Persuasion 70%, Sense 75%, Spellcraft 70%, Spot 75%, Stealth 65%, Survival 55%',
    special: ['Dream Haunting', 'Disease (Demon Fever)', 'Spell-Like Abilities', 'Etherealness', 'Heartstone', 'Summon Sisters', 'Ritual of the Dream Mark', 'Pool of Pain', 'Darkvision 90 ft.', 'Resistant', 'Immunities (Charm, Cold, Fear, Fire, Sleep)'],
    weaknesses: 'Cold Iron, Magic',
    habitat: 'Any',
    encounter: 'Solitary or Covey (3 hags + 1–8 ogres + 1–4 evil giants)',
  },
  {
    slug: 'hag-sea',
    name: 'Sea Hag',
    pageTitle: 'Sea Hag',
    cv: 2,
    hp: 28,
    av: 6,
    avNote: 'natural',
    speed: '30 ft., Swim 40 ft.',
    dmgMod: '+1d4',
    class: 'Monster',
    type: 'Navirite (Fey)',
    horror: '1/1d4 (First Encounter)',
    treasure: 'Standard',
    characteristics: { STR: 17, CON: 14, SIZ: 14, INT: 10, ACU: 12, DEX: 12, SOC: 14 },
    attacks: ['2 Claws 65% 1d6+1+1d4'],
    skills: 'Acrobatics 45%, Athletics 65%, Dodge 50%, Spot 65%, Knowledge 50%, Persuasion 55%, Spellcraft 75%, Survival 55%',
    special: ['Amphibious', 'Evil Eye', 'Horrific Appearance', 'Spell Resistance 12', 'Darkvision 60 ft.', 'Low-Light Vision'],
    weaknesses: 'Cold Iron',
    habitat: 'Temperate Aquatic',
    encounter: 'Solitary or Covey (3 hags of any kind + 1–8 ogres + 1–4 evil giants)',
  },
  {
    slug: 'hell-hound',
    name: 'Hell Hound',
    pageTitle: 'Hell Hound',
    cv: 3,
    hp: 26,
    av: 4,
    speed: '25\'',
    dmgMod: '1d4',
    class: 'Monster',
    type: 'Navirite',
    treasure: 'Harvestables',
    characteristics: { STR: 13, CON: 12, SIZ: 14, INT: 6, ACU: 12, DEX: 12, SOC: 8 },
    attacks: ['Grapple 60% and Bite 75% 1d6+3+dm+fiery bite'],
    skills: 'Acrobatics 60%, Athletics 60%, Dodge 65%, Grapple 60%, Hide 60%, Listen 60%, Spot 60%, Stealth 60%, Track 80%',
    special: ['Fiery Bite', 'Breath Weapon', 'Scent', 'Track', 'Darkvision 60 ft.', 'Immunity to Fire'],
    weaknesses: 'Cold Iron, Cold Vulnerability (takes double damage from cold)',
    habitat: 'Any land or underground that is not cold or freezing',
    encounter: 'Solitary, pair, or pack (5–12)',
  },
  {
    slug: 'homunculus',
    name: 'Homunculus',
    pageTitle: 'Homunculus',
    cv: 1,
    hp: 8,
    av: 2,
    speed: '20 ft.',
    dmgMod: '-2',
    class: 'Monster',
    type: 'Navirite Fey (Construct-like)',
    treasure: 'None',
    characteristics: { STR: 6, CON: 6, SIZ: 2, INT: 9, ACU: 9, DEX: 9, SOC: 9 },
    attacks: ['Claw 50% 1d6-2', 'Bite 50% 1d6-2'],
    skills: 'Dodge 70%, Grapple 25%, Hide 65%, Listen 55%, Spot 55%, Stealth 65%, Acrobatics 55%, Athletics 45%, Endurance 45%, Survival 40%',
    special: ['Summoner\'s Bond', 'Imbued Trait', 'Darkvision 60 ft.'],
    weaknesses: 'Dependent on the creator; regains life/abilities only when dismissed or destroyed',
    habitat: 'Any',
    encounter: 'Solitary (bound to creator)',
  },
  {
    slug: 'hulking-horror',
    name: 'Hulking Horror',
    pageTitle: 'Hulking Horror',
    cv: 6,
    hp: 44,
    av: 6,
    speed: '25',
    dmgMod: '2d6',
    class: 'Monster',
    type: 'Aberration',
    horror: '2/1d8+1',
    characteristics: { STR: 18, CON: 18, SIZ: 26, INT: 7, ACU: 8, DEX: 13, SOC: 5 },
    attacks: ['Smash 75% 1d8+2+2d6'],
    skills: 'Dodge 55%, Other Skills 45%',
    special: ['Reach'],
  },
  {
    slug: 'imps',
    name: 'Fire Imp',
    pageTitle: 'Imps',
    cv: 3,
    hp: 16,
    av: 4,
    speed: '30 (Fly 50)',
    dmgMod: '+0',
    class: 'Monster',
    type: 'Navirite (Fey)',
    horror: 'First Encounter 1/1d4',
    treasure: 'Standard',
    characteristics: { STR: 10, CON: 10, SIZ: 8, INT: 11, ACU: 10, DEX: 13, SOC: 12 },
    attacks: ['Claws (x2) 60% 1d6 + 1d4 fire'],
    skills: 'Acrobatics +30%, Thievery +60%, Knowledge +10%, Persuasion +20%, Spellcraft +20%',
    special: ['Breath Weapon', 'Spell-Like Abilities', 'Fast Healing 2 (in fire)', 'DR 5 vs Cold Iron', 'Magic', 'Legacy'],
    weaknesses: 'Cold, Cold Iron, Magic/Legacy Weapons (Cold damage is doubled)',
    habitat: 'Any',
    encounter: 'Any',
  },
  {
    slug: 'imps',
    name: 'Earth Imp',
    pageTitle: 'Imps',
    cv: 3,
    hp: 18,
    av: 5,
    speed: '20 (Burrow 10)',
    dmgMod: '+1d2',
    class: 'Monster',
    type: 'Navirite (Fey)',
    horror: 'First Encounter 1/1d4',
    treasure: 'Standard',
    characteristics: { STR: 12, CON: 13, SIZ: 8, INT: 10, ACU: 10, DEX: 9, SOC: 10 },
    attacks: ['Claws (x2) 55% 1d6+1 + 1d4 earth (bludgeoning)'],
    skills: 'Endurance +40%, Athletics +30%, Awareness +20%, Spellcraft +20%, Survival +30%',
    special: ['Tremorsense 30\'', 'Burrow', 'Stoneform', 'Spell-Like Abilities'],
    weaknesses: 'Wind-based magic, Sonic',
  },
  {
    slug: 'imps',
    name: 'Water Imp',
    pageTitle: 'Imps',
    cv: 3,
    hp: 16,
    av: 3,
    speed: '30 (Swim 50)',
    dmgMod: '+0',
    class: 'Monster',
    type: 'Navirite (Fey)',
    horror: 'First Encounter 1/1d4',
    treasure: 'Standard',
    characteristics: { STR: 9, CON: 11, SIZ: 8, INT: 12, ACU: 11, DEX: 12, SOC: 12 },
    attacks: ['Claws (x2) 55% 1d6 + 1d4 cold'],
    skills: 'Swim +60%, Stealth +40%, Spellcraft +30%, Survival +20%, Awareness +30%',
    special: ['Amphibious', 'Water Jet (Breath)', 'Spell-Like Abilities'],
    weaknesses: 'Fire, Lightning',
  },
  {
    slug: 'imps',
    name: 'Wind Imp',
    pageTitle: 'Imps',
    cv: 3,
    hp: 15,
    av: 3,
    speed: '40 (Fly 80, perfect)',
    dmgMod: '-1',
    class: 'Monster',
    type: 'Navirite (Fey)',
    horror: 'First Encounter 1/1d4',
    treasure: 'Standard',
    characteristics: { STR: 8, CON: 10, SIZ: 8, INT: 12, ACU: 12, DEX: 15, SOC: 11 },
    attacks: ['Gust Claws (x2) 60% 1d6 + 1d4 wind (knockback on crit)'],
    skills: 'Acrobatics +50%, Stealth +40%, Spellcraft +30%, Awareness +40%, Thievery +30%',
    special: ['Invisibility (air)', 'Flyby', 'Windform', 'Spell-Like Abilities'],
    weaknesses: 'Earth, Metal',
  },
  {
    slug: 'kira',
    name: 'Kira',
    pageTitle: 'Kira',
    cv: 0.5,
    hp: 7,
    av: 0,
    speed: '15\'',
    dmgMod: '-2',
    class: 'Animal',
    type: 'Primate',
    treasure: 'Harvestables',
    characteristics: { STR: 6, CON: 10, SIZ: 3, INT: 6, ACU: 11, DEX: 16, SOC: 8 },
    attacks: ['Bite 45% 1d6+dm'],
    skills: 'Dodge 65%, Grapple 25%, Hide 60%, Listen 25%, Spot 25%, Stealth 75%',
    special: ['See Invisibility', 'Fruitful Droppings'],
    weaknesses: 'Low HP',
    habitat: 'Any Temperate Forest',
    encounter: 'Solitary, Pair, or Gathering (3-40)',
  },
  {
    slug: 'kuduu',
    name: 'Kuduu',
    pageTitle: 'Kuduu',
    cv: 4,
    hp: 65,
    av: 7,
    speed: '30\'',
    dmgMod: '3d6',
    class: 'Animal',
    type: 'Mammal',
    horror: 'None',
    treasure: 'None',
    characteristics: { STR: 30, CON: 20, SIZ: 45, INT: 7, ACU: 12, DEX: 9, SOC: 8 },
    attacks: ['Slam 75% 1d8+4+3d6, Gore 75% 1d8+4+3d6'],
    skills: 'Dodge 50%, Grapple 75%, Hide 35%, Listen 55%, Spot 55%, Stealth 35%, Athletics 80%',
    special: ['Trample', 'Dark Vision'],
    weaknesses: 'None',
    habitat: 'Cold and temperate plains',
    encounter: 'Solitary or Herd',
  },
  {
    slug: 'kyzk',
    name: 'Kyzk',
    pageTitle: 'Kyzk',
    cv: 3,
    hp: 43,
    av: 4,
    avNote: 'thick hide',
    speed: '35\'',
    dmgMod: '+2d6',
    class: 'Animal',
    type: 'Mammal',
    treasure: 'Harvestables',
    characteristics: { STR: 20, CON: 18, SIZ: 25, INT: 3, ACU: 12, DEX: 11, SOC: 5 },
    attacks: ['Gore 75% 1d8+3+dm and Trample 75% 1d8+3+d'],
    skills: 'Dodge 65%, Grapple 60%, Hide 60%, Listen 60%, Spot 60%, Stealth 60%',
    special: ['Stampede'],
    habitat: 'Warm plains or desert',
    encounter: 'Herd (15–100)',
  },
];
