/**
 * SagaBorn D100 — Equipment catalog (weapons, armor, gear)
 *
 * Source: 005 Marketplace/Equipment doc (2026-07-14 pull), corrected by the
 * 2026-07-13 errata (errata WINS on conflict):
 *   - errata #34: mastercraft is always 4x base cost (kit prices fixed below)
 *   - errata #35: Alchemist's Fire = 1d6+2 fire elemental damage
 * Costs are in gp (1 gp = 10 sp = 100 cp; sp/cp prices converted to fractions).
 */

import type { Weapon, Armor, GearItem, Shield } from './types';

// ---------------------------------------------------------------------------
// A) Weapons — melee (Light/Medium/Large) and ranged weapon tables
// ---------------------------------------------------------------------------

export const WEAPONS: Weapon[] = [
  // --- Light Weapons ---
  {
    name: 'Dagger',
    class: 'Light',
    skill: 'Piercing Weapons',
    damageType: 'P',
    damage: '1d4',
    addDamageModifier: true,
    hands: '1h',
    str: 4,
    dex: 4,
    range: "5'/20'",
    costGp: 2,
    weightLb: 1,
    hp: 15,
    special: 'Impaling',
  },
  {
    name: 'Knife',
    class: 'Light',
    skill: 'Slashing Weapons',
    damageType: 'S',
    damage: '1d4',
    addDamageModifier: true,
    hands: '1h',
    str: 4,
    dex: 4,
    range: "5'/20'",
    costGp: 1,
    weightLb: 1,
    hp: 15,
    special: 'Bleeding',
  },
  {
    name: 'Stiletto',
    class: 'Light',
    skill: 'Piercing Weapons',
    damageType: 'P',
    damage: '1d4',
    addDamageModifier: true,
    hands: '1h',
    str: 4,
    dex: 4,
    range: "5'/0",
    costGp: 4,
    weightLb: 1,
    hp: 15,
    special: 'Impaling',
  },

  // --- Medium Weapons ---
  {
    name: 'Blackjack',
    class: 'Medium',
    skill: 'Bludgeoning Weapons',
    damageType: 'B',
    damage: '2d6',
    addDamageModifier: true,
    hands: '1h',
    str: 7,
    dex: 7,
    range: "5'/0",
    costGp: 1, // data note: suspect — 2d6 for 1 gp is out of line with the rest of the table; encoded as printed
    weightLb: 2,
    hp: 10,
    special: 'Crushing; non-lethal damage only',
  },
  {
    name: 'Broadsword',
    class: 'Medium',
    skill: 'Slashing Weapons',
    damageType: 'S',
    damage: '1d8',
    addDamageModifier: true,
    hands: '1h',
    str: 9,
    dex: 8,
    range: "5'/0",
    costGp: 12,
    weightLb: 5,
    hp: 20,
    special: 'Bleeding',
  },
  {
    name: 'Club',
    class: 'Medium',
    skill: 'Bludgeoning Weapons',
    damageType: 'B',
    damage: '1d6',
    addDamageModifier: true,
    hands: '1h',
    str: 9,
    dex: 7,
    range: "5'/0",
    costGp: 0.5, // 5 sp
    weightLb: 4,
    hp: 10,
    special: 'Knockback',
  },
  {
    name: 'Handaxe',
    class: 'Medium',
    skill: 'Slashing Weapons',
    damageType: 'S',
    damage: '1d6',
    addDamageModifier: true,
    hands: '1h',
    str: 9,
    dex: 7,
    range: "5'/0",
    costGp: 6,
    weightLb: 3,
    hp: 10,
    special: 'Bleeding',
  },
  {
    name: 'Mace',
    class: 'Medium',
    skill: 'Bludgeoning Weapons',
    damageType: 'B',
    damage: '1d6',
    addDamageModifier: true,
    hands: '1h',
    str: 7,
    dex: 7,
    range: "5'/0",
    costGp: 9,
    weightLb: 5,
    hp: 20,
    special: 'Crushing',
  },
  {
    name: 'Quarterstaff',
    class: 'Medium',
    skill: 'Bludgeoning Weapons',
    damageType: 'B',
    damage: '1d6+1',
    addDamageModifier: true,
    hands: '2h',
    str: 7,
    dex: 9,
    range: "5'/0",
    costGp: null, // table shows '-' (effectively free / improvised)
    weightLb: 4,
    hp: 20,
    special: 'Crushing',
  },
  {
    name: 'Rapier',
    class: 'Medium',
    skill: 'Piercing Weapons',
    damageType: 'P',
    damage: '1d6',
    addDamageModifier: true,
    hands: '1h',
    str: 7,
    dex: 13,
    range: "5'/0",
    costGp: 20,
    weightLb: 2,
    hp: 15,
    special: 'Impaling',
  },
  {
    name: 'Scimitar',
    class: 'Medium',
    skill: 'Slashing Weapons',
    damageType: 'S',
    damage: '1d6',
    addDamageModifier: true,
    hands: '1h',
    str: 8,
    dex: 8,
    range: "5'/0",
    costGp: 15,
    weightLb: 4,
    hp: 19,
    special: 'Bleeding',
  },
  {
    name: 'Short spear',
    class: 'Medium',
    skill: 'Piercing Weapons',
    damageType: 'P',
    damage: '1d6',
    addDamageModifier: true,
    hands: '1h',
    str: 9,
    dex: 9,
    range: "10'/40'",
    costGp: 1,
    weightLb: 3,
    hp: 15,
    special: 'Impaling',
  },
  {
    name: 'Short sword',
    class: 'Medium',
    skill: 'Piercing Weapons',
    damageType: 'P',
    damage: '1d6',
    addDamageModifier: true,
    hands: '1h',
    str: 5,
    dex: 5,
    range: "5'/0",
    costGp: 10,
    weightLb: 2,
    hp: 20,
    special: 'Impaling',
  },
  {
    name: 'Wrist razors',
    class: 'Medium',
    skill: 'Slashing Weapons',
    damageType: 'S',
    damage: '1d6',
    addDamageModifier: true,
    hands: '1h',
    str: 7,
    dex: 7,
    range: "5'/0",
    costGp: 12,
    weightLb: 2,
    hp: 15,
    special: 'Bleeding or Impaling',
  },
  {
    name: 'Whip',
    class: 'Medium',
    skill: 'Slashing Weapons',
    damageType: 'S',
    damage: '1d4',
    addDamageModifier: true,
    hands: '1h',
    str: 9,
    dex: 10,
    range: "10'/0",
    costGp: 2,
    weightLb: 2,
    hp: 4,
    special: 'Entangle',
  },

  // --- Large Weapons ---
  {
    name: 'Battleaxe',
    class: 'Large',
    skill: 'Slashing Weapons',
    damageType: 'S',
    damage: '1d8',
    addDamageModifier: true,
    hands: '1h',
    str: 9,
    dex: 9,
    range: "5'/0",
    costGp: 10,
    weightLb: 6,
    hp: 15,
    special: 'Bleeding',
  },
  {
    // data note: table prints damage "1d8/2d6+dm" and STR/DEX "9/9 or 13/9".
    // Grip mapping assumed (1h = 1d8 @ STR 13, 2h = 2d6 @ STR 9), pending Mike.
    name: 'Bastard sword',
    class: 'Large',
    skill: 'Slashing Weapons',
    damageType: 'S',
    damage: '1d8',
    addDamageModifier: true,
    hands: '1h/2h',
    str: 13,
    dex: 9,
    grip2h: { damage: '2d6', str: 9, dex: 9 },
    range: "5'/0",
    costGp: 35,
    weightLb: 6,
    hp: 20,
    special: 'Bleeding',
  },
  {
    name: 'Dworven Waraxe',
    class: 'Large',
    skill: 'Slashing Weapons',
    damageType: 'S',
    damage: '2d8',
    addDamageModifier: true,
    hands: '2h',
    str: 12,
    dex: 9,
    range: "5'/0",
    costGp: 50,
    weightLb: 12,
    hp: 22,
    special: 'Bleeding',
  },
  {
    name: 'Longsword',
    class: 'Large',
    skill: 'Slashing Weapons',
    damageType: 'S',
    damage: '1d8',
    addDamageModifier: true,
    hands: '1h',
    str: 7,
    dex: 9,
    range: "5'/0",
    costGp: 15,
    weightLb: 4,
    hp: 15,
    special: 'Bleeding',
  },
  {
    name: 'Falchion',
    class: 'Large',
    skill: 'Slashing Weapons',
    damageType: 'S',
    damage: '3d4',
    addDamageModifier: true,
    hands: '2h',
    str: 7,
    dex: 11,
    range: "5'/0",
    costGp: 20,
    weightLb: 8,
    hp: 20,
    special: 'Bleeding',
  },
  {
    name: 'Mace, Heavy',
    class: 'Large',
    skill: 'Bludgeoning Weapons',
    damageType: 'B',
    damage: '1d8',
    addDamageModifier: true,
    hands: '1h',
    str: 9,
    dex: 9,
    range: "5'", // table prints "5'" with no range component
    costGp: 12,
    weightLb: 8,
    hp: 25,
    special: 'Crushing',
  },
  {
    name: 'Maul, Great',
    class: 'Large',
    skill: 'Bludgeoning Weapons',
    damageType: 'B',
    damage: '2d8',
    addDamageModifier: true,
    hands: '2h',
    str: 13,
    dex: 9,
    range: "5'/0",
    costGp: 15,
    weightLb: 16,
    hp: 15,
    special: 'Crushing',
  },
  {
    // data note: table Skill column reads "B / P" (dual type); primary letter
    // B encoded as the governing skill/damageType, alternate noted in special.
    name: 'Morningstar',
    class: 'Large',
    skill: 'Bludgeoning Weapons',
    damageType: 'B',
    damage: '1d8',
    addDamageModifier: true,
    hands: '1h',
    str: 11,
    dex: 7,
    range: "5'/0",
    costGp: 8,
    weightLb: 6,
    hp: 12,
    special: 'Crushing or Impaling (B/P dual type)',
  },
  {
    // data note: table prints damage "1d8/2d6+dm" but only one STR/DEX (11/7);
    // grip mapping assumed (1h = 1d8, 2h = 2d6, same minimums), pending Mike.
    name: 'Long Spear',
    class: 'Large',
    skill: 'Piercing Weapons',
    damageType: 'P',
    damage: '1d8',
    addDamageModifier: true,
    hands: '1h/2h',
    str: 11,
    dex: 7,
    grip2h: { damage: '2d6', str: 11, dex: 7 },
    range: "10'/0",
    costGp: 5,
    weightLb: 9,
    hp: 18,
    special: 'Impaling',
  },
  {
    name: 'Trident',
    class: 'Large',
    skill: 'Piercing Weapons',
    damageType: 'P',
    damage: '1d8',
    addDamageModifier: true,
    hands: '1h',
    str: 9,
    dex: 7,
    range: "10'/0",
    costGp: 15,
    weightLb: 4,
    hp: 18,
    special: 'Impaling',
  },
  {
    name: 'Warhammer',
    class: 'Large',
    skill: 'Bludgeoning Weapons',
    damageType: 'B',
    damage: '1d8',
    addDamageModifier: true,
    hands: '1h',
    str: 11,
    dex: 9,
    range: "5'/0",
    costGp: 12,
    weightLb: 5,
    hp: 20,
    special: 'Crushing',
  },
  {
    name: 'Greataxe',
    class: 'Large',
    skill: 'Slashing Weapons',
    damageType: 'S',
    damage: '2d8',
    addDamageModifier: true,
    hands: '2h',
    str: 11,
    dex: 9,
    range: "5'/0",
    costGp: 20,
    weightLb: 12,
    hp: 20,
    special: 'Bleeding',
  },
  {
    name: 'Great sword',
    class: 'Large',
    skill: 'Slashing Weapons',
    damageType: 'S',
    damage: '2d8',
    addDamageModifier: true,
    hands: '2h',
    str: 14,
    dex: 13,
    range: "5'/0",
    costGp: 25,
    weightLb: 8,
    hp: 18,
    special: 'Bleeding',
  },
  {
    // data note: table Skill column reads "P / S" (dual type); primary letter
    // P encoded as the governing skill/damageType, alternate noted in special.
    name: 'Halberd',
    class: 'Large',
    skill: 'Piercing Weapons',
    damageType: 'P',
    damage: '2d6',
    addDamageModifier: true,
    hands: '2h',
    str: 13,
    dex: 9,
    range: "10'/0",
    costGp: 10,
    weightLb: 12,
    hp: 25,
    special: 'Bleeding or Impaling (P/S dual type)',
  },
  {
    name: 'Sword staff',
    class: 'Large',
    skill: 'Slashing Weapons',
    damageType: 'S',
    damage: '2d6',
    addDamageModifier: true,
    hands: '2h',
    str: 10,
    dex: 7,
    range: "10'/0",
    costGp: 20,
    weightLb: 7,
    hp: 20,
    special: 'Bleeding',
  },
  {
    name: 'Whip, iron chain',
    class: 'Large',
    skill: 'Slashing Weapons',
    damageType: 'S',
    damage: '1d6',
    addDamageModifier: true,
    hands: '1h',
    str: 11,
    dex: 12,
    range: "10'/0",
    costGp: 15,
    weightLb: 3,
    hp: 20,
    special: 'Entangle',
  },

  // --- Ranged Weapons ---
  // data note: the ranged table has no 1h/2h column; hands assigned by
  // convention (thrown/sling/hand crossbow = 1h, bows and other crossbows = 2h).
  {
    name: 'Bolas',
    class: 'Ranged',
    skill: 'Throw',
    damage: '1d3',
    addDamageModifier: false,
    hands: '1h',
    str: 7,
    dex: 7,
    range: "30'/50'",
    costGp: 5,
    weightLb: 2,
    hp: 5,
    special: 'Entangle',
  },
  {
    name: 'Axe, Throwing',
    class: 'Ranged',
    skill: 'Throw',
    damage: '1d6',
    addDamageModifier: true,
    hands: '1h',
    str: 7,
    dex: 7,
    range: "5'/30'",
    costGp: 4,
    weightLb: 1,
    hp: 5,
    special: 'Slashing',
  },
  {
    name: 'Sling',
    class: 'Ranged',
    skill: 'Ranged Weapons',
    damage: '1d4',
    addDamageModifier: true,
    hands: '1h',
    str: 7,
    dex: 7,
    range: "50'/100'",
    costGp: 0.2, // 2 sp
    weightLb: 0,
    hp: 5,
    special: 'Crushing',
  },
  {
    name: 'Crossbow, hand',
    class: 'Ranged',
    skill: 'Ranged Weapons',
    damage: '1d4+1',
    addDamageModifier: false,
    hands: '1h',
    str: 9,
    dex: 7,
    range: "30'/120'",
    costGp: 100, // data note: suspect — pricier than the heavy crossbow; encoded as printed
    weightLb: 2,
    hp: 10,
    special: 'Impaling',
  },
  {
    name: 'Crossbow, Heavy',
    class: 'Ranged',
    skill: 'Ranged Weapons',
    damage: '2d4+1',
    addDamageModifier: false,
    hands: '2h',
    str: 11,
    dex: 7,
    range: "100'/300'",
    costGp: 45,
    weightLb: 8,
    hp: 14,
    special: 'Impaling',
  },
  {
    name: 'Crossbow, Light',
    class: 'Ranged',
    skill: 'Ranged Weapons',
    damage: '1d6+1',
    addDamageModifier: false,
    hands: '2h',
    str: 8,
    dex: 6,
    range: "60'/200'",
    costGp: 25,
    weightLb: 4,
    hp: 10,
    special: 'Impaling',
  },
  {
    name: 'Shortbow',
    class: 'Ranged',
    skill: 'Ranged Weapons',
    damage: '1d6',
    addDamageModifier: true,
    hands: '2h',
    str: 9,
    dex: 7,
    range: "65'/300'",
    costGp: 30,
    weightLb: 2,
    hp: 10,
    special: 'Impaling',
  },
  {
    name: 'Shortbow, Recurve',
    class: 'Ranged',
    skill: 'Ranged Weapons',
    damage: '1d6+2',
    addDamageModifier: true,
    hands: '2h',
    str: 11,
    dex: 7,
    range: "75'/325'",
    costGp: 60,
    weightLb: 2,
    hp: 10,
    special: 'Impaling',
  },
  {
    name: 'Longbow',
    class: 'Ranged',
    skill: 'Ranged Weapons',
    damage: '1d8',
    addDamageModifier: true,
    hands: '2h',
    str: 11,
    dex: 9,
    range: "110'/400'",
    costGp: 75,
    weightLb: 3,
    hp: 10,
    special: 'Impaling',
  },
  {
    name: 'Longbow, Heavy',
    class: 'Ranged',
    skill: 'Ranged Weapons',
    damage: '1d8+3',
    addDamageModifier: true,
    hands: '2h',
    str: 13,
    dex: 9,
    range: "150'/500'",
    costGp: 150,
    weightLb: 4,
    hp: 10,
    special: 'Impaling',
  },
  {
    name: 'Net',
    class: 'Ranged',
    skill: 'Throw',
    damage: '0', // table prints '—': no damage, entangle only
    addDamageModifier: false,
    hands: '1h',
    str: 5,
    dex: 5,
    range: "15'/25'",
    costGp: 15,
    weightLb: 2,
    hp: null, // data note: HP cell blank in the table
    special: 'Entangle',
  },
];

// ---------------------------------------------------------------------------
// B) Armor
// ---------------------------------------------------------------------------

export const ARMOR: Armor[] = [
  // --- Light Armor ---
  { name: 'Clothing, Heavy', av: 1, costGp: 5, weightLb: 10, skillPenalty: 'None', fitsSiz: 3 },
  { name: 'Hide', av: 1, costGp: 4, weightLb: 12, skillPenalty: 'None', fitsSiz: 3 },
  { name: 'Leather, Soft', av: 1, costGp: 7, weightLb: 15, skillPenalty: 'None', fitsSiz: 2 },
  { name: 'Leather, Hard', av: 2, costGp: 15, weightLb: 15, skillPenalty: '-5% to Physical', fitsSiz: 1 },
  {
    name: 'Studded leather',
    av: 3,
    costGp: 25,
    weightLb: 20,
    skillPenalty: '-10% to Physical, -5% to Spellcraft',
    fitsSiz: 1,
  },
  {
    name: 'Chain shirt',
    av: 4,
    costGp: 100,
    weightLb: 25,
    skillPenalty: '-15% to Physical, -10% to Spellcraft',
    fitsSiz: 1,
  },
  // --- Medium Armor ---
  {
    name: 'Ring mail',
    av: 5,
    costGp: 60,
    weightLb: 30,
    skillPenalty: "-15% to Physical, -10% to Dexterous, -15% to Spellcraft, -5' Speed",
    fitsSiz: 1,
  },
  {
    name: 'Scale mail',
    av: 5,
    costGp: 80,
    weightLb: 35,
    skillPenalty: "-15% to Physical, -5% to Dexterous, -15% to Spellcraft, -5' Speed",
    fitsSiz: 1,
  },
  {
    name: 'Chainmail',
    av: 6,
    costGp: 150,
    weightLb: 40,
    skillPenalty: "-20% to Physical, -10% to Dexterous, -20% to Spellcraft, -5' Speed",
    fitsSiz: -2, // data note: negative fitsSiz as printed; semantics pending Mike
  },
  {
    name: 'Breastplate',
    av: 5,
    costGp: 200,
    weightLb: 30,
    skillPenalty: "-15% to Physical, -10% to Dexterous, -15% to Spellcraft, -5' Speed",
    fitsSiz: -1, // data note: negative fitsSiz as printed; semantics pending Mike
  },
  // --- Heavy Armor ---
  {
    name: 'Half-plate',
    av: 7,
    costGp: 600,
    weightLb: 50,
    skillPenalty: "-20% to Physical, -15% to Dexterous, -25% to Spellcraft, -10' Speed",
    fitsSiz: -1, // data note: negative fitsSiz as printed; semantics pending Mike
  },
  {
    name: 'Full plate',
    av: 8,
    costGp: 1500,
    weightLb: 60,
    skillPenalty: "-25% to Physical, -15% to Dexterous, -30% to Spellcraft, -10' Speed",
    fitsSiz: -1, // data note: negative fitsSiz as printed; semantics pending Mike
  },
];

// ---------------------------------------------------------------------------
// C) Gear — adventuring goods, tools & kits, clothing, light sources,
//    alchemical substances. (Clothing and light sources appear inside the
//    main Goods table in the doc; only "Adventurer's clothing" of the
//    clothing names exists.)
// ---------------------------------------------------------------------------

export const GEAR: GearItem[] = [
  // --- Adventuring goods (incl. clothing and light sources) ---
  { name: "Adventurer's clothing", costGp: 1, weightLb: 2, note: 'Simple clothing for those who travel.' },
  { name: 'Animal glue', costGp: 0.5, weightLb: 0.2 },
  { name: 'Astrolabe', costGp: 100, weightLb: 6, note: '+5% to Skill checks involving navigation while seafaring.' },
  { name: 'Backpack (empty)', costGp: 2, weightLb: 2 },
  {
    // errata #34 exception: 40 gp kept as printed (vs formula 8 gp) — may be an
    // intentional special item, per Mike's note.
    name: 'Backpack, mastercraft',
    costGp: 40,
    weightLb: 4,
    note: 'Carry an extra 20 lbs without affecting encumbrance.',
  },
  { name: 'Bedroll', costGp: 0.1, weightLb: 5 },
  { name: 'Blanket, winter', costGp: 0.5, weightLb: 3 },
  { name: 'Belt pouch', costGp: 1, weightLb: 0.2 },
  { name: 'Bottle', costGp: 2, weightLb: 1 },
  {
    name: 'Caltrops',
    costGp: 0.5,
    weightLb: 1,
    note: '1d4 damage to anything moving over them; DC20 Awareness to spot.',
  },
  { name: 'Candle', costGp: 0.01, weightLb: null, note: "Lights a 10' x 10' space." },
  { name: 'Case, map or scroll', costGp: 1, weightLb: 0.5 },
  { name: 'Cauldron', costGp: 1, weightLb: 5 },
  { name: "Chain (10')", costGp: 30, weightLb: 2 },
  { name: 'Chalk', costGp: 0.01, weightLb: null },
  { name: 'Chest, small', costGp: 2, weightLb: 25 },
  { name: 'Chest, large', costGp: 10, weightLb: 100 },
  { name: 'Cloak', costGp: 2, weightLb: 2 },
  { name: 'Cloak, leather', costGp: 10, weightLb: 5, note: 'Prevents damage from acid rain.' },
  { name: 'Compass', costGp: 80, weightLb: 1, note: '+5 to Navigation skill while using one.' },
  {
    name: 'Creature Compendium',
    costGp: 25,
    weightLb: 2,
    note: '+10% to Knowledge checks about creatures and monsters.',
  },
  { name: 'Crowbar', costGp: 2, weightLb: 5, note: '+10% to STR checks when prying open objects.' },
  { name: 'Fishing kit', costGp: 0.5, weightLb: 3, note: '+5% to Survival checks gathering food near water.' },
  { name: 'Flint and steel', costGp: 1, weightLb: null },
  { name: 'Grappling hook', costGp: 1, weightLb: 4, note: 'Attached to a rope for climbing; use Throw skill.' },
  { name: 'Hammer', costGp: 0.5, weightLb: 2 },
  { name: 'Hammock', costGp: 0.1, weightLb: 3 },
  { name: 'Ink and quill', costGp: 8, weightLb: null },
  { name: 'Iron spike', costGp: 0.05, weightLb: 1 },
  { name: 'Journal', costGp: 10, weightLb: 1 },
  { name: 'Ladder', costGp: 1, weightLb: 20, note: '+30% bonus to climbing.' },
  {
    name: 'Lamp',
    costGp: 0.5,
    weightLb: 1,
    note: "Oil-fueled; illuminates 30' x 30'. Fragile — meant to be stationary.",
  },
  { name: 'Lantern', costGp: 1, weightLb: 1, note: "Oil-fueled; easily carried; illuminates 30' x 30'." },
  { name: 'Lantern, bullseye', costGp: 12, weightLb: 3, note: "Lights a 50' cone from the bearer." },
  { name: 'Lantern, hooded', costGp: 7, weightLb: 2, note: 'Sliding plates allow the light to be hidden at will.' },
  {
    name: 'Lock (very simple)',
    costGp: 20,
    weightLb: 1,
    note: 'Open (Fine Manipulation): Easy; Break (Athletics): Easy; 10 HP.',
  },
  {
    name: 'Lock (average)',
    costGp: 40,
    weightLb: 1,
    note: 'Open (Fine Manipulation): Standard; Break (Athletics): Standard; 20 HP.',
  },
  {
    name: 'Lock (very good)',
    costGp: 80,
    weightLb: 1,
    note: 'Open (Fine Manipulation): Difficult; Break (Athletics): Difficult; 30 HP.',
  },
  {
    name: 'Magnifying glass',
    costGp: 100,
    weightLb: null,
    note: '+5% to Awareness checks while searching for small details.',
  },
  { name: 'Manacles', costGp: 15, weightLb: 2, note: 'Iron or steel cuffs; require a lock.' },
  {
    name: 'Map, local',
    costGp: 15,
    weightLb: null,
    note: '+5% to Skill checks involving geography, landmarks, or navigation of the mapped area.',
  },
  {
    name: 'Map, world',
    costGp: 35,
    weightLb: null,
    note: '+5% to Skill checks involving geography, landmarks, or navigation of the mapped area.',
  },
  { name: 'Mirror, small steel', costGp: 10, weightLb: 0.5 },
  { name: 'Mug', costGp: 0.2, weightLb: 1 },
  { name: 'Oil (1 pint)', costGp: 0.5, weightLb: 1, note: 'Fuel for lamps and lanterns.' },
  { name: 'Paper', costGp: 0.1, weightLb: null },
  {
    name: 'Piton',
    costGp: 0.1,
    weightLb: 0.5,
    note: 'Climb without risk of falling damage; one piton per 10 ft on average.',
  },
  { name: 'Pot', costGp: 0.8, weightLb: 4 },
  { name: 'Rations, trail (per day)', costGp: 0.5, weightLb: 1, note: 'Food for one person for one day.' },
  { name: "Rope, hemp (50')", costGp: 1, weightLb: 10, note: '+20% to climbing when securely attached.' },
  { name: "Rope, silk (50')", costGp: 10, weightLb: 5, note: '+20% to climbing when securely attached.' },
  { name: 'Sack (empty)', costGp: 0.1, weightLb: 0.5 },
  { name: 'Salt (1lb)', costGp: 5, weightLb: 1 },
  { name: 'Saw', costGp: 0.4, weightLb: 2 },
  { name: 'Sewing kit', costGp: 1, weightLb: 1 },
  { name: 'Signet ring', costGp: 5, weightLb: null },
  { name: 'Shovel', costGp: 2, weightLb: 8 },
  { name: 'Sledgehammer', costGp: 1, weightLb: 10 },
  {
    name: 'Spyglass',
    costGp: 100,
    weightLb: 1,
    note: '+5% to any Skill check used to spot or search at a distance.',
  },
  { name: 'Tent, small', costGp: 10, weightLb: 20 },
  { name: 'Tent, medium', costGp: 15, weightLb: 30 },
  { name: 'Tent, large', costGp: 30, weightLb: 40 },
  { name: 'Tent, pavilion', costGp: 100, weightLb: 50 },
  {
    name: 'Tent, leather (upgrade)',
    costGp: null, // priced as +20% of base tent cost, not a flat amount
    weightLb: null, // +20% of base tent weight
    note: '+20% base tent cost and weight; resists damage from the strange weather of Atheles.',
  },
  { name: 'Torch', costGp: 0.1, weightLb: 1, note: "Burns 1 hour; illuminates a 20' radius." },
  { name: 'Twine (50 ft)', costGp: 0.01, weightLb: 0.5 },
  { name: 'Vial, Glass', costGp: 1, weightLb: 0.2 },
  { name: 'Waterskin', costGp: 1, weightLb: 4 },
  { name: 'Whetstone', costGp: 0.02, weightLb: 1 },

  // --- Tools and Kits ---
  {
    name: "Climber's kit",
    costGp: 80,
    weightLb: 5,
    note: '+10% to Climb checks involving climbing or rappelling; 10 uses.',
  },
  {
    name: "Climber's kit (Mastercraft)",
    costGp: 320,
    weightLb: 5,
    note: '+20% to Climb checks involving climbing or rappelling; 10 uses.',
  },
  { name: 'Cooking kit', costGp: 3, weightLb: 16, note: 'Allows cooking special meals during travel.' },
  { name: "Healer's kit", costGp: 50, weightLb: 1, note: '+10% to First Aid checks; 10 uses.' },
  {
    name: "Healer's kit (Mastercraft)",
    costGp: 200, // errata #34: 4x base cost rule; doc table shows old price (100 gp)
    weightLb: 1,
    note: '+20% to First Aid checks; 10 uses.',
  },
  {
    name: "Leatherworker's Repair Kit",
    costGp: 1,
    weightLb: 1,
    note: 'Repair leather items on the road; single use.',
  },
  { name: 'Musical instrument', costGp: 5, weightLb: null, note: 'Weight varies 1-8 lb. No bonuses unless SG deems otherwise.' },
  {
    name: 'Musical instrument (Mastercraft)',
    costGp: 20, // errata #34: 4x base cost rule; doc table shows old price (100 gp)
    weightLb: null,
    note: 'Weight varies 1-8 lb.',
  },
  { name: "Smith's Repair Kit", costGp: 5, weightLb: 2, note: 'Repair metal items on the road; single use.' },
  {
    name: "Thieves' tools",
    costGp: 30,
    weightLb: 1,
    note: '+5% to Fine Manipulation when disabling traps and picking locks.',
  },
  {
    name: "Thieves' tools (Mastercraft)",
    costGp: 120, // errata #34: 4x base cost rule; doc table shows old price (100 gp)
    weightLb: 2,
    note: '+10% to Fine Manipulation when disabling traps and picking locks.',
  },
  { name: "Tinker's kit", costGp: 100, weightLb: 3, note: 'Allows creating and setting traps.' },
  {
    name: "Woodworker's Repair Kit",
    costGp: 1,
    weightLb: 1,
    note: 'Repair or work on wooden items on the road; single use.',
  },

  // --- Alchemical Substances ---
  {
    name: 'Acid, Weak',
    costGp: 10,
    weightLb: 1,
    note: "1d4 or 1 AV for 1 round; splash weapon (Throw, 20' range), 1 acid damage within 5'.",
  },
  {
    name: 'Acid, Standard',
    costGp: 15,
    weightLb: 1,
    note: "1d6+1 or 1 AV for 3 rounds; splash weapon (Throw, 20' range), 1 acid damage within 5'.",
  },
  {
    name: 'Acid, Strong',
    costGp: 20,
    weightLb: 1,
    note: "1d10+1 or 1 AV for 10 rounds; splash weapon (Throw, 20' range), 1 acid damage within 5'.",
  },
  {
    // errata #35: table fixed to 1d6+2 elemental damage
    name: "Alchemist's Fire",
    costGp: 20,
    weightLb: 1,
    note: "1d6+2 fire elemental damage, 5' splash; direct hit bypasses AV and sets target on fire (Throw, 20' range).",
  },
  { name: 'Antacid', costGp: 5, weightLb: 1, note: 'Negates acid for 1d6+1 rounds; standard action to apply.' },
  { name: 'Antitoxin', costGp: 50, weightLb: null, note: 'Drink for +40% to a save vs. poison.' },
  {
    name: 'Black Rock',
    costGp: 40,
    weightLb: 0.0625, // 1 oz
    note: '1d8 explosive damage per ounce; highly volatile — a natural 1 detonates it on the user.',
  },
  {
    name: 'Firebane',
    costGp: 50,
    weightLb: 1,
    note: "Quenches natural fires in a 5'x5' space (up to SIZ 20); standard or move action.",
  },
  { name: 'Healing Salve', costGp: 30, weightLb: 1, note: 'Heals target 1d4+2; standard action to apply.' },
  {
    name: 'Smokestick',
    costGp: 20,
    weightLb: 0.5,
    note: 'Creates opaque smoke filling a 10 ft cube; stick consumed after 1 round, smoke lasts 3 minutes.',
  },
  {
    name: 'Totem Bag (1 use)',
    costGp: 45,
    weightLb: 1.2,
    note: '+10 to saves versus magic when imbibed; lasts 3 minutes.',
  },
  {
    name: 'Universal Solvent',
    costGp: 25,
    weightLb: null,
    note: 'Dissolves most glues; frees 1 person from anything sticky, including webs or spells.',
  },
];

// ---------------------------------------------------------------------------
// D) Shields
// ---------------------------------------------------------------------------

export const SHIELDS: Shield[] = [
  {
    name: 'Buckler',
    parryBase: 15,
    av: 1,
    hp: 15,
    damage: '1d2/Knockback',
    str: 5,
    dex: 7,
    costGp: 1,
    weightLb: 2,
    special:
      'Worn on belt or strapped to the arm, leaving both hands free: may still use two-handed ranged weapons, two-handed swords, and dual weapons.',
  },
  {
    name: 'Shield, light wooden',
    parryBase: 15,
    av: 2,
    hp: 18,
    damage: '1d2/Knockback',
    str: 8,
    dex: 8,
    costGp: 3,
    weightLb: 5,
    special: 'Wood does not rust (but can catch fire).',
  },
  {
    name: 'Shield, light steel',
    parryBase: 15,
    av: 2,
    hp: 20,
    damage: '1d2/Knockback',
    str: 9,
    dex: 9,
    costGp: 12,
    weightLb: 6,
    special: 'Steel cannot catch fire (but can rust).',
  },
  {
    name: 'Shield, heavy wooden',
    parryBase: 30,
    av: 3,
    hp: 20,
    damage: '1d2/Knockback',
    str: 10,
    dex: 8,
    costGp: 7,
    weightLb: 10,
    special: 'Wood does not rust (but can catch fire).',
  },
  {
    name: 'Shield, heavy steel',
    parryBase: 30,
    av: 3,
    hp: 22,
    damage: '1d2/Knockback',
    str: 11,
    dex: 9,
    costGp: 25,
    weightLb: 15,
    special: 'Steel cannot catch fire (but can rust).',
  },
  {
    name: 'Shield, spiked',
    parryBase: 15,
    av: 3,
    hp: 20,
    damage: '1d6+dm, Impaling', // only shield whose damage adds the damage modifier
    str: 9,
    dex: 9,
    costGp: 30,
    weightLb: 15,
  },
  {
    name: 'Shield, tower',
    parryBase: 45,
    av: 3,
    hp: 26,
    damage: 'Knockback', // Dmg/Special column prints "Knockback, Can be set*" — no damage dice
    skillMod: "-5% to Dexterous, -5' to Speed",
    str: 12,
    dex: 8,
    costGp: 50,
    weightLb: 45,
    special:
      'Can be set in the ground (move or standard action) to provide directional Cover; withdrawn as a free action.',
  },
];

// ---------------------------------------------------------------------------
// E) Ammunition — doc footnote: quantity in parentheses is the standard
//    production lot for the listed base cost. Type column (P/B) and Special
//    column encoded in `note`.
// ---------------------------------------------------------------------------

export const AMMUNITION: GearItem[] = [
  { name: 'Arrows or bolts (20)', costGp: 1, weightLb: 2, note: 'Type: P.' },
  { name: 'Bullets, sling (10)', costGp: 0.1, weightLb: 3, note: 'Type: B.' }, // 1 sp
  { name: 'Silver arrow or bolt (10)', costGp: 5, weightLb: 3, note: 'Type: P.' },
  {
    name: 'Cold iron arrows or bolts (10)',
    costGp: 2,
    weightLb: 5,
    note: 'Type: P. +1d4 damage to creatures with cold iron weakness.',
  },
  {
    name: 'Barbed arrows or bolts (10)',
    costGp: 5,
    weightLb: 6,
    note: 'Type: P. Requires a successful Effort or First Aid check to remove; failure inflicts 1d4 damage and still removes the arrow.',
  },
  {
    name: 'Aradan steel arrows or bolts (10)',
    costGp: 10,
    weightLb: 1,
    note: 'Type: P. +1d4 damage to creatures with Aradan steel weakness.',
  },
  {
    name: 'Amarnium arrows or bolts (10)',
    costGp: 20,
    weightLb: 0.5,
    note: 'Type: P. Lightweight.',
  },
  {
    name: 'Tritium arrows or bolts (10)',
    costGp: 60,
    weightLb: 2,
    note: 'Type: P. Can crit against tritium-armored targets.',
  },
  {
    // data note: this row and the rest below are priced per single arrow/bolt
    // (no quantity printed), unlike the lot-priced rows above.
    name: 'Alchemist fire arrow or bolt',
    costGp: 10,
    weightLb: 0.5,
    note: 'Type: P. +1d6 and sets fire to flammable items.',
  },
  {
    name: 'Acid (weak) arrow or bolt',
    costGp: 6,
    weightLb: 0.5,
    note: 'Type: P. +1d4 acid (1 round).', // table prints "1 rounds"
  },
  {
    name: 'Acid (standard) arrow or bolt',
    costGp: 15,
    weightLb: 0.5,
    note: 'Type: P. +1d6+1 acid (3 rounds).',
  },
  {
    name: 'Acid (strong) arrow or bolt',
    costGp: 20,
    weightLb: 0.5,
    note: 'Type: P. +1d10+1 acid (10 rounds).',
  },
  {
    name: 'Blackrock arrow or bolt',
    costGp: 10,
    weightLb: 0.5,
    note: "Type: P. +1d8 explosion 5' (unstable — see Black Rock).",
  },
  {
    name: 'Healing salve arrow or bolt',
    costGp: 30,
    weightLb: 0.5,
    note: 'Type: P. Heals target 1d4+2.',
  },
  {
    name: 'Oil arrow or bolt',
    costGp: 1,
    weightLb: 0.5,
    note: "Type: P. Covers object and 10'x10' area in flammable oil; also makes it difficult terrain.",
  },
  {
    name: 'Snare arrow or bolt',
    costGp: 10,
    weightLb: 0.5,
    note: 'Type: P. Slows target by 1/2.',
  },
];

// ---------------------------------------------------------------------------
// F) Mounts, Pets, and Tack — doc "Mounts, Pets, and Vehicles" table.
//    Columns: Name, Speed, HP, Combat, Can Enter Dungeons*, Cost (no weight
//    column, so weightLb is omitted). Speed/HP/Combat/dungeon note encoded
//    in `note`. Saddle and animal barding are printed at the top of the doc's
//    *Vehicles* table but are tack, so they are included here.
// ---------------------------------------------------------------------------

export const MOUNTS: GearItem[] = [
  {
    name: 'Ank',
    costGp: 300,
    note: 'Speed 30 ft; HP 37; Bite 60% melee (1d8+4); can enter dungeons.',
  },
  {
    name: 'Dog, guard',
    costGp: 25,
    note: 'Speed 40 ft; HP 6; attack 55% (1d4+1); can enter dungeons.',
  },
  {
    name: 'Donkey',
    costGp: 8,
    note: 'Speed 30 ft; HP 11; attack 40% (1d2); can enter dungeons.',
  },
  {
    name: 'Horse, heavy',
    costGp: 200,
    note: 'Speed 50 ft; HP 19; (2) attacks 50% (1d8); will not enter dungeons.',
  },
  {
    name: 'Horse, light',
    costGp: 75,
    note: 'Speed 60 ft; HP 15; (2) attacks 50% (1d6); will not enter dungeons.',
  },
  {
    name: 'Orillot',
    costGp: 1000,
    note: 'Speed 30 ft; HP 85; Gore 80% (2d6+10) or slam 75% (2d8+10); will not enter dungeons.',
  },
  {
    name: 'Pony',
    costGp: 30,
    note: 'Speed 40 ft; HP 13; attack 45% (1d4); will not enter dungeons.',
  },
  {
    name: 'Sarap',
    costGp: 600,
    note: 'Speed 60 ft; HP 38; 2 talons 60% (2d6+9) and bite 60% (1d8+9); will not enter dungeons.',
  },
  {
    name: 'Thundrom',
    costGp: 350,
    note: 'Speed 50 ft; HP 19; Bite 65% (1d6+5) and slam 65% (1d8+2); will not enter dungeons.',
  },
  {
    name: 'Warhorse, heavy',
    costGp: 400,
    note: 'Speed 40 ft; HP 30; (2) hooves 65% (1d8+4); will not enter dungeons.',
  },
  {
    name: 'Warhorse, light',
    costGp: 150,
    note: 'Speed 50 ft; HP 24; (2) hooves 65% (1d6+3); will not enter dungeons.',
  },
  // --- Tack & harness (printed under the doc's "Vehicles" table) ---
  { name: 'Saddle', costGp: 15 },
  {
    name: 'Animal armor/barding',
    costGp: null, // formula price, not a flat amount
    note: 'Costs the same as character armor x2; unusual creatures x4.',
  },
];

// ---------------------------------------------------------------------------
// G) Vehicles — doc "Vehicles" table (land vehicles + "Ships" subsection).
//    The table prints name and cost only: no weight, speed, or capacity
//    columns, so those fields are omitted.
// ---------------------------------------------------------------------------

export const VEHICLES: GearItem[] = [
  // --- Land ---
  { name: 'Cart', costGp: 15 },
  { name: 'Wagon, covered', costGp: 25 },
  { name: 'Wagon, elaborate', costGp: 35 },
  { name: 'Wagon, caravan', costGp: 400 },
  { name: 'Wagon, giant caravan', costGp: 1000 },
  // --- Ships ---
  { name: 'Rowboat', costGp: 50 },
  { name: 'Cog', costGp: 3000 },
  { name: 'Longship', costGp: 10000 },
  { name: 'Galleon', costGp: 30000 },
  { name: 'Warship', costGp: 65000 },
];

// ---------------------------------------------------------------------------
// H) Siege Weapons — doc table columns: Weapon, Range, Damage, Space/Tonnage,
//    HP, Can be turret mounted, Rate of Fire per full round, Quick Reload DC,
//    # Personnel Min/Max, Price. All siege weapons bypass AV (doc footnote).
//    Encoded as GearItem (the crewed-artillery stat line does not fit the
//    personal Weapon interface); full stat line in `note`.
// ---------------------------------------------------------------------------

export const SIEGE_WEAPONS: GearItem[] = [
  {
    name: 'Light ballista',
    costGp: 400,
    note: "Range 240'; damage 2d6 (bypasses AV); space/tonnage 10x5 / 1/4; HP 15; rate of fire 1/2; quick reload DC 13; personnel 1/2.",
  },
  {
    name: 'Medium ballista',
    costGp: 600,
    note: "Range 160'; damage 3d6 (bypasses AV); space/tonnage 10x10 / 2; HP 20; rate of fire 1/3; quick reload DC 27; personnel 2/3.",
  },
  {
    // data note: suspect — the heavy ballista's printed range (80') is shorter
    // than the light (240') and medium (160'); encoded as printed.
    name: 'Heavy ballista',
    costGp: 800,
    note: "Range 80'; damage 4d6 (bypasses AV); space/tonnage 15x15 / 3; HP 35; can be turret mounted; rate of fire 1/4; quick reload DC 57; personnel 4/5.",
  },
  {
    name: 'Light catapult',
    costGp: 500,
    note: "Range 100'-200'; damage 3d6 (bypasses AV); space/tonnage 10x5 / 1; HP 20; rate of fire 1/5; quick reload DC 13; personnel 1/2.",
  },
  {
    name: 'Medium catapult',
    costGp: 700,
    note: "Range 100'-200'; damage 4d6 (bypasses AV); space/tonnage 10x10 / 2; HP 30; rate of fire 1/6; quick reload DC 32; personnel 3/4.",
  },
  {
    name: 'Heavy catapult',
    costGp: 1000,
    note: "Range 100'-200'; damage 5d6 (bypasses AV); space/tonnage 15x15 / 3; HP 40; can be turret mounted; rate of fire 1/8; quick reload DC 72; personnel 5/5.",
  },
  {
    // data note: the two Turret rows print their size ("Small"/"Med") in the
    // Range column; damage, HP, RoF, reload, and personnel cells are blank.
    name: 'Turret, small',
    costGp: 1000,
    note: 'Size Small (printed in Range column); space/tonnage 15x15 / 1; all other combat cells blank in the table.',
  },
  {
    name: 'Turret, medium',
    costGp: 2000,
    note: 'Size Med (printed in Range column); space/tonnage 20x20 / 1; all other combat cells blank in the table.',
  },
];

// Deferred: poisons and inn goods/services are NOT encoded here (out of scope
// for this pass; see 005 doc for their tables). Shields, ammunition,
// mounts/pets/tack, vehicles/ships, and siege weapons are now encoded above
// (sections D-H).
