/**
 * SagaBorn D100 — Professions (Profession Lifepath)
 *
 * Sources:
 *  - /home/claude/d100srd-rules-v2/002-creating-a-character.md (Profession
 *    Lifepath d100 table + the 30 detailed profession entries), doc pull 2026-07-14
 *  - /home/claude/errata-2026-07-13.md (Mike's rulings, 7-13-2026)
 *
 * RULE OF PRECEDENCE: the errata WINS over chapter text on any conflict.
 *
 * Errata applied here: #9 / Part 2 (Mystic added to profession chart: 96,
 * Very Rare, Mage — confirmed 7-14), exec summary #3 (Persuasion is always
 * Persuade; Knowledge Arcana; Pilot specialties Air/Land/Sea), Part 2
 * (profession rarity matched to chart; Gambler 12d4 funds intentional;
 * Noble lost Literacy, got Appraise — printed skill list already reflects it),
 * #33 (starter packages: always soft leather; small weapons = light weapons).
 *
 * d100 ranges transcribed exactly from the rebuilt table (tiles 1-100).
 * Skill names normalized to canonical SKILLS keys (Persuade, Medicine,
 * Craft, Siege Weapon, ...); "(Any)" melee grants use choiceOfGroup per
 * errata #12 (umbrellas are skill GROUPS).
 */

import { Profession } from './types';

export const PROFESSIONS: Profession[] = [
  {
    name: 'Crafter',
    description: 'Whether a village blacksmith, a glassblower, or a maker of finely tuned watches, you make trade goods by hand and sell them to interested buyers. You usually work in a shop, whether you own it or are merely employed…',
    d100: [1, 4],
    rarity: 'Very Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Appraise' },
      { skill: 'Art' },
      { skill: 'Bargain' },
      { skill: 'Craft', specialty: 'Any' }, // "any two Craft skills" — first pick
      { skill: 'Craft', specialty: 'Any' }, // "any two Craft skills" — second pick
      { skill: 'Fine Manipulation' },
      { skill: 'Persuade' },
      { skill: 'Spot' },
      { skill: 'Repair' },
      { skill: 'Research' },
    ],
    equipment: ['basic clothing', 'tools of the trade (but not a workshop)'],
    funds: '1d4x10+20',
    contacts: 0,
    talentPaths: ['Factor', 'Luminar'],
  },
  {
    name: 'Farmer',
    description: 'As a farmer, you dwell in a rural or barely tamed area, coaxing a living out of the land through growing crops or tending animal herds. It is a hard life with long days of backbreaking labor, but nonetheless satisfying.',
    d100: [5, 8],
    rarity: 'Very Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Bargain' },
      { skill: 'Craft' },
      { skill: 'First Aid' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { skill: 'Repair' },
      { skill: 'Ranged Weapons' },
      { skill: 'Ride' },
      { skill: 'Spot' },
      { skill: 'Track' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+5',
    contacts: 0,
    talentPaths: ['Fighter', 'Ranger'],
  },
  {
    name: 'Herder',
    description: 'You make your living tending herd animals, riding the open range and taking care of the herds, finding strays, and bringing them to market when it is time to sell.',
    d100: [9, 12],
    rarity: 'Very Common',
    archetype: 'Expert', // table also suggests Warrior
    skills: [
      { skill: 'Craft' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { skill: 'Navigate' },
      { skill: 'Ranged Weapons' },
      { skill: 'Ride' },
      { skill: 'Spot' },
      { skill: 'Survival' },
      { skill: 'Throw' },
      { skill: 'Track' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+5',
    contacts: 0,
    talentPaths: ['Fighter', 'Ranger'],
  },
  {
    name: 'Hunter',
    description: 'Whether for survival or for the thrill of the hunt, you specialize in tracking and either trapping or killing wild animals or other beings.',
    d100: [13, 23],
    rarity: 'Very Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Climb' },
      { skill: 'Hide' },
      { skill: 'Listen' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Navigate' },
      { skill: 'Ranged Weapons' },
      { skill: 'Spot' },
      { skill: 'Stealth' },
      { skill: 'Survival' },
      { skill: 'Track' },
    ],
    equipment: [
      'basic clothing',
      'Shortbow', // data note: printed as "a short bow"; normalized to the catalog weapon name
      'a light weapon',
    ],
    funds: '1d4x5+5',
    contacts: 0,
    talentPaths: ['Ranger'],
  },
  {
    name: 'Laborer',
    description: 'You are a worker, whether in a shop, in a warehouse, or simply heavy labor. Your muscle and ability to do repetitive tasks are more important than any brainpower you can muster.',
    d100: [24, 36],
    rarity: 'Very Common',
    archetype: 'Expert', // table also suggests Warrior
    skills: [
      { skill: 'Athletics' },
      { skill: 'Climb' },
      { skill: 'Craft' },
      { skill: 'Brawl' },
      { skill: 'Fine Manipulation' },
      { skill: 'Grapple' },
      { skill: 'Listen' },
      { skill: 'Repair' },
      { skill: 'Sense' },
      { skill: 'Spot' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+5',
    contacts: 0,
    talentPaths: [], // recommended paths: "Any"
  },
  {
    name: 'Servant',
    description: 'You are employed as a helper or servant, tending to the household affairs and domestic needs of an affluent employer. You might be a gentleman’s manservant, the adjutant of a general, or you could be a scullery maid…',
    d100: [37, 42],
    rarity: 'Very Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Craft' },
      { skill: 'Etiquette' },
      { skill: 'Fine Manipulation' },
      { skill: 'First Aid' },
      { skill: 'Hide' },
      { skill: 'Insight' },
      { skill: 'Listen' },
      { skill: 'Knowledge' },
      { skill: 'Persuade' },
      { skill: 'Stealth' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+10', // doc: "Funds (can vary): 1d4 x 10 + 10 gp (average)"
    contacts: 0,
    talentPaths: ['Factor'],
  },
  {
    name: 'Soldier',
    description: 'Whether through enlistment or conscription, you are a professional soldier, charged with the defense of your country or organization. You might be a mercenary or sellsword, or you might actually believe in the cause…',
    d100: [43, 48],
    rarity: 'Very Common',
    archetype: 'Warrior',
    skills: [
      { skill: 'Command' },
      { skill: 'Brawl' },
      { skill: 'Climb' },
      { skill: 'Dodge' },
      { skill: 'First Aid' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Ranged Weapons' },
      { skill: 'Siege Weapon' }, // printed "Siege Weapons"; canonical singular
      { skill: 'Spot' },
      { skill: 'Stealth' },
    ],
    equipment: ['basic clothing', 'soft leather armor', 'a medium weapon'],
    funds: '1d4x10+10',
    contacts: 0,
    talentPaths: ['Berserker', 'Fighter'],
  },
  {
    name: 'Warrior',
    description: 'You specialize in individual combat, surviving by your reflexes and your weapon skills. Perhaps you adhere to a code of honor like chivalry or bushido, or you are a mercenary or barbaric adventurer. Soldiers fight in…',
    d100: [49, 55],
    rarity: 'Very Common',
    archetype: 'Warrior',
    skills: [
      { skill: 'Athletics' },
      { skill: 'Brawl' },
      { skill: 'Dodge' },
      { skill: 'Grapple' },
      { skill: 'Listen' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Ranged Weapons' },
      { skill: 'Shield' },
      { skill: 'Spot' },
      { skill: 'Throw' },
    ],
    equipment: ['basic clothing', 'soft leather armor', 'a medium weapon'],
    funds: '1d4x10+10',
    contacts: 0,
    talentPaths: ['Berserker', 'Fighter'],
  },
  {
    name: 'Beggar',
    description: 'You survive by begging for money, food, and other necessities. You may call yourself a hobo, homeless, or a wandering vagabond. Perhaps you had a run of bad luck, are of a discriminated-against group, have a criminal…',
    d100: [56, 57],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Bargain' },
      { skill: 'Fast Talk' },
      { skill: 'Hide' },
      { skill: 'Insight' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { skill: 'Persuade' },
      { skill: 'Sleight of Hand' },
      { skill: 'Spot' },
      { skill: 'Stealth' },
    ],
    equipment: ['basic clothing (rough)', 'a light weapon'],
    funds: '1d3x10',
    contacts: 3,
    talentPaths: [], // recommended paths: "Any"
  },
  {
    name: 'Criminal',
    description: 'You make your way through the world by breaking the law, whether by strong-arm theft, organized crime, picking pockets, or some other means of gaining valuables or money illegally.',
    d100: [58, 61],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Appraise' },
      { skill: 'Bargain' },
      { skill: 'Fast Talk' },
      { skill: 'Fine Manipulation' },
      { skill: 'Hide' },
      { skill: 'Listen' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Persuade' },
      { skill: 'Spot' },
      { skill: 'Stealth' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+10',
    contacts: 1,
    talentPaths: [], // recommended paths: "Any"
  },
  {
    name: 'Detective',
    description: 'You use skills of observation, deduction, and criminology to investigate occurrences.',
    d100: [62, 62],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Fast Talk' },
      { skill: 'Hide' },
      { skill: 'Insight' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Persuade' },
      { skill: 'Research' },
      { skill: 'Spot' },
      { skill: 'Track' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+10',
    contacts: 2,
    talentPaths: ['Factor', 'Ranger'],
  },
  {
    name: 'Entertainer',
    description: 'You use your performing talent to entertain audiences of all sizes, whether through improvisation or scripted performances.',
    d100: [63, 65],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Acrobatics' },
      { skill: 'Art' },
      { skill: 'Disguise' },
      { skill: 'Fast Talk' },
      { skill: 'Fine Manipulation' },
      { skill: 'Insight' },
      { skill: 'Listen' },
      { skill: 'Perform' },
      { skill: 'Persuade' },
      { skill: 'Sense' },
    ],
    equipment: ['basic clothing', 'an instrument'],
    funds: '1d4x10+5',
    contacts: 1,
    talentPaths: ['Bard'],
  },
  {
    name: 'Explorer',
    description: 'You have made it your life’s work to seek out the unknown corners of the world, go where none have gone before, and bring back knowledge of what you have found, either for glory or in the name of discovery.',
    d100: [66, 69],
    rarity: 'Common',
    archetype: 'Expert', // table also suggests Warrior
    skills: [
      { skill: 'Climb' },
      { skill: 'Jump' },
      { skill: 'Navigate' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Persuade' },
      { skill: 'Research' },
      { skill: 'Ride' },
      { skill: 'Swim' },
      { skill: 'Spot' },
      { skill: 'Survival' },
    ],
    equipment: ['basic clothing', 'a medium weapon', 'a backpack'],
    funds: '1d4x10+10',
    contacts: 0,
    talentPaths: ['Fighter', 'Ranger'],
  },
  {
    name: 'Gambler',
    description: 'You survive by the whim of chance, or by cheating fate in games of luck and skill. Inevitably, you travel around; drifting from one gambling arena to another, sometimes one step ahead of the law, hoping your luck…',
    d100: [70, 72],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Bargain' },
      { skill: 'Brawl' },
      { skill: 'Dodge' },
      { skill: 'Fast Talk' },
      { skill: 'Gaming' },
      { skill: 'Insight' },
      { skill: 'Knowledge' },
      { skill: 'Persuade' },
      { skill: 'Sleight of Hand' },
      { skill: 'Spot' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '12d4', // errata Part 2: Gambler 12d4 is intentional
    contacts: 1,
    talentPaths: ['Bard', 'Factor', 'Rogue'],
  },
  {
    name: 'Lawkeeper / Guard',
    description: 'You have the authority and the jurisdiction to uphold and defend the law, ideally in defense of the common folk. Your enforcement of the law and legal code is supported by the power structure in your community.',
    d100: [73, 74],
    rarity: 'Common',
    archetype: 'Warrior',
    skills: [
      { skill: 'Brawl' },
      { skill: 'Dodge' },
      { skill: 'Fast Talk' },
      { skill: 'Grapple' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Ranged Weapons' },
      { skill: 'Spot' },
      { skill: 'Track' },
    ],
    equipment: ['basic clothing', 'a medium weapon'],
    funds: '1d4x10+5',
    contacts: 1,
    talentPaths: ['Archeon', 'Fighter'],
  },
  {
    name: 'Merchant',
    description: 'You make a living in trade, purchasing resources for less and selling for more. You might work in or own a shop, or you might be mobile: a traveling vendor, a wandering tinker, an adventuresome spice merchant, or an…',
    d100: [75, 75],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Appraise' },
      { skill: 'Bargain' },
      { skill: 'Command' },
      { skill: 'Fast Talk' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { skill: 'Persuade' },
      { skill: 'Research' },
      { skill: 'Sense' },
      { skill: 'Spot' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+20',
    contacts: 0,
    talentPaths: ['Factor'],
  },
  {
    name: 'Politician',
    description: 'You have been elected or appointed to a position of authority and make your living taking part in or directing government activities, whether city-wide or greater. You could be a medieval magistrate or a town mayor.',
    d100: [76, 76],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Bargain' },
      { skill: 'Command' },
      { skill: 'Etiquette' },
      { skill: 'Fast Talk' },
      { skill: 'Insight' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { skill: 'Perform', specialty: 'Orate' }, // data note: printed "Perform (Oratory)"; canonical Perform specialty is "Orate"
      { skill: 'Persuade' },
      { skill: 'Research' },
    ],
    equipment: ['fine clothing', 'a light weapon'],
    funds: '1d4x10+10',
    contacts: 4, // two friendly, two adversarial
    talentPaths: [], // recommended paths: "Any"
  },
  {
    name: 'Priest',
    description: 'Your faith and belief in the divine have led you to the calling of the priesthood, and you spend your time preaching or in activities befitting the worship of your deity (or deities). You could be an acetic monk or a…',
    d100: [77, 77],
    rarity: 'Common',
    archetype: 'Expert', // table also suggests Mage
    skills: [
      { skill: 'Command' },
      { skill: 'Fast Talk' },
      { skill: 'Insight' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { skill: 'Perform' },
      { skill: 'Persuade' },
      { skill: 'Research' },
      { skill: 'Sense' },
      { skill: 'Spellcraft' },
    ],
    equipment: ['basic or fine clothing'],
    funds: '1d4x10+10',
    contacts: 2,
    talentPaths: ['Luminar'],
  },
  {
    name: 'Sailor',
    description: 'You ply the ocean waves, working hard to maintain your vessel’s integrity, whether as a pirate, a naval officer, or an ancient world trader.',
    d100: [78, 78],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Climb' },
      { skill: 'Dodge' },
      { skill: 'Grapple' },
      { skill: 'Navigate' },
      { choiceOfGroup: 'melee-weapon' }, // printed "Melee Weapons (Any)"
      { skill: 'Pilot', specialty: 'Sea' },
      { skill: 'Ranged Weapons' },
      { skill: 'Repair' },
      { skill: 'Spot' },
      { skill: 'Swim' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+10',
    contacts: 0,
    talentPaths: ['Fighter', 'Rogue'],
  },
  {
    name: 'Scholar',
    description: 'Study and learning define your life, and you specialize in one or more fields of knowledge, eagerly seeking out all there is to know within your intellectual domain. You might teach this knowledge to students or…',
    d100: [79, 79],
    rarity: 'Common',
    archetype: 'Expert', // table also suggests Mage
    skills: [
      { skill: 'Appraise' },
      { skill: 'Art' },
      { skill: 'Craft' },
      { skill: 'Insight' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { skill: 'Persuade' },
      { skill: 'Research' },
      { skill: 'Spot' },
      { skill: 'Teach' },
    ],
    equipment: ['basic clothing', 'a journal', 'ink and quill'],
    funds: '1d4x5+10',
    contacts: 1,
    talentPaths: ['Bard', 'Factor', 'Luminar'],
  },
  {
    name: 'Thief',
    description: 'You take what you want, either to survive or because it appeals to you. You could be a lowly pickpocket, an infamous brigand, or a glamorous international jewel thief. You flaunt the law to steal, either armed,…',
    d100: [80, 80],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Appraise' },
      { skill: 'Climb' },
      { skill: 'Dodge' },
      { skill: 'Fast Talk' },
      { skill: 'Fine Manipulation' },
      { skill: 'Hide' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Ranged Weapons' },
      { skill: 'Spot' },
      { skill: 'Stealth' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+20',
    contacts: 1,
    talentPaths: ['Rogue'],
  },
  {
    name: 'Artist',
    description: 'You make your living through making art, whether drawing, painting, sculpture, or any other means of creative expression in various mediums.',
    d100: [81, 83],
    rarity: 'Rare',
    archetype: 'Expert',
    skills: [
      { skill: 'Art' }, // printed "Art (drawing, painting, sculpting, etc)" — examples, not a fixed specialty
      { skill: 'Craft', specialty: 'Art' }, // data note: printed "Crafting" (not a canonical skill); normalized to Craft with an Art specialty
      { skill: 'Etiquette' },
      { skill: 'Insight' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { skill: 'Persuade' },
      { skill: 'Research' },
      { skill: 'Sense' },
      { skill: 'Spot' },
    ],
    equipment: ['basic clothing', 'a kit of artistic tools'],
    funds: '1d4x10+5',
    contacts: 2,
    talentPaths: ['Bard', 'Factor'],
  },
  {
    name: 'Athlete',
    description: 'An athlete, your background comes from organized sports, often sponsored by royalty or wealthy merchants.',
    d100: [84, 86],
    rarity: 'Rare',
    archetype: 'Warrior',
    skills: [
      { skill: 'Brawl' },
      { skill: 'Climb' },
      { skill: 'Dodge' },
      { skill: 'Grapple' },
      { skill: 'Jump' },
      { skill: 'Listen' },
      { skill: 'Spot' },
      { skill: 'Stealth' },
      { skill: 'Swim' },
      { skill: 'Throw' },
    ],
    equipment: ['basic and fine clothes'],
    funds: '1d4x10+10',
    contacts: 1,
    talentPaths: ['Fighter'],
  },
  {
    name: 'Spy',
    description: 'You are skilled in subterfuge and infiltration, entering countries or organizations under cover or in secret, finding out their secrets, and reporting them back to an enemy or interested party.',
    d100: [87, 90],
    rarity: 'Rare',
    archetype: 'Expert', // table also suggests Warrior
    skills: [
      { skill: 'Disguise' },
      { skill: 'Dodge' },
      { skill: 'Fast Talk' },
      { skill: 'Hide' },
      { skill: 'Listen' },
      { skill: 'Ranged Weapons' },
      { skill: 'Research' },
      { skill: 'Spot' },
      { skill: 'Stealth' },
      { skill: 'Track' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+20',
    contacts: 1,
    talentPaths: ['Rogue'],
  },
  {
    name: 'Assassin',
    description: 'As a coldblooded professional assassin, death is your trade. Whether you kill for money or some other cause, you are skilled in the termination of other living beings, usually in secrecy.',
    d100: [91, 92],
    rarity: 'Very Rare',
    archetype: 'Expert', // table also suggests Warrior
    skills: [
      { skill: 'Disguise' },
      { skill: 'Dodge' },
      { skill: 'Fine Manipulation' },
      { skill: 'Hide' },
      { skill: 'Listen' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Ranged Weapons' },
      { skill: 'Spot' },
      { skill: 'Stealth' },
      { skill: 'Track' },
    ],
    equipment: ['basic dark clothing', 'a dagger', 'a light crossbow'],
    funds: '1d4x10+10',
    contacts: 0,
    talentPaths: ['Rogue'],
  },
  {
    name: 'Mage',
    description: 'You were training in one of the many ways of magic in the world. This does not grant you the ability to cast spells, only understand their base mechanics, their history, and their lore.',
    d100: [93, 94],
    rarity: 'Very Rare',
    archetype: 'Mage',
    skills: [
      { skill: 'Fine Manipulation' },
      { skill: 'Insight' },
      { skill: 'Knowledge', specialty: 'Arcana' }, // errata: Knowledge Arcana added/defined
      { skill: 'Listen' },
      { skill: 'Persuade' },
      { skill: 'Research' },
      { skill: 'Sense' },
      { skill: 'Spellcraft' },
      { skill: 'Spot' },
      { skill: 'Teach' },
    ],
    equipment: ['basic clothing', 'a journal', 'ink and quill', 'a light weapon'],
    funds: '1d4x10+10',
    contacts: 0,
    talentPaths: ['Bard', 'Luminar', 'Wylder'],
  },
  {
    name: 'Monster Hunter',
    description: 'Since the Return, the lands have been plagued with creatures who want nothing more than to harm those in Atheles. You are determined to stop them.',
    d100: [95, 95],
    rarity: 'Very Rare',
    archetype: 'Expert',
    skills: [
      { skill: 'Dodge' },
      { skill: 'Grapple' },
      { skill: 'Hide' },
      { skill: 'Knowledge', specialty: 'Monster Lore' }, // a Knowledge Expertise (see Knowledge skill)
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Ranged Weapons' },
      { skill: 'Spot' },
      { skill: 'Stealth' },
      { skill: 'Survival' },
      { skill: 'Track' },
    ],
    equipment: ['basic clothing', 'soft leather armor', 'iron manacles', 'a medium weapon'],
    funds: '1d4x10+10',
    contacts: 0,
    talentPaths: ['Archeon', 'Ranger'],
  },
  {
    name: 'Mystic',
    description: 'You focus on the spiritual side of the world, often finding yourself in deep study or research. While you enjoy all knowledge you focus on the mystical. You can be a spiritual leader of a tribe, or a researcher in a…',
    d100: [96, 96], // errata #9 (confirmed 7-14): Mystic added to profession chart: 96, Very Rare, Mage
    rarity: 'Very Rare',
    archetype: 'Mage',
    skills: [
      { skill: 'First Aid' },
      { skill: 'Insight' },
      { skill: 'Knowledge', specialty: 'Arcana' },
      { skill: 'Listen' },
      { skill: 'Medicine' }, // data note: printed "Medicene" (typo); normalized to canonical Medicine
      { skill: 'Persuade' },
      { skill: 'Research' },
      { skill: 'Sense' },
      { skill: 'Survival' },
      { skill: 'Spellcraft' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+20',
    contacts: 0,
    talentPaths: ['Wylder', 'Factor'], // doc: "Wylder or Factor"
  },
  {
    name: 'Noble',
    description: 'You were born into wealth and a ruling class. In a society that recognizes such social distinctions, your status is often associated with ranks and titles, but even if such titles are meaningless, you are still…',
    d100: [97, 97],
    rarity: 'Very Rare',
    archetype: 'Expert', // table also suggests Warrior
    skills: [
      { skill: 'Appraise' }, // errata: Noble lost Literacy, got Appraise (printed list already reflects this)
      { skill: 'Art' },
      { skill: 'Bargain' },
      { skill: 'Command' },
      { skill: 'Etiquette' },
      { skill: 'Insight' },
      { skill: 'Knowledge' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Ride' },
      { skill: 'Strategy' },
    ],
    equipment: ['fancy/fine clothing', 'a light weapon'],
    funds: '1d4x10+40',
    contacts: 2, // one friendly, one adversarial
    talentPaths: ['Factor', 'Fighter'],
  },
  {
    name: 'Occultist',
    description: 'You are a student of obscure secrets, hidden lore, and magical power, believing in the influence and primacy of supernatural forces.',
    d100: [98, 98],
    rarity: 'Very Rare',
    archetype: 'Mage',
    skills: [
      { skill: 'Craft' },
      { skill: 'Fast Talk' },
      { skill: 'Insight' },
      { skill: 'Knowledge', specialty: 'Occult' }, // a Knowledge Expertise (see Knowledge skill)
      { skill: 'Listen' },
      { skill: 'Medicine' },
      { skill: 'Research' },
      { skill: 'Sense' },
      { skill: 'Spellcraft' },
      { skill: 'Teach' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+20',
    contacts: 0,
    talentPaths: ['Luminar', 'Wylder'],
  },
  {
    name: 'Witch Hunter',
    description: 'You are training in hunting mages, whether you find heretics who offended the church or a necromancer who defiles the graves.',
    d100: [99, 100],
    rarity: 'Very Rare',
    archetype: 'Mage', // table also suggests Warrior
    skills: [
      { skill: 'Brawl' },
      { skill: 'Dodge' },
      { skill: 'Grapple' },
      { skill: 'Listen' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Ranged Weapons' },
      { skill: 'Sense' },
      { skill: 'Spellcraft' },
      { skill: 'Stealth' },
      { skill: 'Survival' },
    ],
    equipment: ['basic clothing', 'soft leather armor', 'iron manacles', 'a medium weapon'],
    funds: '1d4x10+10',
    contacts: 0,
    talentPaths: ['Archeon'],
  },
];
