/**
 * SagaBorn D100 — Professions (Profession Lifepath)
 *
 * Sources:
 *  - /home/claude/d100srd-rules-v2/002-creating-a-character.md (Profession
 *    Lifepath d100 table + the 30 detailed profession entries), doc pull 2026-07-14
 *  - /home/claude/errata-2026-07-13.md (Mike's rulings, 7-13-2026)
 *
 * RULE OF PRECEDENCE: the errata WINS over chapter text on any conflict.
 *
 * Errata applied here: #9 / Part 2 (Mystic added to profession chart: 96,
 * Very Rare, Mage — confirmed 7-14), exec summary #3 (Persuasion is always
 * Persuade; Knowledge Arcana; Pilot specialties Air/Land/Sea), Part 2
 * (profession rarity matched to chart; Gambler 12d4 funds intentional;
 * Noble lost Literacy, got Appraise — printed skill list already reflects it),
 * #33 (starter packages: always soft leather; small weapons = light weapons).
 *
 * d100 ranges transcribed exactly from the rebuilt table (tiles 1-100).
 * Skill names normalized to canonical SKILLS keys (Persuade, Medicine,
 * Craft, Siege Weapon, ...); "(Any)" melee grants use choiceOfGroup per
 * errata #12 (umbrellas are skill GROUPS).
 */

import { Profession } from './types';

export const PROFESSIONS: Profession[] = [
  {
    name: 'Crafter',
    d100: [1, 4],
    rarity: 'Very Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Appraise' },
      { skill: 'Art' },
      { skill: 'Bargain' },
      { skill: 'Craft', specialty: 'Any' }, // "any two Craft skills" — first pick
      { skill: 'Craft', specialty: 'Any' }, // "any two Craft skills" — second pick
      { skill: 'Fine Manipulation' },
      { skill: 'Persuade' },
      { skill: 'Spot' },
      { skill: 'Repair' },
      { skill: 'Research' },
    ],
    equipment: ['basic clothing', 'tools of the trade (but not a workshop)'],
    funds: '1d4x10+20',
    contacts: 0,
    talentPaths: ['Factor', 'Luminar'],
  },
  {
    name: 'Farmer',
    d100: [5, 8],
    rarity: 'Very Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Bargain' },
      { skill: 'Craft' },
      { skill: 'First Aid' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { skill: 'Repair' },
      { skill: 'Ranged Weapons' },
      { skill: 'Ride' },
      { skill: 'Spot' },
      { skill: 'Track' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+5',
    contacts: 0,
    talentPaths: ['Fighter', 'Ranger'],
  },
  {
    name: 'Herder',
    d100: [9, 12],
    rarity: 'Very Common',
    archetype: 'Expert', // table also suggests Warrior
    skills: [
      { skill: 'Craft' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { skill: 'Navigate' },
      { skill: 'Ranged Weapons' },
      { skill: 'Ride' },
      { skill: 'Spot' },
      { skill: 'Survival' },
      { skill: 'Throw' },
      { skill: 'Track' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+5',
    contacts: 0,
    talentPaths: ['Fighter', 'Ranger'],
  },
  {
    name: 'Hunter',
    d100: [13, 23],
    rarity: 'Very Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Climb' },
      { skill: 'Hide' },
      { skill: 'Listen' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Navigate' },
      { skill: 'Ranged Weapons' },
      { skill: 'Spot' },
      { skill: 'Stealth' },
      { skill: 'Survival' },
      { skill: 'Track' },
    ],
    equipment: [
      'basic clothing',
      'Shortbow', // data note: printed as "a short bow"; normalized to the catalog weapon name
      'a light weapon',
    ],
    funds: '1d4x5+5',
    contacts: 0,
    talentPaths: ['Ranger'],
  },
  {
    name: 'Laborer',
    d100: [24, 36],
    rarity: 'Very Common',
    archetype: 'Expert', // table also suggests Warrior
    skills: [
      { skill: 'Athletics' },
      { skill: 'Climb' },
      { skill: 'Craft' },
      { skill: 'Brawl' },
      { skill: 'Fine Manipulation' },
      { skill: 'Grapple' },
      { skill: 'Listen' },
      { skill: 'Repair' },
      { skill: 'Sense' },
      { skill: 'Spot' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+5',
    contacts: 0,
    talentPaths: [], // recommended paths: "Any"
  },
  {
    name: 'Servant',
    d100: [37, 42],
    rarity: 'Very Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Craft' },
      { skill: 'Etiquette' },
      { skill: 'Fine Manipulation' },
      { skill: 'First Aid' },
      { skill: 'Hide' },
      { skill: 'Insight' },
      { skill: 'Listen' },
      { skill: 'Knowledge' },
      { skill: 'Persuade' },
      { skill: 'Stealth' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+10', // doc: "Funds (can vary): 1d4 x 10 + 10 gp (average)"
    contacts: 0,
    talentPaths: ['Factor'],
  },
  {
    name: 'Soldier',
    d100: [43, 48],
    rarity: 'Very Common',
    archetype: 'Warrior',
    skills: [
      { skill: 'Command' },
      { skill: 'Brawl' },
      { skill: 'Climb' },
      { skill: 'Dodge' },
      { skill: 'First Aid' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Ranged Weapons' },
      { skill: 'Siege Weapon' }, // printed "Siege Weapons"; canonical singular
      { skill: 'Spot' },
      { skill: 'Stealth' },
    ],
    equipment: ['basic clothing', 'soft leather armor', 'a medium weapon'],
    funds: '1d4x10+10',
    contacts: 0,
    talentPaths: ['Berserker', 'Fighter'],
  },
  {
    name: 'Warrior',
    d100: [49, 55],
    rarity: 'Very Common',
    archetype: 'Warrior',
    skills: [
      { skill: 'Athletics' },
      { skill: 'Brawl' },
      { skill: 'Dodge' },
      { skill: 'Grapple' },
      { skill: 'Listen' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Ranged Weapons' },
      { skill: 'Shield' },
      { skill: 'Spot' },
      { skill: 'Throw' },
    ],
    equipment: ['basic clothing', 'soft leather armor', 'a medium weapon'],
    funds: '1d4x10+10',
    contacts: 0,
    talentPaths: ['Berserker', 'Fighter'],
  },
  {
    name: 'Beggar',
    d100: [56, 57],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Bargain' },
      { skill: 'Fast Talk' },
      { skill: 'Hide' },
      { skill: 'Insight' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { skill: 'Persuade' },
      { skill: 'Sleight of Hand' },
      { skill: 'Spot' },
      { skill: 'Stealth' },
    ],
    equipment: ['basic clothing (rough)', 'a light weapon'],
    funds: '1d3x10',
    contacts: 3,
    talentPaths: [], // recommended paths: "Any"
  },
  {
    name: 'Criminal',
    d100: [58, 61],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Appraise' },
      { skill: 'Bargain' },
      { skill: 'Fast Talk' },
      { skill: 'Fine Manipulation' },
      { skill: 'Hide' },
      { skill: 'Listen' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Persuade' },
      { skill: 'Spot' },
      { skill: 'Stealth' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+10',
    contacts: 1,
    talentPaths: [], // recommended paths: "Any"
  },
  {
    name: 'Detective',
    d100: [62, 62],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Fast Talk' },
      { skill: 'Hide' },
      { skill: 'Insight' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Persuade' },
      { skill: 'Research' },
      { skill: 'Spot' },
      { skill: 'Track' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+10',
    contacts: 2,
    talentPaths: ['Factor', 'Ranger'],
  },
  {
    name: 'Entertainer',
    d100: [63, 65],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Acrobatics' },
      { skill: 'Art' },
      { skill: 'Disguise' },
      { skill: 'Fast Talk' },
      { skill: 'Fine Manipulation' },
      { skill: 'Insight' },
      { skill: 'Listen' },
      { skill: 'Perform' },
      { skill: 'Persuade' },
      { skill: 'Sense' },
    ],
    equipment: ['basic clothing', 'an instrument'],
    funds: '1d4x10+5',
    contacts: 1,
    talentPaths: ['Bard'],
  },
  {
    name: 'Explorer',
    d100: [66, 69],
    rarity: 'Common',
    archetype: 'Expert', // table also suggests Warrior
    skills: [
      { skill: 'Climb' },
      { skill: 'Jump' },
      { skill: 'Navigate' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Persuade' },
      { skill: 'Research' },
      { skill: 'Ride' },
      { skill: 'Swim' },
      { skill: 'Spot' },
      { skill: 'Survival' },
    ],
    equipment: ['basic clothing', 'a medium weapon', 'a backpack'],
    funds: '1d4x10+10',
    contacts: 0,
    talentPaths: ['Fighter', 'Ranger'],
  },
  {
    name: 'Gambler',
    d100: [70, 72],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Bargain' },
      { skill: 'Brawl' },
      { skill: 'Dodge' },
      { skill: 'Fast Talk' },
      { skill: 'Gaming' },
      { skill: 'Insight' },
      { skill: 'Knowledge' },
      { skill: 'Persuade' },
      { skill: 'Sleight of Hand' },
      { skill: 'Spot' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '12d4', // errata Part 2: Gambler 12d4 is intentional
    contacts: 1,
    talentPaths: ['Bard', 'Factor', 'Rogue'],
  },
  {
    name: 'Lawkeeper / Guard',
    d100: [73, 74],
    rarity: 'Common',
    archetype: 'Warrior',
    skills: [
      { skill: 'Brawl' },
      { skill: 'Dodge' },
      { skill: 'Fast Talk' },
      { skill: 'Grapple' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Ranged Weapons' },
      { skill: 'Spot' },
      { skill: 'Track' },
    ],
    equipment: ['basic clothing', 'a medium weapon'],
    funds: '1d4x10+5',
    contacts: 1,
    talentPaths: ['Archeon', 'Fighter'],
  },
  {
    name: 'Merchant',
    d100: [75, 75],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Appraise' },
      { skill: 'Bargain' },
      { skill: 'Command' },
      { skill: 'Fast Talk' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { skill: 'Persuade' },
      { skill: 'Research' },
      { skill: 'Sense' },
      { skill: 'Spot' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+20',
    contacts: 0,
    talentPaths: ['Factor'],
  },
  {
    name: 'Politician',
    d100: [76, 76],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Bargain' },
      { skill: 'Command' },
      { skill: 'Etiquette' },
      { skill: 'Fast Talk' },
      { skill: 'Insight' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { skill: 'Perform', specialty: 'Orate' }, // data note: printed "Perform (Oratory)"; canonical Perform specialty is "Orate"
      { skill: 'Persuade' },
      { skill: 'Research' },
    ],
    equipment: ['fine clothing', 'a light weapon'],
    funds: '1d4x10+10',
    contacts: 4, // two friendly, two adversarial
    talentPaths: [], // recommended paths: "Any"
  },
  {
    name: 'Priest',
    d100: [77, 77],
    rarity: 'Common',
    archetype: 'Expert', // table also suggests Mage
    skills: [
      { skill: 'Command' },
      { skill: 'Fast Talk' },
      { skill: 'Insight' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { skill: 'Perform' },
      { skill: 'Persuade' },
      { skill: 'Research' },
      { skill: 'Sense' },
      { skill: 'Spellcraft' },
    ],
    equipment: ['basic or fine clothing'],
    funds: '1d4x10+10',
    contacts: 2,
    talentPaths: ['Luminar'],
  },
  {
    name: 'Sailor',
    d100: [78, 78],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Climb' },
      { skill: 'Dodge' },
      { skill: 'Grapple' },
      { skill: 'Navigate' },
      { choiceOfGroup: 'melee-weapon' }, // printed "Melee Weapons (Any)"
      { skill: 'Pilot', specialty: 'Sea' },
      { skill: 'Ranged Weapons' },
      { skill: 'Repair' },
      { skill: 'Spot' },
      { skill: 'Swim' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+10',
    contacts: 0,
    talentPaths: ['Fighter', 'Rogue'],
  },
  {
    name: 'Scholar',
    d100: [79, 79],
    rarity: 'Common',
    archetype: 'Expert', // table also suggests Mage
    skills: [
      { skill: 'Appraise' },
      { skill: 'Art' },
      { skill: 'Craft' },
      { skill: 'Insight' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { skill: 'Persuade' },
      { skill: 'Research' },
      { skill: 'Spot' },
      { skill: 'Teach' },
    ],
    equipment: ['basic clothing', 'a journal', 'ink and quill'],
    funds: '1d4x5+10',
    contacts: 1,
    talentPaths: ['Bard', 'Factor', 'Luminar'],
  },
  {
    name: 'Thief',
    d100: [80, 80],
    rarity: 'Common',
    archetype: 'Expert',
    skills: [
      { skill: 'Appraise' },
      { skill: 'Climb' },
      { skill: 'Dodge' },
      { skill: 'Fast Talk' },
      { skill: 'Fine Manipulation' },
      { skill: 'Hide' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Ranged Weapons' },
      { skill: 'Spot' },
      { skill: 'Stealth' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+20',
    contacts: 1,
    talentPaths: ['Rogue'],
  },
  {
    name: 'Artist',
    d100: [81, 83],
    rarity: 'Rare',
    archetype: 'Expert',
    skills: [
      { skill: 'Art' }, // printed "Art (drawing, painting, sculpting, etc)" — examples, not a fixed specialty
      { skill: 'Craft', specialty: 'Art' }, // data note: printed "Crafting" (not a canonical skill); normalized to Craft with an Art specialty
      { skill: 'Etiquette' },
      { skill: 'Insight' },
      { skill: 'Knowledge' },
      { skill: 'Listen' },
      { skill: 'Persuade' },
      { skill: 'Research' },
      { skill: 'Sense' },
      { skill: 'Spot' },
    ],
    equipment: ['basic clothing', 'a kit of artistic tools'],
    funds: '1d4x10+5',
    contacts: 2,
    talentPaths: ['Bard', 'Factor'],
  },
  {
    name: 'Athlete',
    d100: [84, 86],
    rarity: 'Rare',
    archetype: 'Warrior',
    skills: [
      { skill: 'Brawl' },
      { skill: 'Climb' },
      { skill: 'Dodge' },
      { skill: 'Grapple' },
      { skill: 'Jump' },
      { skill: 'Listen' },
      { skill: 'Spot' },
      { skill: 'Stealth' },
      { skill: 'Swim' },
      { skill: 'Throw' },
    ],
    equipment: ['basic and fine clothes'],
    funds: '1d4x10+10',
    contacts: 1,
    talentPaths: ['Fighter'],
  },
  {
    name: 'Spy',
    d100: [87, 90],
    rarity: 'Rare',
    archetype: 'Expert', // table also suggests Warrior
    skills: [
      { skill: 'Disguise' },
      { skill: 'Dodge' },
      { skill: 'Fast Talk' },
      { skill: 'Hide' },
      { skill: 'Listen' },
      { skill: 'Ranged Weapons' },
      { skill: 'Research' },
      { skill: 'Spot' },
      { skill: 'Stealth' },
      { skill: 'Track' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+20',
    contacts: 1,
    talentPaths: ['Rogue'],
  },
  {
    name: 'Assassin',
    d100: [91, 92],
    rarity: 'Very Rare',
    archetype: 'Expert', // table also suggests Warrior
    skills: [
      { skill: 'Disguise' },
      { skill: 'Dodge' },
      { skill: 'Fine Manipulation' },
      { skill: 'Hide' },
      { skill: 'Listen' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Ranged Weapons' },
      { skill: 'Spot' },
      { skill: 'Stealth' },
      { skill: 'Track' },
    ],
    equipment: ['basic dark clothing', 'a dagger', 'a light crossbow'],
    funds: '1d4x10+10',
    contacts: 0,
    talentPaths: ['Rogue'],
  },
  {
    name: 'Mage',
    d100: [93, 94],
    rarity: 'Very Rare',
    archetype: 'Mage',
    skills: [
      { skill: 'Fine Manipulation' },
      { skill: 'Insight' },
      { skill: 'Knowledge', specialty: 'Arcana' }, // errata: Knowledge Arcana added/defined
      { skill: 'Listen' },
      { skill: 'Persuade' },
      { skill: 'Research' },
      { skill: 'Sense' },
      { skill: 'Spellcraft' },
      { skill: 'Spot' },
      { skill: 'Teach' },
    ],
    equipment: ['basic clothing', 'a journal', 'ink and quill', 'a light weapon'],
    funds: '1d4x10+10',
    contacts: 0,
    talentPaths: ['Bard', 'Luminar', 'Wylder'],
  },
  {
    name: 'Monster Hunter',
    d100: [95, 95],
    rarity: 'Very Rare',
    archetype: 'Expert',
    skills: [
      { skill: 'Dodge' },
      { skill: 'Grapple' },
      { skill: 'Hide' },
      { skill: 'Knowledge', specialty: 'Monster Lore' }, // a Knowledge Expertise (see Knowledge skill)
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Ranged Weapons' },
      { skill: 'Spot' },
      { skill: 'Stealth' },
      { skill: 'Survival' },
      { skill: 'Track' },
    ],
    equipment: ['basic clothing', 'soft leather armor', 'iron manacles', 'a medium weapon'],
    funds: '1d4x10+10',
    contacts: 0,
    talentPaths: ['Archeon', 'Ranger'],
  },
  {
    name: 'Mystic',
    d100: [96, 96], // errata #9 (confirmed 7-14): Mystic added to profession chart: 96, Very Rare, Mage
    rarity: 'Very Rare',
    archetype: 'Mage',
    skills: [
      { skill: 'First Aid' },
      { skill: 'Insight' },
      { skill: 'Knowledge', specialty: 'Arcana' },
      { skill: 'Listen' },
      { skill: 'Medicine' }, // data note: printed "Medicene" (typo); normalized to canonical Medicine
      { skill: 'Persuade' },
      { skill: 'Research' },
      { skill: 'Sense' },
      { skill: 'Survival' },
      { skill: 'Spellcraft' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+20',
    contacts: 0,
    talentPaths: ['Wylder', 'Factor'], // doc: "Wylder or Factor"
  },
  {
    name: 'Noble',
    d100: [97, 97],
    rarity: 'Very Rare',
    archetype: 'Expert', // table also suggests Warrior
    skills: [
      { skill: 'Appraise' }, // errata: Noble lost Literacy, got Appraise (printed list already reflects this)
      { skill: 'Art' },
      { skill: 'Bargain' },
      { skill: 'Command' },
      { skill: 'Etiquette' },
      { skill: 'Insight' },
      { skill: 'Knowledge' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Ride' },
      { skill: 'Strategy' },
    ],
    equipment: ['fancy/fine clothing', 'a light weapon'],
    funds: '1d4x10+40',
    contacts: 2, // one friendly, one adversarial
    talentPaths: ['Factor', 'Fighter'],
  },
  {
    name: 'Occultist',
    d100: [98, 98],
    rarity: 'Very Rare',
    archetype: 'Mage',
    skills: [
      { skill: 'Craft' },
      { skill: 'Fast Talk' },
      { skill: 'Insight' },
      { skill: 'Knowledge', specialty: 'Occult' }, // a Knowledge Expertise (see Knowledge skill)
      { skill: 'Listen' },
      { skill: 'Medicine' },
      { skill: 'Research' },
      { skill: 'Sense' },
      { skill: 'Spellcraft' },
      { skill: 'Teach' },
    ],
    equipment: ['basic clothing', 'a light weapon'],
    funds: '1d4x10+20',
    contacts: 0,
    talentPaths: ['Luminar', 'Wylder'],
  },
  {
    name: 'Witch Hunter',
    d100: [99, 100],
    rarity: 'Very Rare',
    archetype: 'Mage', // table also suggests Warrior
    skills: [
      { skill: 'Brawl' },
      { skill: 'Dodge' },
      { skill: 'Grapple' },
      { skill: 'Listen' },
      { choiceOfGroup: 'melee-weapon' }, // "Melee Weapon Skill (Any)"
      { skill: 'Ranged Weapons' },
      { skill: 'Sense' },
      { skill: 'Spellcraft' },
      { skill: 'Stealth' },
      { skill: 'Survival' },
    ],
    equipment: ['basic clothing', 'soft leather armor', 'iron manacles', 'a medium weapon'],
    funds: '1d4x10+10',
    contacts: 0,
    talentPaths: ['Archeon'],
  },
];
