/**
 * SagaBorn D100 — Spells
 *
 * Source: 004-magic.md (2026-07-14 doc pull), stat blocks under "Spell Descriptions"
 * (encoded from the ### headings — the doc's index list is missing 8 spells).
 * Errata (2026-07-13) WINS applied:
 *   #20 — all "caster level" references read as "per mage's Talent Point Level".
 *   #21 — buff spells CAN break the characteristic cap; adding to a Characteristic
 *         changes dependent skills; SIZ/CON changes adjust HP for the spell duration.
 *   #22 — unified elemental rider effects (Fire=On Fire, Water=douses/dilutes,
 *         Ice=slow 1/2 STR negates, Earth=dust outlines invisible, Electricity=+1d4
 *         vs heavy metal armor, Air=knocks SIZ<=20 prone DEX negates); flagged with
 *         `elemental: true`. Elemental Summoning and Elemental Wall intentionally differ.
 * Typography: curly quotes/apostrophes from the doc normalized to ASCII.
 */

import { Spell } from './types';

export const SPELLS: Spell[] = [
  {
    name: 'Acid Bolt',
    type: 'Damage',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'Dodge, Parry*',
    summary:
      '1d4+1 acid damage per mana, 60 ft, aimed with Spot; also acts as acid, causing 1 AV damage for 1d4 rounds.',
  },
  {
    name: 'Acid Fog',
    type: 'Damage',
    mana: { perLevel: true, min: 3 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: '1d4 rounds per mana level',
    target: "AoE 5' Radius Sphere per mana level",
    avoidance: 'None',
    summary:
      'Corrosive fog (3 mana per level) deals 1d4 damage on cast and at end of turn to creatures inside, and reduces worn armor AV by 1 per round; 5 ft radius per level, aimed with Spot; water/bases halve damage.',
  },
  {
    name: 'Aid',
    type: 'Buff',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: 'Touch',
    duration: '1 minute',
    target: 'Single Target',
    avoidance: 'None',
    summary: '+10 per mana to a chosen skill until that skill is used.',
  },
  {
    name: 'Animal Friend',
    type: 'Utility',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: '1 minute per mana',
    target: 'Single Target',
    summary:
      'Use Persuasion with animals at +10% per mana level; simple two-way communication of emotions and directions.',
  },
  {
    name: 'Babble',
    type: 'Mind',
    mana: {
      tiers: [
        { mana: 1, effect: "The target's words become incoherent." },
        { mana: 2, effect: 'The target cannot stop speaking, compelled to talk while no one understands them.' },
        { mana: 3, effect: 'The target frantically babbles, making no sense even to themselves; all their actions are Difficult.' },
      ],
    },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: 'Concentration',
    target: 'Single Target',
    avoidance: 'Acumen',
    summary:
      "Target can only make incoherent noises; any mana level makes all the target's communication and spellcasting Difficult; target may save each round on their turn.",
  },
  {
    name: "Bear's Strength",
    type: 'Buff',
    mana: {
      tiers: [
        { mana: 2, effect: '+10 to STR' },
        { mana: 4, effect: '+20 to STR' },
        { mana: 6, effect: '+30 to STR' },
      ],
    },
    castingTime: '1 Standard Action',
    range: 'Touch',
    duration: '1 minute',
    target: 'Single Target',
    avoidance: 'None',
    summary:
      '+10/+20/+30 STR for 2/4/6 mana. Per errata #21: the buff CAN break the characteristic cap, adjusts STR-dependent skills, and (for SIZ/CON buffs) HP adjusts for the spell duration.',
  },
  {
    name: 'Befriend',
    type: 'Mind',
    mana: { flat: 3 },
    castingTime: '1 Standard Action',
    range: "30'",
    duration: '1 Hour per ACU',
    target: 'Single Target',
    avoidance: 'Contested Roll; Acumen vs. Acumen',
    summary:
      'Target treats the caster as a friend; Persuade attempts against them become Easy unless dangerous or against their beliefs; target keeps memories and free will otherwise.',
  },
  {
    name: 'Bend Sound',
    type: 'Damage',
    mana: {
      tiers: [
        {
          mana: 1,
          effect:
            'Piercing sound: shatters non-magical crystal/glass/ceramic/porcelain in a 5 ft radius (unless over 1 lb per Talent Point Level), 1d6 sonic to exposed fragile objects and crystalline creatures; or deafen one target 2d4 rounds (CON save halves duration).',
        },
        { mana: 3, effect: "Counter and dispel a Silence spell via Heroic action vs the opposing caster's Spellcraft." },
        {
          mana: 5,
          effect: '30 ft area blast: 3d8 sonic damage, CON save or stunned 1 round; 1d6 sonic to fragile/crystalline; does not penetrate Silence.',
        },
        {
          mana: 7,
          effect: '60 ft cone scream: 5d6 sonic damage and deafened 2d6 rounds; Acumen save resists deafness, Dodge halves damage; does not penetrate Silence.',
        },
      ],
    },
    castingTime: '1 Standard Action',
    range: 'Varies',
    duration: '1 round per level',
    target: 'Varies',
    avoidance: 'Dodge for half unless otherwise stated',
    summary: 'Manipulate sound: shatter/deafen (1), counter Silence (3), 3d8 stunning blast (5), or 5d6 deafening cone (7).',
  },
  {
    name: 'Blur',
    type: 'Buff',
    mana: {
      tiers: [
        { mana: 4, effect: 'Target shifts in plane; any attack against them becomes Difficult.' },
        { mana: 7, effect: 'Attacks against target Difficult and the target can move through most solid objects; iron or steel block blurred creatures.' },
      ],
    },
    castingTime: '1 Standard Action',
    range: 'Touch',
    duration: '1 minute',
    target: 'Single Target',
    avoidance: 'None',
    summary: 'Attacks against the blurred target become Difficult (4 mana); at 7 mana the target can also pass through most solid objects (iron/steel block).',
  },
  {
    name: "Cat's Dexterity",
    type: 'Buff',
    mana: {
      tiers: [
        { mana: 2, effect: '+10 to DEX' },
        { mana: 4, effect: '+20 to DEX' },
        { mana: 6, effect: '+30 to DEX' },
      ],
    },
    castingTime: '1 Standard Action',
    range: 'Touch',
    duration: '1 minute',
    target: 'Single Target',
    summary:
      '+10/+20/+30 DEX for 2/4/6 mana. Per errata #21: the buff CAN break the characteristic cap, adjusts DEX-dependent skills, and (for SIZ/CON buffs) HP adjusts for the spell duration.',
  },
  {
    name: 'Command',
    type: 'Mind',
    mana: {
      tiers: [
        { mana: 1, effect: 'Single-word command ("drop", "halt", "flee"); target obeys on its next action and can do nothing else for one round.' },
        { mana: 3, effect: "Simple command; target obeys and does nothing else for one round per mage's Talent Point Level." },
        { mana: 5, effect: 'Detailed command; target obeys on its next action and continues for 1 minute per mana spent.' },
        { mana: 7, effect: "Complex directive; target obeys for one day per mage's Talent Point Level or until the task is complete." },
      ],
    },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'Contested Roll; Acumen vs. Acumen',
    summary:
      'Compel a creature to obey a command; duration of obedience scales with mana (round to a day per Talent Point Level); no effect on undead or creatures that do not understand you; avoided targets are dazed for rounds equal to mana spent.',
    dataNotes: ['duration field contradicts effect text — pending doc fix'],
  },
  {
    name: 'Conjure Creature',
    type: 'Summoning',
    mana: {
      tiers: [
        { mana: 1, effect: 'Creature: 8 HP, AV 1, (2) attacks/Dodge 60%, 1d6 damage.' },
        { mana: 3, effect: 'Creature: 12 HP, AV 2, (2) attacks/Dodge 60%, 1d6+2 damage.' },
        { mana: 5, effect: 'Creature: 16 HP, AV 3, (2) attacks/Dodge 60%, 1d8+1 damage.' },
        { mana: 7, effect: 'Creature: 24 HP, AV 5, (2) attacks/Dodge 60%, 1d10+1 damage.' },
      ],
    },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: '2 rounds per mana',
    target: 'Empty Space',
    avoidance: 'None',
    summary:
      "Summons a mana-bodied creature from the Navirim (e.g. imp, wolf, fox, large cat) that acts on the caster's turn and fights with full abilities; stats scale from 8 HP/1d6 (1 mana) to 24 HP/1d10+1 (7 mana).",
  },
  {
    name: 'Countermagic',
    type: 'Debuff',
    mana: { perLevel: true, min: 1 },
    castingTime: 'Reaction',
    range: "100'",
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'Contested Roll; Spellcraft vs. Spellcraft',
    summary:
      "Reaction: declare mana before learning the enemy spell's cost, then contest Spellcraft; on a win, cancels the target spell if your mana meets or exceeds its cost, otherwise lowers its mana level by the mana you spent.",
  },
  {
    name: 'Creeping Element',
    type: 'Damage',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'N/A',
    elemental: true,
    summary:
      "1d4+1 damage per mana of a chosen element, ignoring the target's AV, plus the elemental rider effect.",
    dataNotes: [
      'inline rider text differs from the unified errata #22 table (Water/Air cause Panicked, Earth adds 1-round blindness) but errata lists only Elemental Summoning and Wall as intentionally different — pending doc fix',
    ],
  },
  {
    name: 'Cure Disease',
    type: 'Healing',
    mana: { perLevel: true, min: 3 },
    castingTime: '1 hour',
    range: 'Touch',
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'N/A',
    summary: "+10% to the target's next CON save vs a disease per mana level (3 mana per level).",
  },
  {
    name: 'Dark',
    type: 'Utility',
    mana: { perLevel: true, min: 3 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'Dodge',
    summary:
      'An object radiates shadowy illumination in a 20 ft radius (+20 ft per level); creatures inside are concealed (actions against them Difficult), even vs dark vision; normal lights and lower-level Light spells cannot brighten it; counters Light via Heroic action on Spellcraft.',
    dataNotes: ['duration field contradicts effect text — pending doc fix'],
  },
  {
    name: 'Dismiss',
    type: 'Debuff',
    mana: { perLevel: true, min: 5 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: 'Instant',
    target: 'Single Target per mana level',
    avoidance: 'Contested Roll; Acumen vs. Acumen',
    summary:
      'Forces an extraplanar creature back to the Navirim on a won Heroic Action (caster ACU vs defender ACU); one target per mana level (5 mana each).',
  },
  {
    name: 'Dispel',
    type: 'Utility',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "100'",
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'None',
    summary:
      'Ends one spell the caster is aware of if the mana spent overcomes the target spell\'s mana — no contest roll; targets a single spell only; also usable against summoned creatures and magical traps.',
  },
  {
    name: 'Elemental Arrow',
    type: 'Damage',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: 'Varies',
    duration: 'Instant',
    target: 'Single or MultipleTarget',
    avoidance: 'Dodge',
    elemental: true,
    summary:
      '1d8+3 magical or elemental damage per arrow, 60 ft range; each additional mana adds another arrow (separate targets allowed, matching element) and +60 ft range; each arrow aimed individually; elemental riders apply on damage.',
  },
  {
    name: 'Elemental Blast',
    type: 'Damage',
    mana: { perLevel: true, min: 2 },
    castingTime: '1 Standard Action',
    range: 'Varies',
    duration: '1 minute per mana',
    target: "AoE 5' Radius Sphere per mana level",
    avoidance: 'Dodge for half',
    elemental: true,
    summary:
      '2 mana: 1d6+1 damage, 5 ft radius sphere, 30 ft range; each additional level adds 1d6+1 damage, +5 ft radius, +30 ft range; aimed with Spot; Dodge for half; elemental riders apply on damage.',
    dataNotes: ['duration field contradicts effect text — pending doc fix'],
  },
  {
    // Doc types this 'Damage', but it is a self-buff that punishes melee attackers — encoded as Buff.
    name: 'Elemental Shield',
    type: 'Buff',
    mana: { perLevel: true, min: 3 },
    castingTime: '1 Standard Action',
    range: 'Self',
    duration: '3 rounds per mana level',
    target: 'Self',
    avoidance: 'None',
    summary:
      'Wreathes the caster in magical or elemental energy: any creature striking with body or handheld weapon (not reach) takes 1d6+1 damage per mana level; each element variant grants half damage vs its opposing element and side effects (e.g. Fire Shield lights 30 ft).',
    dataNotes: ["doc stat block types this 'Damage' but it is a self-buff — encoded as Buff, pending doc fix"],
  },
  {
    name: 'Elemental Storm',
    type: 'Damage',
    mana: { perLevel: true, min: 2 },
    castingTime: '1 Standard Action',
    range: 'Varies',
    duration: '1d4 rounds',
    target: 'AoE Radius Sphere per mana level',
    avoidance: 'Dodge for half',
    elemental: true,
    summary:
      '2 mana: 1d4+1 damage raining down in a 10 ft radius, 50 ft range; each additional level adds 1d4+1 damage, +10 ft radius, +15 ft range; needs open sky above; aimed with Spot; elemental riders apply on damage.',
  },
  {
    name: 'Elemental Sphere',
    type: 'Damage',
    mana: { perLevel: true, min: 3 },
    castingTime: '1 Standard Action',
    range: "100'",
    duration: '2 rounds per mana',
    target: '5 ft. diameter sphere',
    avoidance: 'Dodge for half',
    elemental: true,
    summary:
      'A rolling 5 ft globe of elemental energy moves 30 ft per round while the caster concentrates, rolling over barriers under 4 ft; deals its elemental effect to creatures in its space, +1d6 per mana level; winks out beyond 100 ft.',
  },
  {
    name: 'Elemental Wall',
    type: 'Damage',
    mana: {
      tiers: [
        { mana: 1, effect: '10 ft long, 10 ft tall, 1 ft thick wall dealing 1d4+1 damage to anyone passing through.' },
        { mana: 3, effect: '20 ft long wall dealing 3d4+3 damage to anyone passing through.' },
        { mana: 5, effect: '40 ft long wall dealing 3d6+3; can encircle the caster at a 5 ft radius (off-center allowed).' },
        { mana: 7, effect: '50 ft long wall dealing 5d6+5; 10 ft radius ring; one side may emit energy dealing 1d4+1 to anyone within 10 ft.' },
      ],
    },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: '1 min per mana',
    target: 'Single Target',
    avoidance: 'None',
    elemental: true,
    summary:
      'Conjures a wall of a controlled element that damages anyone passing through, from 1d4+1 (1 mana, 10 ft) up to 5d6+5 (7 mana, 50 ft, can ring the caster).',
    dataNotes: ["errata #22 notes Elemental Wall's elemental effects intentionally differ from the unified rider table"],
  },
  {
    name: 'Enfeeble',
    type: 'Debuff',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "30'",
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'CON save',
    summary: "Target's next skill check suffers -5% per mana level.",
  },
  {
    name: 'Fear',
    type: 'Mind',
    mana: {
      tiers: [
        { mana: 1, effect: 'A single target becomes Shaken.' },
        { mana: 3, effect: 'A single target becomes Scared.' },
        { mana: 5, effect: 'Up to three creatures become Scared.' },
        { mana: 7, effect: 'Up to three creatures become Panicked.' },
      ],
    },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: '1 minute',
    target: 'Varies',
    avoidance: 'Contested Roll; Acumen vs. Acumen',
    summary:
      "Inflicts Shaken/Scared/Panicked by mana tier; after the first round a Scared or Panicked creature may roll ACU vs the caster's Spellcraft to downgrade to Shaken for the remainder.",
  },
  {
    name: 'Find',
    type: 'Utility',
    mana: { flat: 5 },
    castingTime: '1 hour',
    range: '15 miles',
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'None',
    summary:
      'Sense the direction (and direction of travel) of a familiar person, known item, or kind of item within 15 miles; kinds of creature require having seen one within 30 ft.',
  },
  {
    name: "Fox's Fascination",
    type: 'Buff',
    mana: {
      tiers: [
        { mana: 2, effect: '+10 to SOC' },
        { mana: 4, effect: '+20 to SOC' },
        { mana: 6, effect: '+30 to SOC' },
      ],
    },
    castingTime: '1 Standard Action',
    range: 'Touch',
    duration: '1 minute',
    target: 'Single Target',
    avoidance: 'None',
    summary:
      '+10/+20/+30 SOC for 2/4/6 mana. Per errata #21: the buff CAN break the characteristic cap, adjusts SOC-dependent skills, and (for SIZ/CON buffs) HP adjusts for the spell duration.',
  },
  {
    name: 'Gain Spirit',
    type: 'Buff',
    mana: { perLevel: true, min: 3 },
    castingTime: '1 Standard Action',
    range: 'Touch',
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'None',
    summary: 'Target recovers 1 lost Spirit Point per 3 mana spent.',
  },
  {
    name: 'Heal',
    type: 'Healing',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: 'Touch',
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'Dodge',
    summary: 'Touch heals 1d6+3 per mana spent.',
    dataNotes: ["avoidance 'Dodge' on a beneficial touch spell looks erroneous — pending doc fix"],
  },
  {
    name: 'Identify',
    type: 'Utility',
    mana: { flat: 1 },
    castingTime: '20 Minutes',
    range: 'Touch',
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'None',
    summary:
      'Reveals all magical properties of one item, including activation methods and remaining charges; artifacts may only yield hints.',
  },
  {
    name: 'Illusionary Image',
    type: 'Mind',
    mana: {
      tiers: [
        { mana: 1, effect: 'Visual only — no sound, smell, texture, or temperature.' },
        { mana: 3, effect: 'Visual with minor sounds, but no speech, smell, texture, or temperature.' },
        { mana: 5, effect: 'Visual with full speech, smell, and temperature.' },
        { mana: 7, effect: 'Visual with full speech, smell, texture, and temperature.' },
      ],
    },
    castingTime: '1 Standard Action',
    range: "300'",
    duration: 'Concentration',
    target: 'Empty space',
    avoidance: 'Intellect',
    summary: 'Creates a visual illusion of an object, creature, or force; sensory fidelity scales with mana (1/3/5/7).',
  },
  {
    name: 'Imbue Staff',
    type: 'Buff',
    mana: {
      tiers: [
        { mana: 1, effect: 'Staff gains +5% to hit and +1d4 subdual damage.' },
        { mana: 3, effect: 'Staff gains +10% to hit and +2d4 subdual damage.' },
        { mana: 5, effect: 'Staff gains +15% to hit and +3d4 subdual damage.' },
      ],
    },
    castingTime: '2 minutes',
    range: 'Touch',
    duration: '4 hours',
    target: 'Self',
    avoidance: 'None',
    summary: "The caster's staff gains +5%/+10%/+15% to hit and +1d4/+2d4/+3d4 subdual damage for 1/3/5 mana, for 4 hours.",
  },
  {
    name: 'Imbue Weapon',
    type: 'Buff',
    mana: {
      tiers: [
        { mana: 1, effect: 'Weapon gains +5% to hit and +1 damage.' },
        { mana: 3, effect: 'Weapon gains +10% to hit and +2 damage.' },
        { mana: 5, effect: 'Weapon gains +15% to hit and +3 damage.' },
      ],
    },
    castingTime: '1 Standard Action',
    range: 'Touch',
    duration: '2 minutes',
    target: 'Single weapon',
    avoidance: 'None',
    summary: 'A weapon gains +5%/+10%/+15% to hit and +1/+2/+3 damage for 1/3/5 mana, for 2 minutes.',
  },
  {
    name: 'Invulnerable Sphere',
    type: 'Buff',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: '1 minute',
    target: 'Single Target or Space',
    avoidance: 'None',
    summary:
      'Creates a 5 ft diameter sphere that absorbs 5 HP of damage; each mana past the first adds 5 ft or 5 HP absorbed; does not block outgoing objects or non-damaging spells.',
  },
  {
    name: 'Levitate',
    type: 'Utility',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "30' per mana",
    duration: '2 minutes per mana',
    target: 'Single Target',
    avoidance: 'Contested Roll; Acumen vs. Acumen',
    summary:
      'Levitates a creature or object (1 mana per 10 SIZ), raising or lowering 30 ft per mana each round while the caster concentrates; attacking while levitating is Difficult; targets float down when it ends.',
  },
  {
    name: 'Light',
    type: 'Utility',
    mana: {
      tiers: [
        { mana: 1, effect: 'One object glows like a torch (30 ft light) for 1 hour; blocked by magical darkness.' },
        { mana: 2, effect: 'Up to four mobile lights (100 ft/round, within 10 ft of each other) that can blind/distract (-5% to all skills) or outline hidden foes, negating concealment.' },
        { mana: 3, effect: 'An item sheds daylight-bright light 60 ft (+60 ft dim); counters and dispels Darkness via Heroic action on Spellcraft.' },
        { mana: 5, effect: 'Ray of light: 2d8 damage to a struck creature, +2d8 more vs undead.' },
        { mana: 7, effect: '10 ft sun-bright ball, 300 ft light radius; 3d8 damage within 40 ft (undead 6d8); true daylight for light-vulnerable creatures.' },
      ],
    },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: 'Varies',
    target: 'Creatures or objects',
    avoidance: 'Varies',
    summary:
      'Scaling light magic: torchlight (1), dancing lights (2), daylight item that counters Darkness (3), 2d8 light ray (5), or a miniature sun dealing 3d8 (7); undead take double the listed ray/sun damage.',
    dataNotes: ["doc stat block lists dual type 'Utility (mana 1), Damage (mana 2+)' — encoded as Utility"],
  },
  {
    name: 'Mage Bolt',
    type: 'Damage',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: 'Instant',
    target: 'Single Target per bolt',
    avoidance: 'None',
    summary:
      '1d4+1 force damage per bolt, one bolt per mana level (different targets allowed); cannot miss or be Dodged if any part of the target is visible; bypasses most mundane AV.',
  },
  {
    name: 'Mage Compass',
    type: 'Utility',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'None',
    summary: 'Bestows directional sense: +5% to Navigation skill checks per mana level.',
    dataNotes: ['duration field contradicts effect text — pending doc fix'],
  },
  {
    name: 'Phantasmal Hands',
    type: 'Utility',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: 'Concentration (Max: 10 min per level)',
    target: 'Single Target',
    avoidance: 'See below',
    summary:
      'Spectral hands (MOV 25 ft) pick up, manipulate, Grapple, or pummel (Brawl) for 1d6+1; grappled crush 1d6+1; each extra level adds +5 ft MOV, doubles liftable weight (30 lb / SIZ 2 base), and +1d4 damage.',
  },
  {
    name: 'Phase',
    type: 'Utility',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'Acumen vs Acumen',
    summary:
      "Teleports a complete object of up to 3 SIZ per mana level to anywhere visible within 100 ft; objects in use or held get an avoidance check (holder's/target's ACU); willing targets need no roll.",
  },
  {
    name: 'Protection from Arrows',
    type: 'Buff',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: 'Touch',
    duration: '2 minutes per mana',
    target: 'Single Target',
    avoidance: 'Acumen',
    summary: 'Target becomes Difficult to hit with missile weapons; each additional mana adds 2 minutes or another protected target.',
  },
  {
    name: 'Protection from the Elements',
    type: 'Buff',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: 'Touch',
    duration: '10 minutes per mana',
    target: 'Single Target',
    avoidance: 'Acumen',
    summary: 'Target is immune to a chosen element (fire, water, ice/cold, earth, air, or electricity) for 10 damage; each mana adds 10 minutes and blocks 10 more damage.',
  },
  {
    name: 'Protection from Ravaging',
    type: 'Buff',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "30'",
    duration: '10 minutes per mana',
    target: "10' sphere",
    avoidance: 'Spellcraft',
    summary:
      'A 10 ft sphere blocks all effects of ravaging used to create mana and denies the ravager that mana; does not protect against magic cast with ravaged mana; each level adds 10 minutes and 5 ft.',
  },
  {
    name: 'Protection from the Never',
    type: 'Buff',
    mana: { perLevel: true, min: 3 },
    castingTime: '1 Standard Action',
    range: "30'",
    duration: '10 minutes per level',
    target: 'Single object',
    avoidance: 'Acumen',
    summary:
      'All within 10 ft of a charmed object gain +1 AV vs Fey (Navirite) creatures, or protection from scrying through dreams; each mana level adds 10 minutes and 5 ft.',
  },
  {
    name: 'Push',
    type: 'Utility',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'Contested ACU vs target DEX or STR',
    summary:
      'Force pushes a person or object: per mana, up to 7 SIZ moved 5 ft with 1d6 bludgeoning damage (7 mana = SIZ 49, 35 ft, 7d6); targets larger than the mana allows take damage but are not moved; a DEX/STR save stops the push and halves damage.',
  },
  {
    name: 'Open',
    type: 'Utility',
    mana: {
      tiers: [
        { mana: 1, effect: "Open unlocked boxes, chests, and doors within 15'." },
        { mana: 3, effect: "Open non-magical locked boxes, chests, and doors within 30'." },
        { mana: 7, effect: "Open most magically locked boxes, chests, and doors within 50'; rituals/artifacts above 7 mana stay sealed." },
      ],
    },
    castingTime: '1 Standard Action',
    range: 'Varies',
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'None',
    summary: 'Opens unlocked (1 mana, 15 ft), mundane-locked (3 mana, 30 ft), or magically locked (7 mana, 50 ft) containers and doors.',
  },
  {
    name: "Orrilot's Constitution",
    type: 'Buff',
    mana: {
      tiers: [
        { mana: 2, effect: '+10 to CON' },
        { mana: 4, effect: '+20 to CON' },
        { mana: 6, effect: '+30 to CON' },
      ],
    },
    castingTime: '1 Standard Action',
    range: 'Touch',
    duration: '1 minute',
    target: 'Single Target',
    avoidance: 'None',
    summary:
      "+10/+20/+30 CON for 2/4/6 mana. Per errata #21: the buff CAN break the characteristic cap, adjusts CON-dependent skills, and — as a CON buff — the target's HP (CON+SIZ) adjusts for the spell duration.",
  },
  {
    name: 'Resist',
    type: 'Buff',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: 'Touch',
    duration: '1 minute mana',
    target: 'Single Target',
    avoidance: 'None',
    summary: '+5% to any Save for the duration; each additional mana level gives another +5% or another target.',
    dataNotes: ["duration printed as '1 minute mana' — likely '1 minute per mana', pending doc fix"],
  },
  {
    name: 'Seal',
    type: 'Utility',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: '15 minutes per mana',
    target: 'Single Target',
    avoidance: 'Dodge',
    summary:
      'Magically bonds two fitted, unused inanimate objects (e.g. door and frame) as one and grants them +20 HP; each extra level adds 15 minutes or +20 HP, split declared before casting.',
  },
  {
    name: 'See Magic',
    type: 'Utility',
    mana: {
      tiers: [
        { mana: 1, effect: 'Detect a faint aura in a general area where magic is.' },
        { mana: 2, effect: 'Stronger aura showing the exact area where magic is present.' },
        { mana: 3, effect: 'With a Knowledge Arcana check, learn basic facts about the magic detected.' },
        { mana: 4, effect: 'As the 2 mana version, but lasts 1 hour without concentration.' },
      ],
    },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: 'Concentration',
    target: 'Single Target',
    avoidance: 'None',
    summary:
      'See active magic items and spells within 60 ft with detail scaling by mana; blocked by iron, 1 ft of stone, 3 ft of wood, or magical concealment.',
  },
  {
    name: 'Shape Earth and Stone',
    type: 'Utility',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'Varies',
    summary:
      "Reshape a 5'x5'x5' cube of earth/stone per mana level; Difficult on crafted objects, Very Difficult if the item is in use by a living being.",
  },
  {
    name: 'Shape Metal',
    type: 'Utility',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'Varies',
    summary:
      "Reshape a 5'x5'x5' cube of metal per mana level; Difficult on crafted objects, Very Difficult if in use; hard metals may need multiple checks plus a crafting check.",
  },
  {
    name: 'Shape Wood',
    type: 'Utility',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'Varies',
    summary:
      "Reshape a 5'x5'x5' cube of wood per mana level; Difficult on crafted objects, Very Difficult if the item is in use by a living being.",
  },
  {
    name: 'Shelter',
    type: 'Utility',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "5'",
    duration: '20 minutes',
    target: 'Single Space',
    avoidance: 'None',
    summary:
      'Domed shelter 10 ft wide and 5 ft tall protecting from natural weather (0-115 degrees, snow to acidic rain, not extreme magical events); each extra mana adds 5 ft per side and 20 minutes.',
  },
  {
    name: 'Shield',
    type: 'Buff',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: 'Self',
    duration: '10 minutes per mana',
    target: 'Self',
    avoidance: 'None',
    summary:
      'Weightless floating shield grants +2 AV, blocks Mage Bolts, and has 25 HP; each extra mana doubles duration and HP (AV stays 2); +1 mana charges it with an element so melee attackers (not reach) take 1d6+1 elemental damage, with element-specific resistances.',
  },
  {
    name: 'Sleep',
    type: 'Mind',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "30'",
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'Acumen',
    summary: 'Target falls asleep for 1 minute, +1 minute per additional mana level.',
    dataNotes: ['duration field contradicts effect text — pending doc fix'],
  },
  {
    name: 'Slow',
    type: 'Debuff',
    mana: { flat: 3 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: '1d4 rounds',
    target: 'Single Target',
    avoidance: 'Contested Roll; Acumen vs. Acumen',
    summary:
      'Target moves at 1/2 speed and loses half of their attacks (rounded up) for 1d4 rounds; may retry the save as a Move or Standard action each round after the first.',
  },
  {
    name: 'Sphere of Silence',
    type: 'Utility',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: '1 minute per mana level',
    target: "10' Spherical Space",
    avoidance: 'Difficult Acumen Save',
    summary:
      'A 10 ft sphere negates all sound inside: no speech, silent footfalls, verbal spells fail; making a sound requires a successful (Difficult ACU) save.',
  },
  {
    name: "Spider's Grasp",
    type: 'Utility',
    mana: { flat: 1 },
    castingTime: '1 Standard Action',
    range: 'Touch',
    duration: '10 minutes',
    target: 'Single Target',
    avoidance: 'Dodge',
    summary:
      'Target climbs like a spider, moving at normal speed up walls and across ceilings (needs 3 points of contact); slick or difficult surfaces halve speed.',
  },
  {
    name: 'Spirit Sap',
    type: 'Debuff',
    mana: { perLevel: true, min: 3 },
    castingTime: '1 Standard Action',
    range: "30'",
    duration: 'Instant',
    target: 'Single Target',
    avoidance: 'Contested Roll; Acumen vs. Acumen',
    summary: 'Drains 1d3 Spirit Points from the target into the ether per 3 mana spent.',
  },
  {
    name: 'Summon Animal Spirit',
    type: 'Summoning',
    mana: { perLevel: true, min: 2 },
    castingTime: '1 Standard Action',
    range: "30'",
    duration: '1 minute per mana',
    target: "An empty 5' space",
    avoidance: 'None',
    summary:
      'Summons an animal spirit in the form of any known animal: 2 mana = SIZ 4, CV 1; +1 CV per additional 2 mana (table runs to CV 8 / SIZ 27 at 16 mana); stats per the summoning table, not the animal.',
  },
  {
    name: 'Summon Minor Elemental',
    type: 'Summoning',
    mana: { perLevel: true, min: 2 },
    castingTime: '1 Standard Action',
    range: "30'",
    duration: '1 minute per mana',
    target: "An empty 5' space",
    avoidance: 'None',
    summary:
      "Summons a mindless elemental of the caster's elemental foci: base 10 HP, 45% to hit, 1d4+1 damage plus its element's damage rider; +5 HP, +10% to hit, +1d4+1 damage per additional mana level; max 8 mana; no Dodge/Parry; opposing element deals it double damage, same element heals it. (Element riders here intentionally differ from the unified table, per errata #22.)",
  },
  {
    name: 'Transform',
    type: 'Utility',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: '15 minutes per mana',
    target: 'Single Target',
    avoidance: 'Acumen vs. Acumen',
    summary:
      'Changes a being or object into another shape of the same relative type; level 1 = color/shape only (no SIZ change); level 2+ also changes size (+2 SIZ per mana level) with outward attributes of the new form, characteristics unchanged; breaks if the target is damaged/killed.',
  },
  {
    name: 'Vision',
    type: 'Utility',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: "50'",
    duration: '1 minute',
    target: 'Single Target',
    avoidance: 'None',
    summary:
      "Transfers the caster's sight and hearing to an invisible mobile sphere within range; each additional mana adds 1 minute and 50 ft; casting any other spell ends the effect.",
    dataNotes: ["range printed as 50'' (doubled foot mark) — encoded as 50', pending doc fix"],
  },
  {
    name: 'Ward',
    type: 'Utility',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: 'Touch',
    duration: '2 hours per mana',
    target: 'Single Target or Space',
    avoidance: 'None',
    summary:
      "Wards a touched 10'x10' area: intrusion triggers a loud alarm audible within 100 ft or a silent alert to the caster; the caster may designate people or items that do not trigger it.",
  },
  {
    name: 'Warding Armor',
    type: 'Buff',
    mana: { perLevel: true, min: 1 },
    castingTime: '1 Standard Action',
    range: 'Touch',
    duration: '1 hour',
    target: 'Self',
    avoidance: 'None',
    summary:
      '+1 AV per mana spent (max +4) for 1 hour vs mundane and magical damage, but not elemental damage; no encumbrance; visible to See Magic; negated if the caster wears any iron, steel, or tritium.',
  },
  {
    name: 'Web',
    type: 'Trap',
    mana: { flat: 2 },
    castingTime: '1 Standard Action',
    range: "60'",
    duration: '1d4+1 rounds',
    target: "5' spherical area",
    avoidance: 'Dodge',
    summary:
      'Fills a 5 ft area with sticky webbing (needs 3 anchor points to stay 3-dimensional); snared creatures make all skill checks Difficult; a successful Dodge allows movement at 1/2 speed; a Difficult STR roll frees a caught creature to half speed.',
  },
];

/*
 * Intentionally NOT encoded from 004-magic.md:
 *   - "Title" — placeholder stat block with no name or effect text.
 *   - "Elemental Bond" (Beta Spells) — no stat block, one line of flavor text.
 *   - "Echo Sight" (Beta Spells) — no stat block, fragmentary effect text.
 */
